### ISSUE TITLE
[Question] Run Clair3 with .bam files obtained with LRA.

### ISSUE THREAD

**Issue by waltergallegog** [HKU-BAL/Clair3#102]
Hello,
I have some ONT fastq files that I have aligned using LRA https://github.com/ChaissonLab/LRA, as it has shown advantages over minimap2 (specially in the context of structural variation detection)

I now want to use the resulting .bam for SNP using Clair3.
However, if I understood correctly, the training data for ONT was obtained using minimap2.
Should I stick to minimap2 then, and rerun the alignment of my fastq files, or is it ok to use a .bam resulting from LRA?

Thanks

**Comment by aquaskyline** [comment]
Basically, the choice of aligner wouldn't make a significant difference to Clair3's performance. But to be precise, let me try LRA on a few GIAB samples and turn back to you.

**Comment by aquaskyline** [comment]
We tried LRA v1.3.2 with the default settings, but no luck so far, the small variant calling performance seemed abnormal. Some option tuning might be helpful, but the conclusion so far is LRA's default settings cannot work with Clair3.
 
<img width="875" alt="来自 iOS 的图像" src="https://user-images.githubusercontent.com/895289/167352582-2f951311-5c3f-447c-b225-605f001366ed.png">

**Comment by waltergallegog** [comment]
Hi @aquaskyline. Thank you so much for the benchmark and for this precious feedback. I will use minimap2 when working with Clair3 to ensure the results are correct.

**Comment by tinyfallen** [comment]
Hi dear developer, I would like to know whether it would affect the performance using bowtie2 instead of bwa-mem for NGS reads, thanks a lot!
