### ISSUE TITLE
Running Clair3 as a non-root user when using docker

### ISSUE THREAD

**Issue by llk578496** [HKU-BAL/Clair3#104]
Hi, 
May I know could I run Clair3 as a non-root user when using docker (e.g. docker run --it --user 1000:1000 .........)? 
Thank you very much!

**Comment by aquaskyline** [comment]
It depends on your system settings, you can find more details at https://www.thegeekdiary.com/run-docker-as-a-non-root-user/.

Or you can try the Singularity installation.

**Comment by llk578496** [comment]
Thank you very much! I will try that out.
