### ISSUE TITLE
Quick question about Deep Learning and Varian Calling

### ISSUE THREAD

**Issue by daniusparres** [HKU-BAL/Clair3#106]
Hi, I love the method! But after using it for several weeks I have a doubt... what is the purpose or reason of using Deep Learning for Variant Calling? What do neural networks contribute to this task? Where can I get information about the reason of using Deep Learning in comparison with the classical perspective?

Best regards and thank you very much,

Daniel

**Comment by aquaskyline** [comment]
In [Clairvoyante's paper](https://www.nature.com/articles/s41467-019-09025-z) and [Clair's paper](https://www.nature.com/articles/s42256-020-0167-4), we discussed why deep learning performed better and what are the key points that make deep learning work for variant calling.
