### ISSUE TITLE
Error when there are no candidates for full-alignment calling 

### ISSUE THREAD

**Issue by charlesfoster** [HKU-BAL/Clair3#108]
Hi,

I've included `clair3` in a snakemake pipeline I maintain. Each of the snakemake rules are run on routine _and_ negative control samples. On a recent analysis run, the pipeline errored out because `clair3` failed with our negative control. Log excerpt:

```
[INFO] 6/7 Call low-quality variants using full-alignment model
cat: '/path/to/NEG/clair3/tmp/full_alignment_output/candidate_bed/FULL_ALN_FILE_*': No such file or directory
```
(path truncated for the purpose of this issue)

The previous part of the log reads:

```
[INFO] 5/7 Select candidates for full-alignment calling
[INFO] Set variants quality cutoff 7.0
[INFO] Set reference calls quality cutoff 4.0
[WARNING] Cannot find any low-quality 0/0, 0/1 or 1/1 variant in pileup output in contig MN908947.3
[INFO] Low quality reference calls to be processed in MN908947.3: 0
[INFO] Low quality variants to be processed in MN908947.3: 0
```

Seems that the lack of a 'FULL_ALN_FILE_*' file, e.g. `/path/to/NEG/clair3/tmp/full_alignment_output/candidate_bed/FULL_ALN_FILE_MN908947.3` file causes the `cat` command to fail, which then causes the pipeline to die because of bash 'strict mode'.

To remedy this, I have to first do `mkdir -p /path/to/NEG/clair3/tmp/full_alignment_output/candidate_bed && touch /path/to/NEG/clair3/tmp/full_alignment_output/candidate_bed/FULL_ALN_FILE_MN908947.3`. Afterwards, the script no longer fails, but having to have this pre-processing step isn't ideal. Could it instead be fixed in `run_clair3.sh`?

Command used:

```
singularity run -B $CONDA_PREFIX:$CONDA_PREFIX,$PWD:$PWD ${clair3_container_simg} /opt/bin/run_clair3.sh \
--bam_fn=${BAM} \
--sample_name=NEG \
--ref_fn=${REF} \
--threads=4 \
--platform="ont" \
--model_path="/opt/models/r941_prom_sup_g5014" \
--output=NEG/clair3    \
--chunk_size=29903 \
--include_all_ctgs \
--no_phasing_for_fa \
--enable_long_indel \
--haploid_sensitive | tee clair3.log.txt
```

Version: Clair3 v0.1-r11

Thanks!

**Comment by aquaskyline** [comment]
Thanks for the report. Looking into it and turn back soon.

**Comment by charlesfoster** [comment]
Thanks for the quick fix. I'll have to try it out when I'm back in the office next week, but I'm assuming it'll be fine now.
