### ISSUE TITLE
Using singularity

### ISSUE THREAD

**Issue by mzwaig** [HKU-BAL/Clair3#113]
Hi,

I'm trying to run Clair3 but I keep getting a large error message both when I use the demo data and my own and I can't figure out why. I think this might be the root of the error but I'm not sure. I have it installed in bioconda and I've attached the full log file.

tensorflow.python.framework.errors_impl.NotFoundError: /lb/project/ioannisr/Melissa-abacus/tools/conda/clair3/lib/python3.6/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringB5cxx11EPNS_15OpKernelContextEb

Thanks for you help,
Melissa

[run_clair3.log](https://github.com/HKU-BAL/Clair3/files/8846328/run_clair3.log)

**Comment by aquaskyline** [comment]
Seems your Tensorflow installation is broken, it might be because of some leftovers of older versions of TensorFlow, etc.

**Comment by mzwaig** [comment]
Thanks. I switch from conda to singularity because the newer version of TensorFlow wouldn't install. 

However, singularity can't seem to find the reference file despite printing the correct file path as it start running. I'm using the absolute path

Thanks,
Melissa 
```
singularity exec /lb/project/ioannisr/Melissa-abacus/tools/clair3_latest.sif /opt/bin/run_clair3.sh \
	--bam_fn=${PROJDIR}/${build}/alignment/${Sample}/${Sample}.sorted.bam \
	--ref_fn='/lb/project/ioannisr/Melissa-abacus/Reference_genomes/Homo_sapiens.GRCh38/Homo_sapiens.GRCh38.fa' \
	--threads=14 \
	--platform='ont' \
	--model_path='/opt/models/${MODEL_NAME}' \ 
	--output=${PROJDIR}/${build}/Clair3/${Sample}
```



[run_clair3.log](https://github.com/HKU-BAL/Clair3/files/8856080/run_clair3.log)

**Comment by aquaskyline** [comment]
You need to bind the non-system paths to make it visible in Singularity, please refer to https://sylabs.io/guides/3.7/user-guide/bind_paths_and_mounts.html

In the other parts of your command, you cannot use single quote around variables in shell, otherwise it won't be dereferenced.

**Comment by mzwaig** [comment]
I'm getting the same tensorflow issue when I use singularity (I double check that I wasn't running a separate conda instance). 

What version are you using? I've tried both 2.2.0 and 2.8

**Comment by aquaskyline** [comment]
You will need some debugging technics to find out the libraries that TensorFlow is calling on your computer to find out what's wrong. You might also want to try on another system setup.
