### ISSUE TITLE
Clair3 quality filtering threshold

### ISSUE THREAD

**Issue by Teklu67** [HKU-BAL/Clair3#116]
Hello,
I read that the quality scores of variants derived from ONT data are usually bimodally distributed. What is the best quality threshold for filtering Clair3 vcf output? In Clair2, I was using a shell script kindly provided by Fritz and Medhat but it is no more working for Clair3 outputs. Any suggestion please? 
Many thanks for your time and help!

**Comment by aquaskyline** [comment]
Clair3's variant quality score was redesigned. You only need to filter out those with quality lower than 2.

**Comment by Teklu67** [comment]
ok, thanks a lot!
