### ISSUE TITLE
CRAM support

### ISSUE THREAD

**Issue by santoshe1** [HKU-BAL/Clair3#117]
Hello,

Thank you for the tool Clair3. I would like to know if Clair3 supports CRAM as input instead of BAM?

Best,
S

**Comment by santoshe1** [comment]
Thank you, Could you let us know the tentative date for next update @aquaskyline ?

**Comment by aquaskyline** [comment]
Probably in September. So if in a hurry, could you please try converting CRAM to BAM before feeding it to Clair3. Sorry that we cannot help more.

**Comment by aquaskyline** [comment]
Supported CRAM input in v0.1-r12.
