### ISSUE TITLE
Will there be a release after v0.1-r11 given ticket #92

### ISSUE THREAD

**Issue by SHuang-Broad** [HKU-BAL/Clair3#118]
Hi, 

I'm considering bumping up the version of Clair3 in our pipeline after #99.
However, after seeing ticket #92, I'm hesitant as it points to a major drop of performance.
Judged from the discussion in #92, there's a patch that fixed the issue.
The release date for v0.1-r11 is April 4th, and #92 happened after that.

So I'm wondering if there will be v0.1-r11.2 or v0.1-r12 soon.
(I noticed the tag v0.1-r11.1 is for Zenodo specifically).

Thanks,
Steve

**Comment by SHuang-Broad** [comment]
Additional context: we built our own docker but are happy to use the official docker.
But looking at the docker build time, tag v0.1-r11 is built way after the April 4th, so I'm wondering if Clair3 in the docker with tag [v0.1-r11](https://hub.docker.com/layers/clair3/hkubal/clair3/v0.1-r11/images/sha256-52b97e3e45c2c486a1022de2ce7bceb8e8c9b40bce9a63bec2758d283aa7b1a2?context=explore) is the same as the version github [gives](https://github.com/HKU-BAL/Clair3/releases/tag/v0.1-r11) (April 4th).

**Comment by aquaskyline** [comment]
#92 was addressed in all the latest installation options. The r11 version you got is with "minor 2" as mentioned in https://github.com/HKU-BAL/Clair3#latest-updates

**Comment by SHuang-Broad** [comment]
I'm a little confused.

The v0.1-r11 tag in Github's "tags" [link](https://github.com/HKU-BAL/Clair3/releases/tag/v0.1-r11) is still pointing to r11 released on April 4th. There isn't a "v0.1-r11 minor 2" tag.

The docker version looks to be built with the patch included though.

**Comment by aquaskyline** [comment]
We added to the link **v0.1-r11 minor 2 patches are included in all installation options**.
