### ISSUE TITLE
Clair3 model for unknown basecall version

### ISSUE THREAD

**Issue by tuannguyen8390** [HKU-BAL/Clair3#120]
Hi team, 

I was wondering if I download some public dataset without knowing what basecall version/mode was performed with the dataset (for example, 9.4.1 vs 10.4, HAC vs SUP), what should I use as model for Clair3 ? Is there a "general" model used for all ONT flowcell ?

Thanks,

Tuan

**Comment by aquaskyline** [comment]
Great question. I don't think Clair3 would have a general model due to the ample differences in performance between chemistries and basecallers. But it is possible to make a guess according to the alignment statistics.

**Comment by tuannguyen8390** [comment]
Thanks for the suggestion, very interesting approach (& probably nice to thoroughly examine) !

**Comment by raonycardenas** [comment]
Hi there, is there a way to find out which basecalling model I should use from a BAM file without the model information?
Is there a way to reverse engineer the basecall model?
