### ISSUE TITLE
Empty VCF output for demo and samples

### ISSUE THREAD

**Issue by mproberts99** [HKU-BAL/Clair3#122]
Hi,
I am using Clair3 and keep getting empty VCF files as output for my own samples and the demo files. I tested both the pre-built docker image and built it myself by cloning this repo and running clair3_ont_quick_demo.sh. It appears to exit after step 1/7 pileup variant calling, outputting no vcf file for pileup_output so it creates an empty vcf file for the pileup and merged VCFs. The process takes about 6 minutes before it exits. I have used my file with another caller with no issue so I'm suspecting something is going wrong when building the image. Anyone else having this issue or have any advice to figure out what is going wrong?

This is the error for the demo. No error message is outputted when running it with my own files:

+ /opt/bin/scripts/clair3_c_impl.sh --bam_fn /home/monica.roberts/clair3_ont_quickDemo/HG003_chr20_demo.bam --ref_fn /home/monica.roberts/clair3_ont_quickDemo/GRCh38_no_alt_chr20.fa --threads 4 --model_path /opt/models/ont --platform ont --output /home/monica.roberts/clair3_ont_quickDemo/output --bed_fn=/home/monica.roberts/clair3_ont_quickDemo/quick_demo.bed --vcf_fn=EMPTY --ctg_name=EMPTY --sample_name=SAMPLE --chunk_num=0 --chunk_size=5000000 --samtools=samtools --python=python3 --pypy=pypy3 --parallel=parallel --whatshap=whatshap --qual=2 --var_pct_full=0.7 --ref_pct_full=0.1 --var_pct_phasing=0.7 --snp_min_af=0.08 --indel_min_af=0.15 --min_mq=5 --min_coverage=2 --min_contig_size=0 --pileup_only=False --gvcf=False --fast_mode=False --call_snp_only=False --print_ref_calls=False --haploid_precise=False --haploid_sensitive=False --include_all_ctgs=False --no_phasing_for_fa=False --pileup_model_prefix=pileup --fa_model_prefix=full_alignment --remove_intermediate_dir=False --enable_phasing=False --enable_long_indel=False --use_gpu=False --longphase_for_phasing=False --longphase=EMPTY

[INFO] Check environment variables
[INFO] --include_all_ctgs not enabled, use chr{1..22,X,Y} and {1..22,X,Y} by default
[INFO] Call variant in contigs: chr20
[INFO] Chunk number for each contig: 13
Traceback (most recent call last):
  File "/opt/bin/scripts/../clair3.py", line 94, in <module>
    main()
  File "/opt/bin/scripts/../clair3.py", line 88, in main
    submodule.main()
  File "/opt/bin/preprocess/CheckEnvs.py", line 492, in main
    CheckEnvs(args)
  File "/opt/bin/preprocess/CheckEnvs.py", line 396, in CheckEnvs
    split_extend_bed(bed_fn=bed_fn, output_fn=split_bed_path, contig_set=contig_set)
  File "/opt/bin/preprocess/CheckEnvs.py", line 161, in split_extend_bed
    with open(ctg_output_fn, 'w') as output_file:
PermissionError: [Errno 13] Permission denied: '/home/monica.roberts/clair3_ont_quickDemo/output/tmp/split_beds/chr20'

Thanks in advance!

**Comment by zhengzhenxian** [comment]
Hi,

Seem you have no permission to write files in your output folder `/home/monica.roberts/clair3_ont_quickDemo/output`, you might need to use an authorized output folder. 

And pls follow the [general usage](https://github.com/HKU-BAL/Clair3#general-usage) if you wish to run Clair3 in your own data, the demo data is just a quick check for the workflow, thanks!

**Comment by mproberts99** [comment]
I fixed it by adding '-u $(id -u ${USER}):$(id -g ${USER})' to the demo file as well as my own docker run command. 

Thanks so much!
