### ISSUE TITLE
Clair3 with Guppy 6

### ISSUE THREAD

**Issue by felixm3** [HKU-BAL/Clair3#124]
Hello,

I have data that is base called with Guppy 6.

```
ONT Guppy basecalling software version 6.1.3+cc1d765, minimap2 version 2.22-r1101
config file:    	/opt/ont/ont-guppy/data/dna_r9.4.1_450bps_sup.cfg
model file:     	/opt/ont/ont-guppy/data/template_r9.4.1_450bps_sup.jsn

```
Can I use Clair3 to do variant calling on it?

If yes, what should I select for the:

`--model_path=`

please?

**Comment by zhengzhenxian** [comment]
Hi,
Yes, pls use `--model_path=${YOUR_MODEL_PATH}/r941_prom_sup_g5014` for r9.4.1 Guppy6 data.

**Comment by felixm3** [comment]
Thank you for the quick response.

Can you help me understand please why it's okay to use the Guppy 5 model from the Promethion sequencer on my Guppy 6 data from MinION sequencers?

My understanding was that the Guppy 6 models are quite different from the Guppy 5 models no?

Best regards.

**Comment by aquaskyline** [comment]
Clair3 Guppy5 model applies to Guppy6 data, more details are at https://github.com/HKU-BAL/Clair3/blob/main/docs/guppy5_20220113.md.

**Comment by felixm3** [comment]
Thank you for the reference.

Other than the first line, it doesn't mention Guppy6 anywhere though.

Could you please help me understand the justification for using the Guppy5 model for Guppy6 data?

Your reference only talks about using Guppy5 data for training, no Guppy6 data.

Best regards.

**Comment by aquaskyline** [comment]
On simplex reads, in terms of error profile, Guppy6 is not systematically different from Guppy5. The benchmarking performance you see on using Guppy5 model on Guppy5 data is what you will get on using Guppy5 model on Guppy6 data.

Guppy 5 and 6 are significantly different from Guppy 3 and 4 in terms of error profile.

**Comment by felixm3** [comment]
I see.

Thank you!
