### ISSUE TITLE
Check environment variables:pysam,whatshap

### ISSUE THREAD

**Issue by oranges7** [HKU-BAL/Clair3#125]
The command I use is as follows：
run_clair3.sh \
--ref_fn=/home/gyc/ont/seq/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
--bam_fn=/home/gyc/ont/fast5/workspace/output/out166/std/out.bam \
--threads=8 \
--platform="ont" \
--model_path="/home/gyc/anaconda3/envs/clair3ys/bin/models/r941_prom_hac_g360+g422" \
--output=/home/gyc/ont/fast5/workspace/output/out166/std/out

but I have some problems：

[INFO] CLAIR3 VERSION: v0.1-r11
[INFO] BAM FILE PATH: /home/gyc/ont/fast5/workspace/output/out166/std/out.bam
[INFO] REFERENCE FILE PATH: /home/gyc/ont/seq/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
[INFO] MODEL PATH: /home/gyc/anaconda3/envs/clair3ys/bin/models/r941_prom_hac_g360+g422
[INFO] OUTPUT FOLDER: /home/gyc/ont/fast5/workspace/output/out166/std/out
[INFO] PLATFORM: ont
[INFO] THREADS: 8
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: /home/gyc/anaconda3/envs/clair3ys
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] LONGPHASE PATH: EMPTY
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] PHASING PROPORTION: 0.7
[INFO] MINIMUM MQ: 5
[INFO] MINIMUM COVERAGE: 2
[INFO] SNP AF THRESHOLD: 0.08
[INFO] INDEL AF THRESHOLD: 0.15
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: False
[INFO] ENABLE REMOVING INTERMEDIATE FILES: False
[INFO] ENABLE PHASING VCF OUTPUT: False
[INFO] ENABLE LONG INDEL CALLING: False
[INFO] ENABLE LONGPHASE_FOR_PHASING: False
[INFO] ENABLE C_IMPLEMENT: True

+ /home/gyc/anaconda3/envs/clair3ys/bin/scripts/clair3_c_impl.sh --bam_fn /home/gyc/ont/fast5/workspace/output/out166/std/out.bam --ref_fn /home/gyc/ont/seq/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna --threads 8 --model_path /home/gyc/anaconda3/envs/clair3ys/bin/models/r941_prom_hac_g360+g422 --platform ont --output /home/gyc/ont/fast5/workspace/output/out166/std/out --bed_fn=EMPTY --vcf_fn=EMPTY --ctg_name=EMPTY --sample_name=SAMPLE --chunk_num=0 --chunk_size=5000000 --samtools=samtools --python=python3 --pypy=pypy3 --parallel=parallel --whatshap=whatshap --qual=2 --var_pct_full=0.7 --ref_pct_full=0.1 --var_pct_phasing=0.7 --snp_min_af=0.08 --indel_min_af=0.15 --min_mq=5 --min_coverage=2 --min_contig_size=0 --pileup_only=False --gvcf=False --fast_mode=False --call_snp_only=False --print_ref_calls=False --haploid_precise=False --haploid_sensitive=False --include_all_ctgs=False --no_phasing_for_fa=False --pileup_model_prefix=pileup --fa_model_prefix=full_alignment --remove_intermediate_dir=False --enable_phasing=False --enable_long_indel=False --use_gpu=False --longphase_for_phasing=False --longphase=EMPTY

[INFO] Check environment variables
**Traceback (most recent call last):
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/pkgutil.py", line 412, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: ('/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages', 'pysam')**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gyc/anaconda3/envs/clair3ys/bin/whatshap", line 7, in <module>
    from whatshap.__main__ import main
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/whatshap/__main__.py", line 6, in <module>
    import whatshap.cli as cli_package
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/whatshap/cli/__init__.py", line 12, in <module>
    from whatshap.utils import IndexedFasta, FastaNotIndexedError, detect_file_format
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/whatshap/utils.py", line 2, in <module>
    import pyfaidx
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/pyfaidx/__init__.py", line 21, in <module>
    from pkg_resources import get_distribution
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/pkg_resources/__init__.py", line 559, in _build_master
    ws = cls()
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/pkg_resources/__init__.py", line 552, in __init__
    self.add_entry(entry)
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/pkg_resources/__init__.py", line 608, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1964, in find_distributions
    importer = get_importer(path_item)
  File "/home/gyc/anaconda3/envs/clair3ys/lib/python3.6/pkgutil.py", line 416, in get_importer
    importer = path_hook(path_item)
**TypeError: expected str, bytes or os.PathLike object, not tuple
[INFO] --include_all_ctgs not enabled, use chr{1..22,X,Y} and {1..22,X,Y} by default
[ERROR] whatshap not found, please check you are in clair3 virtual environment**
[ERROR] Current python execution path: /home/gyc/anaconda3/envs/clair3ys/bin/python
**How can I fix them? thanks**

**Comment by oranges7** [comment]
This is the environment I created today, the environment created before can run

**Comment by aquaskyline** [comment]
You message says "whatshap not found".

**Comment by oranges7** [comment]
> 

but pip list as follows：
(clair3ys) [gyc@localhost script]$ pip list
Package                Version
---------------------- ---------
absl-py                1.1.0
astor                  0.8.1
astunparse             1.6.3
biopython              1.79
blinker                1.4
brotlipy               0.7.0
cachetools             2.1.0
certifi                2021.5.30
cffi                   1.14.4
charset-normalizer     2.1.0
click                  8.0.1
cryptography           35.0.0
cycler                 0.11.0
dataclasses            0.8
gast                   0.3.3
google-auth            1.2.1
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.38.1
h5py                   2.10.0
idna                   3.3
importlib-metadata     4.8.1
isal                   0.11.1
Keras-Preprocessing    1.1.2
kiwisolver             1.3.1
Markdown               3.4.1
matplotlib             3.3.4
mock                   4.0.3
networkx               2.7.1
numexpr                2.7.3
numpy                  1.19.5
oauthlib               3.2.0
olefile                0.46
opt-einsum             3.3.0
packaging              21.3
pandas                 1.1.5
Pillow                 8.1.0
pip                    21.3.1
protobuf               3.18.0
pyasn1                 0.4.8
pyasn1-modules         0.0.5
pycparser              2.21
pyfaidx                0.7.0
PyJWT                  2.4.0
pyOpenSSL              22.0.0
pyparsing              3.0.9
pysam                  0.16.0.1
PySocks                1.7.1
python-dateutil        2.8.2
pytz                   2022.1
PyVCF3                 1.0.3
requests               2.28.1
requests-oauthlib      1.3.1
rsa                    3.1.4
scipy                  1.5.3
setuptools             58.0.4
six                    1.16.0
tables                 3.6.1
tensorboard            2.3.0
tensorboard-plugin-wit 1.8.1
tensorflow             2.2.0
tensorflow-estimator   2.6.0
termcolor              1.1.0
tornado                6.1
typing_extensions      4.1.1
urllib3                1.26.10
Werkzeug               2.0.2
**whatshap               1.0**
wheel                  0.37.1
wrapt                  1.13.1
xopen                  1.2.0
zipp                   3.6.0

**Comment by aquaskyline** [comment]
Please try running whatshap without a path in your environment. Or you can pass the absolute path of whatshap to Clair3.

**Comment by oranges7** [comment]
ok，Thank you for your quick reply, I will try

**Comment by oranges7** [comment]
> Please try running whatshap without a path in your environment. Or you can pass the absolute path of whatshap to Clair3.

I re-installed the environment and it works now, thank you for your reply
