### ISSUE TITLE
Clair3 on HPC SLURM - Multiple nodes possible?

### ISSUE THREAD

**Issue by felixm3** [HKU-BAL/Clair3#126]
Hello,

I'm trying to run Clair3 on an HPC. I've requested 8 nodes with 28 CPUs each for a total of 224 CPUs.

```
#!/bin/bash
#
#SBATCH --job-name=run_clair3sh_220724
#
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=28
```

However, when I run Clair3, it seems to only see one of the 8 nodes and therefore runs on only 28 CPUs.

`[33m[WARNING] Threads setting exceeds maximum available threads 28, set threads=28`

Is Clair3 capable of running on CPUs spread out over multiple nodes?

Thanks in advance.

**Comment by aquaskyline** [comment]
Natively Clair3 doesn't support multiple node execution. You might want to refer to the solution using nextflow at https://github.com/epi2me-labs/wf-human-snp from ONT.

**Comment by felixm3** [comment]
Got it.

Thanks!
