### ISSUE TITLE
A loop to run clair3 on multiple .bam files 

### ISSUE THREAD

**Issue by amechakra** [HKU-BAL/Clair3#127]
Hi
I am trying to run clair3 (conda) with a for loop to analyze bam files from different samples. 

The code looks like:

conda create -n clair3 -c bioconda clair3 python=3.6.10 -y
conda activate clair3

for i in {path do di/*.bam}
do
 run_clair3.sh \
--bam_fn=$i \ 
--ref_fn={path to the reference genome .fasta} \
--threads=8 \
--platform=ont \
--model_path={path to r941_prom_hac_g360+g422} \
--output= {path to output dir} \
--sample_name=x\
--min_coverage=25 \
--ctg_name=chr19
done

when I run this, I have the following error 
![Picture1](https://user-images.githubusercontent.com/93645991/182315584-63b2be7b-7591-4047-9c76-7b466ab4ebbb.png)

Can you help me to fix the problem?

**Comment by aquaskyline** [comment]
add more '\'

**Comment by amechakra** [comment]
Sorry, when I changed the code to delete personal info and paths, I deleted the backslash(s). 

Here is the actual code and I have the exact same error(s)

for i in {path do di/*.bam}
do
run_clair3.sh
--bam_fn=$i \
--ref_fn={path to the reference genome .fasta} \
--threads=8 \
--platform=ont \
--model_path={path to r941_prom_hac_g360+g422} \
--output= {path to output dir} \
--sample_name=x \
--min_coverage=25 \
--ctg_name=chr19
done

**Comment by amechakra** [comment]
![Picture2](https://user-images.githubusercontent.com/93645991/182320883-6281bd55-ee75-401c-8437-c28cf9373432.png)

**Comment by aquaskyline** [comment]
add '\' after run_clair3.sh

**Comment by amechakra** [comment]
thank you for your fast answers.
It is easier to post the real code... I will delete afterwards. 
It is not working with this

![Picture3](https://user-images.githubusercontent.com/93645991/182323099-d9622894-15f2-48d0-bf43-a19cb149f81c.png)

**Comment by aquaskyline** [comment]
If you are familiar with bash, in your error message, it shows "--ref_fn=..." was treated as a new row, i.e., there must be some problems between '--ref_fn' and the previous row. Sometime it could be editor's problem, sometime it's autocorrection, but you can simply type the command again verbatim, and preferably remove the '\\' and merge all options into one row to get it working first. Since this is a bash syntax problem, please do trial and error to get it work.

**Comment by amechakra** [comment]
Thanks a lot
