### ISSUE TITLE
Typo in example code of guppy5.md documents

### ISSUE THREAD

**Issue by cdebuck** [HKU-BAL/Clair3#129]
Hi,

There is a small typo in the docker code sections of:
https://github.com/HKU-BAL/Clair3/blob/main/docs/guppy5_20220113.md#how-to-use-the-guppy5-model
https://github.com/HKU-BAL/Clair3/blob/main/docs/guppy5.md

`hkubal/clair3::latest` should not have a double semi-colon and should be: `hkubal/clair3:latest`

Thanks for developing this tool.

**Comment by aquaskyline** [comment]
Thanks and fixed.
