### ISSUE TITLE
Question about default settings

### ISSUE THREAD

**Issue by cdebuck** [HKU-BAL/Clair3#130]
Hello,
I've used clair3 with the default options like this:

```
INPUT_DIR="/home/user/test_in"
OUTPUT_DIR="/home/cdebuck/Data/variant_calling/test_clair3"
BAM="test.bam"
THREADS="28"
REF="ref.fasta"

docker run -it \
  -v "${INPUT_DIR}":"${INPUT_DIR}" \
  -v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
  hkubal/clair3:latest \
  /opt/bin/run_clair3.sh \
  --bam_fn="${INPUT_DIR}/${BAM}" \
  --ref_fn="${INPUT_DIR}/${REF}" \
  --threads=${THREADS} \
  --platform="ont" \
  --include_all_ctgs \
  --model_path="/opt/models/r941_prom_sup_g5014" \
  --output="${OUTPUT_DIR}"
```

Based on the documentation, I was expecting that clair3 would not perform a phasing step, but in the logs I see that it has used WhatsHap phasing, but the --help states:

```
      --enable_phasing          Output phased variants using whatshap, default: disable.
      --longphase_for_phasing   Use longphase for phasing, default: enable
```

What is the function of the --enable_phasing parameter, since clair3 has used WhatsHap without supplying this parameter?
Is the mentioned default for the --longphase_for_phasing correct, since longphase was not used?

**Comment by aquaskyline** [comment]
`--enable_phasing` should be renamed as `--output_phased_bam`

**Comment by cdebuck** [comment]
Thank you. I actually have multiple .bam files that belong to the same sample.
So if I understand it correctly I can do the following:
Use clair3 (default settings, so with WhatsHap phasing on) for each of the .bam files separately to obtain a .vcf file for each of the .bam files.
And then use WhatsHap phase afterwards combining all of the .bam and .vcf files that belong to this sample.

Or it is not recommended to run WhatsHap again after using clair3?

**Comment by aquaskyline** [comment]
Updated my previous. If you have multiple bam files that belong to the same sample, would it be more useful to merge the bam files together and use the merged bam as Clair3's input?

**Comment by cdebuck** [comment]
That would be possible indeed. In that case: if I supply --enable_phasing, this would mean that I'm performing variant calling and phasing in one go right? Is the output described as `phased reads in bam` equivalent to running whatshap haplotag?

**Comment by aquaskyline** [comment]
Yes and yes.

**Comment by cdebuck** [comment]
I have now used clair3 with the option `--enable_phasing`, but it has not resulted in any phased.bam files in the output.
In the output directory only the following file was added: phased_merge_output.vcf.gz.
I checked the phase_output folder in the temp folder, but the phase_bam folder there is empty.

**Comment by zhengzhenxian** [comment]
Hi,

It is expected. We only phased the final VCF. We would suggest you to use the phased output(phased_merge_output.vcf.gz) and [WhatsHap haplotag](https://whatshap.readthedocs.io/en/latest/guide.html#whatshap-haplotag-tagging-reads-by-haplotype-for-visualization) submodule to get a phased BAM.

**Comment by aquaskyline** [comment]
@cdebuck in the latest code the `phased.bam` wasn't outputted since it takes another hour to run but not all users needed it. With `phased_merge_output.vcf.gz`, could you please do one more step [WhatsHap haplotag](https://whatshap.readthedocs.io/en/latest/guide.html#whatshap-haplotag-tagging-reads-by-haplotype-for-visualization) to generate `phased.bam` after finish running Clair3.

**Comment by cdebuck** [comment]
No problem thank you, I just expected the phased.bam output based on the previous comment in this issue, so I wanted to check to be sure.

**Comment by aquaskyline** [comment]
Amended my previous reply.

**Comment by chilampoon** [comment]
Hi there, I was wondering if `longphase_for_phasing` means using long phase after variant calling to get those phased vcfs, but during calling the program still uses whatshap?

**Comment by zhengzhenxian** [comment]
Hi, `--longphase_for_phasing` option means replace whatshap with longphase to phase intermediate pileup VCF in the calling process. We still use whatshap to get phased VCF if the `enable_phasing` option is enabled.

**Comment by chilampoon** [comment]
> Hi, `--longphase_for_phasing` option means replace whatshap with longphase to phase intermediate pileup VCF in the calling process. We still use whatshap to get phased VCF if the `enable_phasing` option is enabled.

Thanks! I specified `--longphase_for_phasing` but didn't set `enable_phasing` to true... I found phased vcfs in the intermediate file directory, can I get the final phased vcf from these intermediated phased vcfs?

**Comment by zhengzhenxian** [comment]
afraid not, those VCFs only contained pileup heterozygous variants.
We would suggest you use the final output(merge_output.vcf.gz) and WhatsHap [phase](https://whatshap.readthedocs.io/en/latest/guide.html#user-guide) submodule or LongPhase [phase](https://github.com/twolinin/LongPhase/#snp-only-phasing) to get a more reliable phased VCF.
