### ISSUE TITLE
Allele frequency (AF) of InDel alleles appears incorrect in Clair3 v0.1-r11

### ISSUE THREAD

**Issue by Sandman2127** [HKU-BAL/Clair3#131]
Hi all,
I just have some questions about the output of Clair3. Specifically, in the merge_output.vcf I'm getting an odd allele frequency output in my Indel calls.

See the IGV screenshot below:

<img width="1903" alt="Wrong_Del_AF" src="https://user-images.githubusercontent.com/29004963/184407725-21c98ea5-a223-44e2-ad21-e9e9edbea5a5.png">
To me the above looks like 4/11 reads are ALT allele freq = 0.3636

''

Additionally, I have seen a few other InDel type variants that seem like they should be called based on depth parameters, yet are not, any ideas? 
<img width="1893" alt="Del_not_called" src="https://user-images.githubusercontent.com/29004963/184407728-77b85f2f-1188-45b3-82cb-33e0a3875807.png">

again this seems like it would be 4/12 == 0.33, which is well above the call parameter defaults for clair3, i.e.: 
```
      --indel_min_af=FLOAT      Minimum Indel AF required for a candidate variant. Lowering the value might increase a bit of sensitivity in trade of speed and accuracy, default: ont:0.15,hifi:0.08,ilmn:0.08.
```

#### filter for >5kb reads and remove adapters with filtlong & porechop
```
$PORECHOP --threads 16 --format auto --discard_middle -i $InputFile -o output.porechopped.fastq
$filtlong --min_length $minLength --mean_q_weight 10 output.porechopped.fastq | gzip > filtered.fq.gz
```
#### minimap 2.17
```
$minimap2 -t $HalfofThreads -L --MD -c -ax map-ont $Genome $InputFile > ${InputFile%.fq.gz}.sam
```

#### Clair3 v0.1-r11
```
MODELDIR="/opt/miniconda/envs/clair3/bin/models"
MODEL="ont"
$CLAIR3 --bam_fn=$InputBam --ref_fn=$Genome --platform="ont" --threads=$HalfofThreads --model_path="$MODELDIR/$MODEL" --output=$OUTPUT
```

**Comment by aquaskyline** [comment]
In your first case, it is not just a "4bp deletion" (GT 0/1), it's a "4bp del + A>G" (GT 1/2). There are 5 reads supporting A>G, and 4 reads supporting 4bp del. Thus (4+5)/11~=0.8182.

The second case doesn't look like an authentic deletion, all four 2bp deletion signals are with an adjacent T>C, while reads without the deletion single are also without an adjacent T>C. It looks like a typical false deletion signal.

**Comment by Sandman2127** [comment]
Thanks aquaskyline,
#1 is just a misinterpretation on my part, since they're both at the same locus the Alt Allele freq is definitely a combination of the two. Totally makes sense, my apologies. 

As for #2, I don't fully understand, couldn't that just be the haplotype structure at that locus, i.e. you have a 2bp deletion and a SNP for a T>C in one allele (4/12) and the other allele doesn't contain the T>C in almost all cases (7/12). Perhaps this is just a normal error type in ONT data? 

Thanks again for your time, really appreciate the explanations and I'm happy to close this whenever works for you.

**Comment by aquaskyline** [comment]
For #2, perhaps and perhaps not. Clair3's neural network decided it's not a real variant despite the relatively obvious-to-eye signal. The odd is given in the QUAL. It is not saying that Clair3's decision is always correct, and it is possible that it's just the true haplotype structure at the locus, but Clair3 was designed to spot non-obvious spurious signals and got massively verified benchmarking against the standard reference samples.

**Comment by Sandman2127** [comment]
Thanks aquaskyline, that is definitely possible. If I come across more data for this sample, perhaps decent depth CCS, I'll check into it. That being said, as you mention, Clair3's performance with benchmarks appears quite impressive! Looking forward to your future work!
