### ISSUE TITLE
Intuition doc for beginner

### ISSUE THREAD

**Issue by PaParaZz1** [HKU-BAL/Clair3#132]
Can you provide some intuition documations for your repo, it is confused to know about what you do for a beginner.

For example, as the viewpoint of machine learning algorithm developer, I want to know the following things:
- What is the brief description of your task, like the input/output of neural network and evalutaion metric?
- What is the advantage of using deep learning in your task than some traditional method?
- What is the difference between different datasets or tasks?

**Comment by aquaskyline** [comment]
You might want to start with Clair3's paper at [bioRxiv](https://www.biorxiv.org/content/10.1101/2021.12.29.474431v1). More details re your three points are also available at [Nature Machine Intelligence](https://www.nature.com/articles/s42256-020-0167-4) and [Nature Communications](https://www.nature.com/articles/s41467-019-09025-z).
