### ISSUE TITLE
conda package installation failure

### ISSUE THREAD

**Issue by ftostevin-ont** [HKU-BAL/Clair3#134]
The conda package appears to depend on a version `pigz==2.4` that can no longer be installed. Conda-forge [has version 2.6](https://anaconda.org/conda-forge/pigz/files).
```
% mamba create -n clair3 -c conda-forge -c bioconda -c defaults clair3=0.1.12
...
Looking for: ['clair3=0.1.12']
...
Encountered problems while solving:
  - package clair3-0.1.12-py39hb9dc472_0 requires pigz 2.4.*, but none of the providers can be installed
```

**Comment by aquaskyline** [comment]
Removed version pinning on pigz from conda receipt, please try again.

**Comment by ftostevin-ont** [comment]
Installation now works. Thanks!

One further question - is there a reason for specifically requiring `tensorflow-cpu`? We would like to have flexibility to possibly use a gpu for testing and particularly for model training. Could this be relaxed to just `tensorflow`?

**Comment by aquaskyline** [comment]
Both `tensorflow` and `tensorflow-cpu` work. After installation, one can just pip remove `tensorflow-cpu` and then install `tensorflow`. In r12, we bumped up tensorflow version from 2.2 and 2.8. In our testing with using `tensorflow=2.8.0`, conda required and downloaded over a gigabyte of CUDA library packages. It made the traffic a bit too large and the installation time too long. So far we haven't got a solution to force conda installing `tensorflow=2.8.0` without the cuda libraries. In fact we are not sure about changing from `tensorflow` to `tensorflow-cpu`. Any thoughts?

**Comment by aquaskyline** [comment]
Further discussed with Zhenxian. Here is our plan, 1) we will update conda to install `tensorflow` so as to support both CPU and GPU by default; 2) we will add a conda package `clair3-cpuonly` that installs `tensorflow-cpu`.

**Comment by ftostevin-ont** [comment]
> In our testing with using `tensorflow=2.8.0`, conda required and downloaded over a gigabyte of CUDA library packages, which has not happened in `tensorflow=2.2.0`. It made the traffic a bit too heavy and the installation time too long. So far we haven't got a solution to force conda installing `tensorflow=2.8.0` without the cuda libraries. In fact we are not sure about the change from `tensorflow` to `tensorflow-cpu`. Any thoughts?

Interesting, I hadn't realised that this was changed. I guess this means that the default `tensorflow` is now a gpu-enabled version? I can certainly understand that this extra overhead would not be desirable for general users.

> After installation, one can just pip uninstall `tensorflow` and then install `tensorflow` (the gpu version by default) again. 

Using pip with packages that conda is trying to manage and vice versa is generally a bad idea and can leave the environment in a broken state, so I'm not keen on this option.

> Further discussed with Zhenxian. Here is our plan, 1) we will update conda to install tensorflow so as to support both CPU and GPU by default; 2) we will add a conda package clair3-cpuonly that installs tensorflow-cpu.

Since the default pipeline uses cpu only and gpu access is only really useful for training, which is relevant to only a small number of users, if you end up going for multiple packages it might make more sense to leave the main `clair3` package as is (cpu-only) and make the secondary package `clair3-gpu`. But of course multiple packages adds a maintenance burden for you, so in the end I don't think there's a perfect solution here.

**Comment by aquaskyline** [comment]
Check here https://conda-forge.org/blog/posts/2021-11-03-tensorflow-gpu/ for the changed behavior of installing tensorflow via conda.

We've updated Clair3's conda installation to installing `tensorflow` to keep the default behavior expected from the previous versions. In the next version, we will revise the issue and decide again.

**Comment by ftostevin-ont** [comment]
Thanks for the quick responses
