### ISSUE TITLE
No variant calling close to the edge of reads?

### ISSUE THREAD

**Issue by SebastianMeyer1989** [HKU-BAL/Clair3#135]
Hello,

I am using clair3 for variant calling on Nanopore data (running with default parameters, excpt for --include_all_ctgs).
I observed, that clair3 seems to not call possible variants within up to ~10-15 bases on the beginning/end of reads.
I am sorry, if I overlooked something obvious, but is this generally done for all reads (because the quality normally gets worse towards the beginning/end of the reads)?
Or are these actually quality-filtered and this only happens in reads with bad quality?

In either case, is it possible to turn this „filtering“ off (I did not find a parameter for that)?

As an example I attached an IGV Screenshot of such a case.
Here you see three tracks of .vcf files (Barcode 11, 18 and 19) and three tracks of the corresponding .bam files (also barcode 11, 18 and 19)
In the .bam file of barcode 18 there is an obvious variant at position 11 (C>G) with 95% Gs, which is not called in the .vcf file. Coverage and quality should be sufficient for a calling and I saw identical cases in my data in different positions all somewhere within ~15 bases of the beginning or end of reads.

![IGV_clair3_not_calling_near_the_edge_v1](https://user-images.githubusercontent.com/47881936/188111779-19051bec-d7ea-4dc8-857f-7e7f8bda6bb9.PNG)

**Comment by aquaskyline** [comment]
We need more details to conclude. Would it be possible for you to provide us a bam of this case?

**Comment by aquaskyline** [comment]
It could be filters or just a decision of the calling network. Could you generate a small bam with a subset of reads aligned only to the position of interest. `samtools view filename.bam  EFAU004_0264:1-81` should do the job. We are interested in having a look at the reads to find out if it is a false negative by Clair3.

**Comment by SebastianMeyer1989** [comment]
Thanks. That works and the output is now small enough.


[VRE_BC_18-new_FLAGs_EFAU004_00264_1-81.txt](https://github.com/HKU-BAL/Clair3/files/9488575/VRE_BC_18-new_FLAGs_EFAU004_00264_1-81.txt)


If this is not significant enough, I can provide a few more cases.

Thanks again for looking into this.

**Comment by aquaskyline** [comment]
It took us a while to do some experiments. The conclusion is that Clair3's framework cannot call variants in the head or tail 16bp of a sequence as reliable as those not in the head or tail 16bp of a sequence. We did experiments on four randomly chosen variants and padded either side of the input with zero at variable lengths to simulate the forcing Clair3 to call variants in the head or tail 16bp of a sequence. The results are shown in the figure below. Significant variant quality score decay or failure was observed in all four cases. Having said that, it is not impossible for Clair3 to also identify possible variant signals in the head or tail 16bp of a sequence, but it'd be unreliable, especially with the observation that both ends of a sequence are usually with depth coverage lower than average (with an exception in amplicon sequencing). At the moment, I tend not to provide an option to force calling variants from the head or tail 16bp of a sequence. But a hack to this is simply adding 16bp of 'N' to the head and tail of a sequence (before sequence alignment) to push the whole sequence into the scope of Clair3.

<img width="662" alt="Screen Shot 2022-09-14 at 12 41 47" src="https://user-images.githubusercontent.com/895289/190061285-73277367-8d97-4a6a-b5c5-1b93ef98f556.png">

**Comment by SebastianMeyer1989** [comment]
Thank you for your extensive analysis of the problem. This helps a lot!
And also thanks for the suggestions how to bypass this.
I will have to look into my data now and think about, how I want to solve this. :)
