### ISSUE TITLE
Which model to use for r9.4.1 fast calls?

### ISSUE THREAD

**Issue by sagnikbanerjee15** [HKU-BAL/Clair3#136]
Hello,

I am unsure of the model I should use for Minion r9.4.1 where the base calling was performed with dna_r9.4.1_450bps_fast.cfg

I saw a "fast" compatible model for r10.4 from rerio but not for r9.4.1

Could you please suggest the best model?

Thank you

**Comment by aquaskyline** [comment]
All HKU-provided ONT models at https://github.com/HKU-BAL/Clair3#hku-provided-models are for r9.4.1. Please check the one that matches the Guppy version you used.

**Comment by sagnikbanerjee15** [comment]
Hi,

Thanks for the quick reply. Among the models that have been mentioned, none are for the "fast" base calling method. The models are for either "hac" or "sup".

Thanks.

**Comment by aquaskyline** [comment]
You can use a SUP model on fast base-called data. But not the reverse.

**Comment by sagnikbanerjee15** [comment]
Oh good to know. Thanks!

**Comment by FAFUshiyan** [comment]
Hi，
I am using model dna_r9.4.1_450bps_fast_prom.cfg for basecalling, Guppy's version is Version 4.0.11, which would be the best choice of model for me?
Is r941_prom_hac_g360+g422.tar.gz the best choice?

**Comment by zhengzhenxian** [comment]
Hi, 

Yes, the `r941_prom_hac_g360+g422` model is recommended for Guppy3 and Guppy4 data.
