### ISSUE TITLE
Bump longphase to 1.3?

### ISSUE THREAD

**Issue by SamStudio8** [HKU-BAL/Clair3#137]
Clair3 packages [longphase 1.0](https://github.com/HKU-BAL/Clair3/blob/main/Makefile#L10), but we have been unable to use CRAM input with longphase < 1.3 due to a defect that was fixed [by this commit](https://github.com/twolinin/longphase/commit/5d450a3b7900271974a1610e73809cc3f12a60db). This requires us to overwrite the longphase binary as part of our conda installation process. Longphase 1.3 claims to improve accuracy as well as fix some bugs like the aforementioned, would it be appropriate to bump the version in the Makefile and distribute a new version of the Clair3 package to conda with longphase 1.3 included?

**Comment by aquaskyline** [comment]
Should be easy bumping up to 1.3. The [improvements](https://github.com/twolinin/longphase/releases/tag/v1.3) in v1.3 look promising, but I have not yet tested it on my side. Let me know if you have already got some promising testing results on your side so I can skip the testings.

**Comment by cjw85** [comment]
@SamStudio8 Do we have a before and after already?

@aquaskyline which test set do you prefer fo these sorts of regression tests?

**Comment by aquaskyline** [comment]
HG003 {1,2,3,4,5}0x. Other GIAB samples also work.

I got the tests automated so if you haven't tried Clair3 w/longphase v1.3, I can get it started quickly.

**Comment by SamStudio8** [comment]
I don't have an appropriate good before/after to hand, so if you've got some automated testing ready to go and you're happy to run it that would be great! 😇

**Comment by aquaskyline** [comment]
Sure, will let you know

**Comment by aquaskyline** [comment]
Clair3's performance increased moving from longphase v1.0 to v1.3, especially at lower coverages. Will update all installation options. Clair3's version number remains r12.

![image](https://user-images.githubusercontent.com/895289/192425412-0721bc1d-fe39-4f71-a630-dca6867c3d35.png)
