### ISSUE TITLE
Variant QUAL distribution between Clair3 and Clair

### ISSUE THREAD

**Issue by geocarvalho** [HKU-BAL/Clair3#139]
Hello team, thank you for making this amazing project open source!
I just want to know if the variant QUAL distributions should follow the same bimodal distribution from Clair's previous version.
![image](https://github.com/HKU-BAL/Clair/raw/master/docs/images/QualDist-ONT.png)

Because I can see that the default QUAL filter value is 2 for Clair3 and the median for my samples' variant is around 20 while for Clair is quite high ("The best quality cutoff is 748").

**Comment by aquaskyline** [comment]
The quality score in Clair3 has been revamped and is entirely different from Clair. The rule of thumb is to use 2 as the cutoff in Clair3. Experienced users might want to try different cutoffs for SNPs and Indels respectively.
