### ISSUE TITLE
Add source=clair3 and Clair3 version to VCF header metadata

### ISSUE THREAD

**Issue by peterk87** [HKU-BAL/Clair3#141]
Hello,

Would it be possible to add `##source=clair3` and Clair3 version to the VCF output metadata header for Clair3? 

```
##fileformat=VCFv4.2
##source=clair3
##clair3_version=0.1-r12
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=LowQual,Description="Low quality variant">
```

It would be nice to have some more provenance information in the VCF files by default. Right now I'm just adding `source=clair3` with awk.

Thanks!

**Comment by zhengzhenxian** [comment]
@peterk87  Sure, scheduled in the next release. 

Before that you might still need to add the INFO into the header manually using awk or using the command below:
`(printf "##source=clair3\n##clair3_version=0.1-r12\n"; zcat merge_output.vcf.gz;) | gzip -c > merge_output_update_header.gz`.

**Comment by aquaskyline** [comment]
added in v1.0.0
