### ISSUE TITLE
merged phased bam?

### ISSUE THREAD

**Issue by RichardCorbett** [HKU-BAL/Clair3#142]
Hi folks,
Sorry if this is a duplicate.  I thought I asked this a year or so ago, but I can't find the issue now.

In the temporary output folder, under `./tmp/phase_output/phase_bam/` I see chromosome-wise phased bams.   Is there a way to get a merged phased bam, or should I set up something to merge the bams if I want to use them downstream?

**Comment by zhengzhenxian** [comment]
Hi,
The phased BAMs in `./tmp/phase_output/phase_bam/` are actually intermediate phased BAMs phased by heterozygous pileup SNP candidates. We would suggest you to use the final output (phased_merge_output.vcf.g, with `--enable_phasing` option enabled) and [WhatsHap haplotag](https://whatshap.readthedocs.io/en/latest/guide.html#whatshap-haplotag-tagging-reads-by-haplotype-for-visualization) submodule to get a more reliable phased BAM.

**Comment by RichardCorbett** [comment]
Perfect. Thank you!
