### ISSUE TITLE
Clair3 doesn't find whatshap 

### ISSUE THREAD

**Issue by martabaragli** [HKU-BAL/Clair3#143]
Hello,
I am trying to launch Clair3 from a conda environment, I installed all the packages requested but when starting Clair I get this error:

`[ERROR] whatshap not found, please check you are in clair3 virtual environment`

I checked in the environment's bin and whatshap is there, I also tried setting the path manually and still get the same issue. 
The version I installed is 1.4.

**Comment by zhengzhenxian** [comment]
Hi, 
     Seems you did not activate the conda environment successfully, could you try to `source activate ${YOUR_CONDA_ABOLUTE_PATH}` and run `echo ${CONDA_PREFIX}` to check the path? Or you could directly pass the whatshap path to Clair3 using `--whatshap="${CONDA_PREFIX}/bin/whatshap"` option.

**Comment by martabaragli** [comment]
Hi,
I did activate Clair environment, and I don't have any issues with other necessary packages (like samtools) that are in the same directory. I also tried setting the path manually with the `--whatshap` option but Clair3 still doesn't find it.

**Comment by zhengzhenxian** [comment]
Hi,
Could you try to `echo` the whole command and paste it here for us to pinpoint the problem? Thanks!

**Comment by martabaragli** [comment]
I used this command:
`sh run_clair3.sh \
    --bam_fn /bam/path \
    --ref_fn /ref/path \
    --platform ont \
    --model_path models/r941_prom_hac_g360+g422/ \
    --threads 10 \
    --output /output/path`

then I added 
`--whatshap="${CONDA_PREFIX}/bin/whatshap"`
but nothing changed

**Comment by zhengzhenxian** [comment]
I guess you might need to use an absolute conda path for `--whatshap="YOUR_PATH/bin/whatshap"` as the ${CONDA_PREFIX} environment is empty.

**Comment by martabaragli** [comment]
I tried that way as well, but I get the same error anyway.

**Comment by aquaskyline** [comment]
@martabaragli thanks for the feedback. We need one more piece of information, in your Clair3 environment, please run `whatshap --version` and send us the output.

**Comment by aquaskyline** [comment]
That means whatshap is exposed to Clair3 with no problem. I am absolutely not sure, but It could be a corrupted local copy of Clair3 code. I would suggest you try either installing Clair3 with conda from scratch again, or try Singularity.
