### ISSUE TITLE
Some issues with r11 & r12

### ISSUE THREAD

**Issue by tuannguyen8390** [HKU-BAL/Clair3#144]
Hi there ! 

I recently made the change from r11 -> r12, and found that for some reason clair3 cannot run pass step 1 ([INFO] 1/7 Call variants using pileup model). 

Please see attached for the log file, in the folder I can find many core.xxxxx files.

![image](https://user-images.githubusercontent.com/47171822/197463656-cfbff1fa-f3f0-4a49-8535-9d6e5a7ac603.png)

[run_clair3.log](https://github.com/HKU-BAL/Clair3/files/9849301/run_clair3.log)

================================================
With r11 - I've also seen something in the log file - Not sure if I need to worry about this also :) 

ImportError: BioPython >= 1.73 must be installed to read block gzip files.
This is WhatsHap 1.0 running under Python 3.6.10
Traceback (most recent call last):
  File "/opt/conda/envs/clair3-env/lib/python3.6/site-packages/pyfaidx/__init__.py", line 398, in __init__
    from packaging.version import Version

ModuleNotFoundError: No module named 'packaging'

[run_clair3-r11.log](https://github.com/HKU-BAL/Clair3/files/9849391/run_clair3-r11.log)

Cheers,

Tuan

**Comment by zhengzhenxian** [comment]
Hi,
I guess the `core.*` files are the temporary caching file in the first step. Seem so many contigs are found in your BAM, could you try removing the option `--include_all_ctgs` and see if the problem persists?

For the r11 issue, I noticed that whatshap was not installed properly, you might need to re-build a new pure conda environment and re-run the sample. 

Hope it help!

**Comment by tuannguyen8390** [comment]
Hi there,

Is there a way to dodge that - I'm dealing with bovine (30 chromosome) so `--include_all_ctgs ` seems needed. With this run I also ran this with 48 cores (with r11 I used to do it with 24 cores and they ran fine for 90+ samples+ ), will that causing any problem ? 

With r11 I made a docker image using conda. Will try to fix it. 

Tuan

**Comment by aquaskyline** [comment]
Those core.* are core dumps. In r12 we switched some performance critical parts to using C programming. Looked at your r12 log, there is no output after starting step 1, and the core dumps are of almost the same size, my conjecture is it's an installation problem instead of other reasons that could also generate core dumps, such as segmentation fault or out of memory. For the r12, I suggest you to try Docker or Singularity installation.

In the r11 log you provided, it prompted "ModuleNotFoundError: No module named 'packaging'". `packaging` is not a library explicitly used by Clair3, and it seems to be a stardard library that should come together with python and pip. Again my best guess is it's related to installation problem.

**Comment by tuannguyen8390** [comment]
Oh I did not realize that you guys already have a docker image pre-built :). I made one my own deployed using Conda. Probably that's the issue, I will close the thread for now and reopen if I run into any other issue. Thanks - Tuan

**Comment by tuannguyen8390** [comment]
Just a quick comment for future reference if people run into the same problem (core dump) - I believe this is perhaps due to running Clair3 with BAM file mapped from FASTA files (instead of FASTQ). 

Some of the individuals that I currently have are sequenced in both short & long-read, therefore I deploy some read-polishing method to use short-reads to polish long-reads, the output of this are simply FASTA file because it is tricky to guestimate the PHRED score of the output FASTQ. When loading this to an aligner (say Minimap2), the read mapping score is set as "unknown", which potentially leads to the problem. Outputting QC read with FASTQ in my case simply made the problem went away. 

Tuan

**Comment by aquaskyline** [comment]
Thank you, Tuan. That's an important input. When you say "the read mapping score is set as 'unknown'", you mean the column is set to ".", correct?
