### ISSUE TITLE
'forced' genotyping missing variants

### ISSUE THREAD

**Issue by wdecoster** [HKU-BAL/Clair3#146]
Hi,

I'm running Clair3 (through docker) with  --vcf_fn=candidates.vcf.gz and   --print_ref_calls. However, not all twelve variants from candidates.vcf.gz are included in the output file, and the number of variants varies across samples between 4 and 12. Are there other options that I should activate? I understand that not all variants could be genotyped, but then I would expect an explicit ./. for those positions.

Thanks,
Wouter

**Comment by aquaskyline** [comment]
The missing variants are probably because they failed the `--min_coverage`, `--snp_min_af`, and `--indel_min_af`. My preliminary idea is to set the three options to 0, and one may choose to untrust a genotyping result if the DP or AF is too low. But I need to do some experiments to ensure that setting the three options to 0 won't cause problems for the other part of Clair3. Turn back to you soon.

**Comment by aquaskyline** [comment]
Setting `--snp_min_af` and `--indel_min_af` to 0 had no problem, but setting `--min_coverage` to 0 messed up input creation integrity checkings. Discussed with the team and we are adding a post-calling processing step that adds back './.'. New code available in two days.

**Comment by wdecoster** [comment]
Awesome, thank you so much

**Comment by aquaskyline** [comment]
Suppose you installed Clair3 using Conda, please clone the repo and overwrite the following files.
```
CLAIR3_PATH=${CONDA_PREFIX}/bin
git clone https://github.com/HKU-BAL/Clair3.git
cd Clair3
mkdir -p ${CLAIR3_PATH}/postprocess
cp -r clair3.py ${CLAIR3_PATH}/
cp -r postprocess/AddBackMissingVariantsInGenotyping.py ${CLAIR3_PATH}/postprocess/
cp -r scripts/clair3_c_impl.sh ${CLAIR3_PATH}/scripts/
cp -r scripts/clair3.sh ${CLAIR3_PATH}/scripts/
```
Clair3 now outputs './.' at genotyping loci that failed any filters (min coverage, min snp af, min indel af).

**Comment by wdecoster** [comment]
Thank you!
