### ISSUE TITLE
Dockerfile not reproducible

### ISSUE THREAD

**Issue by tuannguyen8390** [HKU-BAL/Clair3#148]
Hi @zhengzhenxian, 

After the last discussion where I got the conda installation broken and creates many core dump files @ issue #144 . I started to use the official docker image on [Dockerhub](https://hub.docker.com/r/hkubal/clair3) and have great time with it - no more dump files ! However, the image itself is a little bit big, and deploying that over a lot of time create a bit of I/O friction in the pipeline. So I tried to reproduce your `Dockerfile` in the current Github repo to re-create it and see if I can make it smaller. However I could not do it, perhaps because in the Dockerfile coding @ Line 48 is currently

```COPY . .``` 

I checked the layer on Dockerhub and seems like that is a masked layer. 

Anyway, theoretically speaking I believe that instead of using Ubuntu 16.04 & install Miniconda

```
FROM ubuntu:16.04
......
.....
.....
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda3-latest-Linux-x86_64.sh && \
    conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    conda create -n clair3 python=3.9.0 -y
```

We can simply replace it with 

```
FROM continuumio/miniconda3:latest
RUN  conda config --add channels defaults && \
conda config --add channels bioconda && \
conda config --add channels conda-forge && \
conda create -n clair3 
```
as currently Miniconda Python version is already 3.9.7. 

Many thanks !

Tuan

**Comment by zhengzhenxian** [comment]
Thank you, Tuan! We will try your suggestion and update the Dockerfile accordingly.

**Comment by aquaskyline** [comment]
Updated the Dockerfile. Terminal docker image size reduced by ~800MB.

**Comment by tuannguyen8390** [comment]
Thanks @aquaskyline, I will use the new docker file for now, any reduction in size is beneficial on the cloud. However at the moment the recipe is still not reproducible as 

```
L45 COPY . .
```

Many thanks,

Tuan

**Comment by aquaskyline** [comment]
by "not reproducible" do you mean a docker image could not be built using the Dockerfile on your side? can you show us any error messages on line 45?

**Comment by tuannguyen8390** [comment]
Sorry that was L46 :). Here is the command & output from my end

![image](https://user-images.githubusercontent.com/47171822/203176605-a1a280a9-bacb-4fec-a17a-d2e9da97504d.png)

**Comment by tuannguyen8390** [comment]
My bad, all good now, things misconfigured my end. Closing the issue now, thanks a lot for making the image smaller !
