### ISSUE TITLE
Questions about libclair3.c

### ISSUE THREAD

**Issue by oranges7** [HKU-BAL/Clair3#150]
/************************************************************/

    #include "kvec.h"
    #include "khash.h"
    #include "levenshtein.h"
    #include "medaka_bamiter.h"
    #include "medaka_common.h"
    #include "medaka_khcounter.h"
    #include "clair3_pileup.h"
    #include "clair3_full_alignment.h"
    

/************************************************************/

I would like to ask where the path to these header files is, thank you

**Comment by zhengzhenxian** [comment]
Hi,

Please kindly refer to the [src](https://github.com/HKU-BAL/Clair3/tree/main/src) directory and the [Makefile](https://github.com/HKU-BAL/Clair3/blob/main/Makefile) for more details, thanks.

**Comment by oranges7** [comment]
Sorry, I found the file after asking the question, delaying your precious time
