### ISSUE TITLE
Clair3 v0.1-r12: errors for full alignment calling, questions for merging output.

### ISSUE THREAD

**Issue by Shu8Zhao** [HKU-BAL/Clair3#152]
Hello,

I was testing Clair3 illumina v0.1-r12.  I downloaded and installed the package using conda. The command I was using is attached.

```
run_clair3.sh --threads=4 --min_coverage=10 --include_all_ctgs -p ilmn --snp_min_af=0.5 \
 --call_snp_only --no_phasing_for_fa --haploid_precise -b input.bam -f ref.fasta \
 -m /worksz/envs/clair3-illumina/bin/models/ilmn -o inter_dir

``` 
Then I realizes there was no variants called for chr1 using full-alignment, and found this error message in the log file. I also tested clair3 for ont data and it was running fine. So I figure this error could be only for illumina data.

```
[ERROR] Invalid bed input in 1-th row chr1 -34 1032
[mpileup] fail to read the header of -
Calling variants ...
Total processed positions in chr1 (chunk 1/1) : 0
ESC[91m[ERROR] No full-alignment output for file chr1//worksz/Var_calling/clair3_illumina/iAB3990001_clair3.intermediate/tmp/full_alignment_output/full_alignment_chr1.0_1.vcfESC[0m
Total time elapsed: 0.00 s
```

The first 5 lines of /tmp/full_alignment_output/candidate_bed/full_aln_regions_chr1 looks like this. It doesn't look right indeed. Do you  know how to fix this? Please let me know if more info is needed. 

```
chr1    -34     1032
chr1    2209966 2211032
chr1    2209966 2211032
chr1    2237966 2239032
chr1    2317966 2319032

```
The other question I have is how the output files from pileup and full alignment are merged? I have 1917 SNPs labeled as "PASS" in pileup.vcf.gz, and 5538 in full_alignment.vcf.gz. But there are only 495 left in merge_output.vcf.gz. Looks like a large amount of SNPs were filtered out. I was wondering how these output files merged for illumina data.

Thanks!

**Comment by zhengzhenxian** [comment]
Hi,
    Could you send the logs `${OUPUT_DIR}/run_clair3.log` and `${OUPUT_DIR}/log` to my email zxzheng@cs.hku.hk for us to pinpoint the Invalid bed issue?

For the Illumina platform, the final variants are acquired from all realigned variants from `full-alignment.vcf.gz` and the rest pileup variants from `pileup.vcf.gz`. The merging logic is [here](https://github.com/HKU-BAL/Clair3/blob/main/preprocess/MergeVcf.py#L59). But it is weird that only 495 calls are left in `merge_output.vcf.gz`, we might need to check the log first, thanks!

**Comment by Shu8Zhao** [comment]
Hi Zhenxian,

Thank you for your email! Sorry for the late reply. I was on Thanksgiving
break last weekend. The log files are attached to this email. Please let me
know if anything else can be helpful.

Thanks for the explanation for merging vcf files.

Best,
Shu

**Comment by zhengzhenxian** [comment]
Hi, Shu,
   
Seem I did not receive your email, would you pls send the log files again, thanks!


Zhenxian

**Comment by Shu8Zhao** [comment]
Hi Zhenxian,

No problem. I attached a zip file this time. Let me know if it reaches you.

Best,
Shu

**Comment by zhengzhenxian** [comment]
Hi Shu,

Still fail to receive your file, could kindly try to send to my personal email kourou1127@gmail.com, thanks!
