### ISSUE TITLE
Contig names not recognized

### ISSUE THREAD

**Issue by s-kubik** [HKU-BAL/Clair3#154]
Hello,

I have problems running Clair3 on aligned ONT reads (MInimap2 used for alignment). I get the following error message:
```
[WARNING] Contig name 7 provided but no mapped reads in BAM, skip!
[WARNING] No mapped reads support in BAM for provided contigs set 7
[WARNING] No contig intersection found, output header only in /mnt/ssd_disk/Oxford_run_arrow/Clair3_output/merge_output.vcf.gz
[INFO] Exit in environment checking
```
but I clearly see reads aligned to 7 when running
`samtools view ${INPUT_DIR}/sample1.fastq.gz.sam.bam -L ${INPUT_DIR}/chr7.bed`

The same error pops up for all chromosomes when do not restrict the target. Any idea what can be the issue?

**Comment by zhengzhenxian** [comment]
Hi, 
We checked the mapped read number directly using `samtools idxstats $BAM`, and skiped the contigs with no read mapped(The third column). Could you kindly add the `-F 2316` to `samtools view` to see any mapped reads found? 

Thanks!

**Comment by s-kubik** [comment]
Thanks for a quick response, indeed `idxstats` gives 0 mapped reads for all contigs but I still see the reads in 7 with `samtools view ${INPUT_DIR}/sample1.fastq.gz.sam.bam -F 2316`:
![image](https://user-images.githubusercontent.com/53193988/204312154-8bebc104-2406-49cf-a437-9a275ff2a6ef.png)

Interestingly, mapped reads are also found in output of `samtools flagstat ${INPUT_DIR}/sample1.fastq.gz.sam.bam`:

![image](https://user-images.githubusercontent.com/53193988/204312580-e752c043-e33b-4b27-9bb0-43b8b7615650.png)

**Comment by s-kubik** [comment]
I managed to figure out what was wrong: my indexing files were screwed up, after repreparing them with I get it right. Thanks for pointing me in the right direction!
