### ISSUE TITLE
tumour-normal mode

### ISSUE THREAD

**Issue by rowanhowellGE** [HKU-BAL/Clair3#157]
Hi,

Are there any plans to develop a tumour-normal joint calling mode?

Thanks

**Comment by aquaskyline** [comment]
In progress. Stay tuned.

**Comment by rowanhowellGE** [comment]
Amazing! I would be really interested to try this out. We have a lot of tumour normal pairs we would like to analyse so let me know if you would be willing to share an early version to test.

**Comment by aquaskyline** [comment]
Sure, we target to have the first release in early spring.

**Comment by AsmaaSamyMohamedMahmoud** [comment]
Hi, 
Is this option (tumor/normal joint calling mode) available with the current release on conda ?

**Comment by aquaskyline** [comment]
available with ClairS

**Comment by AsmaaSamyMohamedMahmoud** [comment]
Thank you!
