### ISSUE TITLE
Calling variants from RNA

### ISSUE THREAD

**Issue by husamia** [HKU-BAL/Clair3#159]
To call variants from RNA-Seq data. Reads mapped to the humgen reference with HiSat2 typically used for RNA-Seq. Would the ilmn model work for calling?

**Comment by aquaskyline** [comment]
It won't work well because Clair3 assumes a diploid input.

**Comment by husamia** [comment]
can I use the ilmn model with the --haploid_sensitive to do what I want?

**Comment by aquaskyline** [comment]
Yes, but be reminded we are completely unsure about the performance of Clair3 on RNA data.
