### ISSUE TITLE
Some errors in Representation Unification

### ISSUE THREAD

**Issue by huangnengCSU** [HKU-BAL/Clair3#16]
Hi, 
    In the steps of generating unified VCFs, a command is missing and a parameter is used incorrectly, which results in an error. In step 2, there should be a command `${PARALLEL} -j ${THREADS} ${TABIX} -p vcf ${PHASE_VCF_PATH}/phased_{1}.vcf.gz ::: ${CHR[@]}` behind the command `whatshap phase`. In step 4, the parameter `THRESHOLD` is not given and I think it should replaced by `MIN_AF`. 

Best,
Neng Huang

**Comment by aquaskyline** [comment]
Thanks Neng.

We made following amendements in `representation_unification.md`:
1. Added create index for the phased VCF files: `${PARALLEL} -j ${THREADS} tabix -p vcf ${PHASE_VCF_PATH}/phased_{1}.vcf.gz ::: ${CHR[@]}` at line 115.
2. Changed `${THRESHOLD}` to `${MIN_AF}`  at line 161.
3. Removed unnecessary path parameter `${FULL_ALIGNMENT_OUTPUT_PATH}` at line 192.

**Comment by huangnengCSU** [comment]
@aquaskyline 
Thanks for fixing the problems immediately. I met a new problem in the step of `representation unification` that the command needs too much memory. The input bam is generated from data of NA12878 with 20 coverage. The server has 1.5T memory and 80 cpu cores. The command reports `Cannot allocate memory`.

Best
Neng

**Comment by aquaskyline** [comment]
`representation unification` takes around 20G per thread now, but later we will deduce the memory consumption by adding a generator to the code, the current implementation stores all sites in memory.

**Comment by huangnengCSU** [comment]
@aquaskyline 
I use 10 threads to perform unification. The program has been running for over 72 hours without stopping. Steps 1 to 4 run successfully and generate the corresponding output files. Step 5 `Unify Representation for true variant set and candidate sites` runs for 72 hours without any output information.

```
${PARALLEL} --joblog ${OUTPUT_DIR}/unify_repre.log -j${THREADS} \
"${PYPY} ${CLAIR3} UnifyRepresentation \
    --var_fn ${VAR_OUTPUT_PATH}/var_{1} \
    --candidate_details_fn_prefix ${CANDIDATE_DETAILS_PATH}/{1}_ \
    --ref_fn ${REFERENCE_FILE_PATH} \
    --output_vcf_fn ${VCF_OUTPUT_PATH}/vcf_{1}_{2} \
    --chunk_id {2} \
    --chunk_num ${chunk_num} \
    --bed_fn ${BED_FILE_PATH} \
    --platform ${PLATFORM} \
    --ctgName ${CHR_PREFIX}{1}" ::: ${CHR[@]} ::: ${CHUNK_LIST[@]} > ${OUTPUT_DIR}/RU.log
```

**Comment by zhengzhenxian** [comment]
Hi, Neng,
Our experience is that 50x of ONT data takes five threads around an hour. So we are sure your tasks have run into problems and can be stopped. Are your tasks still eating up CPU? How many folds of data and what's basecaller version are you using? Thanks.

zhenxian

**Comment by huangnengCSU** [comment]
Hi,
I do not know whether the task still eating up cpu source before I kill it. The data I used is NA12878 with 20 coverage. And the basecaller is Guppy 4.0. I found that many most of the files in the folder `vcf_output` is null. 
![image](https://user-images.githubusercontent.com/28866823/120274588-a31e4700-c2e2-11eb-8467-3650f05e2bf4.png)

here is my script:
```
#!/bin/bash
# @Author: huang neng
# @Date:   2021-06-01 14:03:19
# @Last Modified by:   huang neng
# @Last Modified time: 2021-06-01 14:04:52

#!/bin/bash

# Setup variables
CLAIR3="/public/home/user/tools/Clair3/clair3.py"                                     # clair3.py
PYPY="/public/home/user/anaconda3/envs/clair3/bin/pypy3.6"                                 # e.g. pypy3
WHATSHAP="/public/home/user/anaconda3/envs/clair3/bin/whatshap"                         # e.g. whatshap
PARALLEL="/public/home/user/anaconda3/envs/clair3/bin/parallel"                         # e.g. parallel
TABIX="/public/home/user/anaconda3/envs/clair3/bin/tabix"                               # e.g. tabix
SAMTOOLS="/public/home/user/anaconda3/envs/clair3/bin/samtools"                         # e.g. samtools

# Input parameters
PLATFORM="ont"                       # e.g. {ont, hifi, ilmn}
VCF_FILE_PATH="/public/home/user/ont-quickstart/input/NA12878-20X/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz"                   # e.g. hg003.vcf.gz
BAM_FILE_PATH="/public/home/user/ont-quickstart/input/NA12878-20X/reads2ref.sort.bam"                   # e.g. hg003.bam
REFERENCE_FILE_PATH="/public/home/user/ont-quickstart/input/NA12878-20X/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna"           # e.g. hg003.fasta
BED_FILE_PATH="/public/home/user/ont-quickstart/input/NA12878-20X/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed"                   # e.g. hg003.bed
OUTPUT_DIR="/public/home/user/ont-quickstart/input/NA12878-20X/clair3_full_alignment_training/"					       # e.g. output

# Chromosome prefix ("chr" if chromosome names have the "chr" prefix)
CHR_PREFIX="chr"

# array of chromosomes (do not include "chr"-prefix)
CHR=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X)

# Number of threads to be used
THREADS=10

# The number of chucks to be divided into for parallel processing
chunk_num=15
CHUNK_LIST=`seq 1 ${chunk_num}`

# Minimum AF required for a candidate variant
MIN_AF=0.08

# Temporary working directory
CANDIDATE_DETAILS_PATH="${OUTPUT_DIR}/candidate_details"
SPLIT_BED_PATH="${OUTPUT_DIR}/split_beds"
VCF_OUTPUT_PATH="${OUTPUT_DIR}/vcf_output"
VAR_OUTPUT_PATH="${OUTPUT_DIR}/var"
PHASE_VCF_PATH="${OUTPUT_DIR}/phased_vcf"
PHASE_BAM_PATH="${OUTPUT_DIR}/phased_bam"

mkdir -p ${CANDIDATE_DETAILS_PATH}
mkdir -p ${SPLIT_BED_PATH}
mkdir -p ${VCF_OUTPUT_PATH}
mkdir -p ${VAR_OUTPUT_PATH}
mkdir -p ${PHASE_VCF_PATH}
mkdir -p ${PHASE_BAM_PATH}


cd ${OUTPUT_DIR}

# WhatsHap phasing vcf file if vcf file includes '|' in INFO tag
${WHATSHAP} unphase ${VCF_FILE_PATH} > ${OUTPUT_DIR}/INPUT.vcf.gz

# WhatsHap phase vcf file
${PARALLEL} --joblog ${PHASE_VCF_PATH}/phase.log -j${THREADS} \
"${WHATSHAP} phase \
    --output ${PHASE_VCF_PATH}/phased_{1}.vcf.gz \
    --reference ${REFERENCE_FILE_PATH} \
    --chromosome ${CHR_PREFIX}{1} \
    --ignore-read-groups \
    --distrust-genotypes \
    ${OUTPUT_DIR}/INPUT.vcf.gz \
    ${BAM_FILE_PATH}" ::: ${CHR[@]}

${PARALLEL} -j ${THREADS} ${TABIX} -p vcf ${PHASE_VCF_PATH}/phased_{1}.vcf.gz ::: ${CHR[@]}
    
# WhatsHap haplotags bam file
${PARALLEL} --joblog ${PHASE_BAM_PATH}/haplotag.log -j${THREADS} \
"${WHATSHAP} haplotag \
    --output ${PHASE_BAM_PATH}/{1}.bam \
    --reference ${REFERENCE_FILE_PATH} \
    --regions ${CHR_PREFIX}{1} \
    --ignore-read-groups \
    ${PHASE_VCF_PATH}/phased_{1}.vcf.gz \
    ${BAM_FILE_PATH}" ::: ${CHR[@]}

# Index the phased bam file using samtools
${PARALLEL} --joblog ${PHASE_BAM_PATH}/index.log -j ${THREADS} ${SAMTOOLS} index -@12 ${PHASE_BAM_PATH}/{1}.bam ::: ${CHR[@]}

# Split bed file regions according to the contig name and extend bed region
${PARALLEL} --joblog ${SPLIT_BED_PATH}/split_extend_bed.log -j${THREADS} \
"${PYPY} ${CLAIR3} SplitExtendBed \
    --bed_fn ${BED_FILE_PATH} \
    --output_fn ${SPLIT_BED_PATH}/{1} \
    --ctgName ${CHR_PREFIX}{1}" ::: ${CHR[@]}

# Get true variant label information from VCF file
${PARALLEL} --joblog ${VAR_OUTPUT_PATH}/get_truth.log -j${THREADS} \
"${PYPY} ${CLAIR3} GetTruth \
    --vcf_fn ${PHASE_VCF_PATH}/phased_{1}.vcf.gz \
    --ctgName ${CHR_PREFIX}{1} \
    --var_fn ${VAR_OUTPUT_PATH}/var_{1}" ::: ${CHR[@]}

# Create candidate details for representation unification
${PARALLEL} --joblog ${CANDIDATE_DETAILS_PATH}/create_tensor.log -j${THREADS} \
"${PYPY} ${CLAIR3} CreateTensorFullAlignment \
    --bam_fn ${PHASE_BAM_PATH}/{1}.bam \
    --ref_fn ${REFERENCE_FILE_PATH} \
    --indel_fn ${CANDIDATE_DETAILS_PATH}/{1}_{2} \
    --ctgName ${CHR_PREFIX}{1} \
    --samtools ${SAMTOOLS} \
    --min_af ${MIN_AF} \
    --extend_bed ${SPLIT_BED_PATH}/{1} \
    --unify_repre_fn ${CANDIDATE_DETAILS_PATH}/{1}_{2} \
    --unify_repre \
    --phasing_info_in_bam \
    --bed_fn ${BED_FILE_PATH} \
    --chunk_id {2} \
    --chunk_num ${chunk_num}" ::: ${CHR[@]} ::: ${CHUNK_LIST[@]}
    
${PARALLEL} --joblog ${OUTPUT_DIR}/unify_repre.log -j${THREADS} \
"${PYPY} ${CLAIR3} UnifyRepresentation \
    --var_fn ${VAR_OUTPUT_PATH}/var_{1} \
    --candidate_details_fn_prefix ${CANDIDATE_DETAILS_PATH}/{1}_ \
    --ref_fn ${REFERENCE_FILE_PATH} \
    --output_vcf_fn ${VCF_OUTPUT_PATH}/vcf_{1}_{2} \
    --chunk_id {2} \
    --chunk_num ${chunk_num} \
    --bed_fn ${BED_FILE_PATH} \
    --platform ${PLATFORM} \
    --ctgName ${CHR_PREFIX}{1}" ::: ${CHR[@]} ::: ${CHUNK_LIST[@]} > ${OUTPUT_DIR}/RU.log
    
cat ${FULL_ALIGNMENT_OUTPUT_PATH}${VCF_OUTPUT_PATH}/vcf_* | ${PYPY} ${CLAIR3} SortVcf --output_fn ${OUTPUT_DIR}/unified.vcf
bgzip -f ${OUTPUT_DIR}/unified.vcf
tabix -f -p vcf ${OUTPUT_DIR}/unified.vcf.gz
```

**Comment by zhengzhenxian** [comment]
Thanks for your script, it is abnormal if the chunked output vcf is empty, we are not sure whether such low-coverage data leads to the problem, could you try setting a higher allele frequency by setting ```MIN_AF=0.2``` in the default setting and add a smaller partition size by add `--partition_size 5` in 
```
${PARALLEL} --joblog ${OUTPUT_DIR}/unify_repre.log -j${THREADS} \
"${PYPY} ${CLAIR3} UnifyRepresentation \
    --var_fn ${VAR_OUTPUT_PATH}/var_{1} \
    --candidate_details_fn_prefix ${CANDIDATE_DETAILS_PATH}/{1}_ \
    --ref_fn ${REFERENCE_FILE_PATH} \
    --output_vcf_fn ${VCF_OUTPUT_PATH}/vcf_{1}_{2} \
    --chunk_id {2} \
    --chunk_num ${chunk_num} \
    --bed_fn ${BED_FILE_PATH} \
    --platform ${PLATFORM} \
    --ctgName ${CHR_PREFIX}{1} \
    --partition_size 5" ::: ${CHR[@]} ::: ${CHUNK_LIST[@]} > ${OUTPUT_DIR}/RU.log
```
Please let us know if it could run successfully, thanks.

**Comment by aquaskyline** [comment]
Let me elaborate a bit. We suspect that the relatively low coverage (~20x) you are using is the culprit of a long running time. Low coverage ONT generates excessively more candidates. In `UnifyRepresentation`, `MIN_AF` controls the minimum allele frequency of the candidates considered for representation unification. The higher the `MIN_AF`, the fewer candidates are involved. `--partition_size` controls the number of adjacent candidates being grouped together for representation unification. The lower the `--partition_size`, the fewer combinations to be tested. That's the reason why we suggest you test `MIN_AF=0.2` (or even higher like 0.35), and `--partition_size=5` (or even lower like 3) to make sure the program runs to an end first.

Another suggestion is to try playing with the parameters with a single instance of `UnifyRepresentation`. Adding an option ` --dryrun` immediately after `${PARALLEL}` gives you the commands parallel is going to run. You can use a command from them and try playing with the two parameters to ensure `UnifyRepresentation` runs to an end.

These suggestions are for debugging only. To train a model for production, we won't suggest a high `MIN_AF` or a low `--partition_size`. We would suggest using a high coverage.

**Comment by huangnengCSU** [comment]
@aquaskyline @zhengzhenxian 
Thanks for your suggestions. The program runs to an end when I set `MIN_AF=0.2` and `partition_size=5`. As Dr. Luo said, UnifyRepresentation on a low coverage dataset with low `MIN_AF` and high `partition_size` needs to be tested.

Best
Neng Huang
