### ISSUE TITLE
Missing variants in merge_output.vcf.gz

### ISSUE THREAD

**Issue by sejmodha** [HKU-BAL/Clair3#161]
Hi There,

I noticed that a range of variants that have passed the quality checks in `pileup.vcf.gz` and `full_alignment.vcf.gz` that are missing from `merge_output.vcf.gz`. 

Is this a known bug in the latest version of Clair3 that is available through conda? What is the best way to fix this? I see those variants present in the BAM alignments and they are picked up properly in previous stages of the pipeline, but they are missing from the final output file.

Thanks
Sej

**Comment by zhengzhenxian** [comment]
Hi,

Not all pileup and full-alignment variants would be included in the combined file, those with low quality score (QUAL < 2) are removed.

Zhenxian

**Comment by sejmodha** [comment]
I am not sure if that is the case for my data as I can see that QUAL is >2 for those variants that are being missed. I can confirm that those are only absent in the merged VCF file if `--haploid_precise` mode.  If Clair3 is run with `--haploid_precise` or without `--haploid_precise` or `haploid_sensitive` options then those variants are included in the merged VCF file.

Moreover, on a separate note, a lot of variants (again those with QUAL >2) are simply not called by Clair3 in a range of datasets which are clearly visible in IGV when alignments are manually inspected. I am not entirely sure whether the internal "thresholds" for Clair3 need to be modified to include these obvious variants that are missed by Clair3.

**Comment by zhengzhenxian** [comment]
Hi, 

Can you send over the BAMs and fasta of one or a few missing variants to my email(zxzheng@cs.hku.hk)? We need to check the result before pinpoint the problem. Thanks!

Zhenxian

**Comment by jacqgg** [comment]
I'm using Clair3 v1.0.0 (bioconda) and I have the same problem, some variants are missing, I tested many options like --snp_min_af=0.0 --indel_min_af=0.0 --qual=2 and I steel cant see variants in any of output vcf files.

IGV example (coverage ~320x):
![image](https://user-images.githubusercontent.com/15021501/223707534-ed5fc8fb-6ca8-4372-8e4f-c348ee8ab694.png)

and results like (in this case merged.vcf):
![image](https://user-images.githubusercontent.com/15021501/223707872-d072415c-4812-4414-b095-a9e1caf41450.png)
from the first 3 snps from IGV I can only see results for one in vcf and I can't understand why this is happening. Any suggestions?

**Comment by aquaskyline** [comment]
@jacqgg It is not that the variant is missing, you can see that at position 30, Clair3 has decided it is a reference call at the position. Clair3 could be incorrect, but it was trained to remove false variants even though they look so much like true ones. Are the variants at 30bp and 34bp known to be true or were verified by other sequencing data?
