### ISSUE TITLE
Missing phasing on some variants

### ISSUE THREAD

**Issue by mproberts99** [HKU-BAL/Clair3#164]
Hello,
I ran Clair3 R10 model with the --enable_phasing option and noticed not all variants are phased in the final output. The two positions I am looking at are 29 bp apart on the same amplicon. Does this indicate a failure of the phasing algorithm or do I need to change another parameter? I've pasted the VCF output below and attached an IGV screenshot of the region.
chr7	117548606	.	A	ATG	22.5	PASS	F	GT:GQ:DP:AF	0/1:22:69:0.2464
chr7	117548628	.	G	T	22.34	PASS	F	GT:GQ:DP:AF:PS	1|0:22:69:0.3913:117548628

<img width="134" alt="Screenshot 2023-01-24 at 4 40 48 PM" src="https://user-images.githubusercontent.com/60239089/214428140-d4c5879f-d32a-4aa5-ba5a-255f7e438848.png">

**Comment by aquaskyline** [comment]
We believe it's a decision of the phasing algorithm. As the last step, Clair3 simply runs Whatshap with default parameters on `merge_output.vcf.gz`.

**Comment by mproberts99** [comment]
The latest updates show  --longphase_for_phasing was added as an option and then updated to enable by default, is that correct? Does that mean longphase is being used instead of whatshap? It looks like longphase has not yet added a feature to phase indels due to their high error rate with ONT in the past. If longphase is being run by default, is there a parameter to change the default back to WhatsHap?

**Comment by aquaskyline** [comment]
The naming of the two options `--enable_phasing` and `--longphase_for_phasing` are confusing. Clair3 has two steps that require phasing: "intermediate step: phase high-quality heterozygous variants and haplotag the reads for full-alignment model calling", and "last step: phase the output variant calls".  `--longphase_for_phasing` controls the behavior of the intermediate step. `--enable_phasing` controls the last step. `--longphase_for_phasing=True` means using longphase, while `--longphase_for_phasing=False` means using Whatshap for the intermediate step. `--enable_phasing` means using Whatshap for the last step. We have not yet implemented using longphase for the last step, but that's scheduled for the next release.

**Comment by mproberts99** [comment]
Ah okay, thank you for the explanation, that makes much more sense. We needed the indel in that screenshot above to be phased so I ended up re-running the merge_output.vcf through Whatshap and added the --indels option. Perhaps that could be a helpful option to include for some users in next releases. Thank you again!
