### ISSUE TITLE
Data request

### ISSUE THREAD

**Issue by shiying1595** [HKU-BAL/Clair3#167]
I cannot download this data, could you please share it with me? I am in the mainland. 

http://www.bio8.cs.hku.hk/clairvoyante/orginalData_hg002/illumina/HG002.GRCh38.50x.rg.bam

Thank you very much!

**Comment by zhengzhenxian** [comment]
Hi,
The link is deprecated, you can download the BAMs directly from GIAB FTP server [here](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/NIST_Illumina_2x250bps/novoalign_bams/). You can also acquire other GIAB samples from GIAB [github website](https://github.com/genome-in-a-bottle/giab_data_indexes). Hope it help!

**Comment by shiying1595** [comment]
Sincere thanks
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Feb 6, 2023 03:17 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [HKU-BAL/Clair3] Data request (Issue #167)

&nbsp;



 
Hi,
 The link is deprecated, you can download the BAMs directly from GIAB FTP server here. You can also acquire other GIAB samples from GIAB github website. Hope it help!
