### ISSUE TITLE
SelectCandidates phasing default behaviour

### ISSUE THREAD

**Issue by ftostevin** [HKU-BAL/Clair3#17]
https://github.com/HKU-BAL/Clair3/blob/c1517320e18ea0ca04f04256fb530e41219d60d0/preprocess/SelectCandidates.py#L352-353

The parameter `--phasing_info_in_bam` is defined `store_false`, which means it is true by default, in contradiction to the description. Which is the expected behaviour?

**Comment by aquaskyline** [comment]
The help info was wrong, the default is true since we used "store_false". Thanks for the report. We are checking all "store_false" and "store_true" and will update after the check.

**Comment by aquaskyline** [comment]
1. Fixed the default value in help info in `preprocess/SelectCandidates.py` at line 353
2. Fixed the default value in help info in  ·preprocess/SelectHetSnp.py` at line 334

**Comment by ftostevin** [comment]
Thank you for the clarification
