### ISSUE TITLE
resume pipeline from stalled process

### ISSUE THREAD

**Issue by husamia** [HKU-BAL/Clair3#170]
I ran the command 

`run_clair3.sh --bam_fn=sample_GRCh38_sorted.bam --ref_fn=../Homo_sapiens_assembly38.fasta --model_path=/opt/models/ilmn/ --threads=5 --platform=ilmn -o sample_GRCh38_Clair3.vcf.gz --sample_name=name --gvcf --remove_intermediate_dir --enable_long_indel`

I have antimalware scanner running which stalled my process at this step. No error message. Just completely stopped for days. a known issue with Docker Desktop and Antimalware Service in Windows

`[INFO] 7/7 Merge pileup VCF and full-alignment VCF
`

How can I resume?

**Comment by zhengzhenxian** [comment]
Hi,

I think you might need to manually comment the codes from line 91 to line 288 in [scripts/clair3_c_impl.sh](https://github.com/HKU-BAL/Clair3/blob/main/scripts/clair3_c_impl.sh). It will then only run the final merging steps, Thanks!

**Comment by husamia** [comment]
I commented the lines  91-288 in clair3_c_impl.sh then re-executed the same exact command


first few lines of log, 
```

`[INFO] Check environment variables
[INFO] --include_all_ctgs not enabled, use chr{1..22,X,Y} and {1..22,X,Y} by default
[INFO] Call variant in contigs: chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY
[INFO] Chunk number for each contig: 50 49 40 39 37 35 32 30 28 27 28 27 23 22 21 19 17 17 12 13 10 11 32 12
[INFO] 1/7 Call variants using pileup model
[INFO] Delay 1 seconds before starting variant calling ...
[mpileup] 1 samples in 1 input files
Calling variants ...
Processed 20000 tensors
Processed 40000 tensors
Processed 60000 tensors
Total processed positions in chr1 (chunk 3/50) : 63717
Total time elapsed: 174.56 s
[INFO] Delay 4 seconds before starting variant calling ...
[mpileup] 1 samples in 1 input files
Calling variants ...
Processed 20000 tensors
Processed 40000 tensors
Processed 60000 tensors
Total processed positions in chr1 (chunk 7/50) : 63057
Total time elapsed: 174.70 s
[INFO] Delay 3 seconds before starting variant calling ...
[mpileup] 1 samples in 1 input files
Calling variants ...
Processed 20000 tensors
Processed 40000 tensors
Processed 60000 tensors`
```
