### ISSUE TITLE
AssertionError：(len(fi.root.label) == len(fi.root.position) == len(fi.root.position_matrix) == len(fi.root.alt_info))

### ISSUE THREAD

**Issue by willow2333** [HKU-BAL/Clair3#171]
"assert (len(fi.root.label) == len(fi.root.position) == len(fi.root.position_matrix) == len(fi.root.alt_info))
AssertionError"

Hi，
 I get the error about above, when training the full-alignment model. The number of "len(fi.root.label)" is 3X comparing  "len(fi.root.position)","len(fi.root.position_matrix)" and "len(fi.root.alt_info))". The steps of before are correct. How can resolve this issue, thanks for your help!
 best wishes!

**Comment by zhengzhenxian** [comment]
Hi, 

Seem our repo did not include the size check code. Could you specify which step the error occurs?

**Comment by willow2333** [comment]
Hi,
    Thanks for your reply firstly! The below command was run, the error occurs.  thanks for your help!

${PARALLEL} --joblog ${DATASET_FOLDER_PATH}/mergeBin.log -j${THREADS} \
"${PYTHON3} ${CLAIR3} MergeBin \
    ${TENSOR_CANDIDATE_PATH}/tensor_{2}_{3}_{1}_* \
    --platform ${PLATFORM} \
    --out_fn ${BINS_FOLDER_PATH}/bin_{2}_{3}_{1}" ::: ${CHR[@]} ::: ${ALL_SAMPLE[@]} :::+ ${DEPTHS[@]}

**Comment by zhengzhenxian** [comment]
Hi,

Could you try to re-run the 5-th [step](https://github.com/HKU-BAL/Clair3/blob/main/docs/full_alignment_training_r1.md#5-create-full-alignment-tensor-using-the-createtrainingtensor-submodule) to see if the error persist? We speculate the `CreateTrainingTensor` submodule failed to generate the tensors.

**Comment by willow2333** [comment]
Hi,
   I try to re-run the 5-th step, no error occurs, part of log as below. The folder of "tensor_can" has tensors like below. When I run the 6-th step, there is "AssertionError". It is like that the length of label is 3X than others (position, position_matrix and alt_info).
![image](https://user-images.githubusercontent.com/47717534/219565341-01e61de4-06a8-4133-bf14-45487aa0fd41.png)

![image](https://user-images.githubusercontent.com/47717534/219564302-0a755e67-e889-4434-b722-b9c96f12d4b8.png)

**Comment by zhengzhenxian** [comment]
Hi,

We tested the training workflow but failed to repeat your errors. The label size matched the input size. Which platform do you used for training?

**Comment by willow2333** [comment]
Hi,
   Thank you for your reply firstly. I get the HG002_GIAB_MinION_GridION_Guppy_4.2.2.fastq.gz from the [url](https://s3-us-west-2.amazonaws.com/human-pangenomics/NHGRI_UCSC_panel/HG002/nanopore/Guppy_4.2.2/HG002_GIAB_MinION_GridION_Guppy_4.2.2.fastq.gz) for training.
