### ISSUE TITLE
Does the data of training r941_prom_hac_g360+g422 model use HG002 with 432 coverage?

### ISSUE THREAD

**Issue by oranges7** [HKU-BAL/Clair3#172]
Does the data of training r941_prom_hac_g360+g422 model use HG002 with 432 coverage?

**Comment by oranges7** [comment]
Is the ont data in the training data set used in all the samples in the table?（r941_prom_hac_g360+g422）

**Comment by zhengzhenxian** [comment]
Hi,

[Here](https://github.com/HKU-BAL/Clair3/blob/main/docs/training_data.md#ont) is the all training samples(HG001, HG002, HG004, HG005) for the r941_prom_hac_g360+g422 model. HG002 included two coverages, 432-fold and 49-fold.

**Comment by oranges7** [comment]
Thank you very much for your reply. I see.

**Comment by oranges7** [comment]
Hi，
There seems to be an error in the link to the 49 coverage HG002 sample. Could you please check it?

**Comment by oranges7** [comment]
It seems that there is something wrong with the links to the data in Guppy v3.6.0.

**Comment by aquaskyline** [comment]
Some links were deprecated by precisionFDA, but basically they are GIAB data, and you can find them online. All GIAB data is gathered at https://github.com/genome-in-a-bottle/giab_data_indexes
