### ISSUE TITLE
Wondering if you know the phasing accuracy among duplications in the human genome

### ISSUE THREAD

**Issue by sarahdada** [HKU-BAL/Clair3#173]
Hello!

I have a 5x copy number of a 7000bp region on an autosome. It's being phased as homozygous ( I used Clair3, and then WhatsHap haplotag). It's within the same phase block. This is a little disconcerting since it's such a specific structural variant. 

I'm looking at using population data to determine if this is true, or if it's a result of the read going through the same region several times with not much flanking sequence. Wondering if you have any ideas or thoughts?

Thanks kindly,
Sarah

**Comment by zhengzhenxian** [comment]
Hi, 

WhatsHap would not phase SV, and it would be great if you could post an IGV screenshot of the SV (would be better with haplotagging information), thanks.

Zhenxian
