### ISSUE TITLE
No phased indel variants in phased_merged_output.vcf.gz

### ISSUE THREAD

**Issue by yangao07** [HKU-BAL/Clair3#174]
Hi,

First of all, great tool!

After running clair3 with "--enable_phasing", I found that all the indel variants are not phased in the final phased_merged_output.vcf.gz, is this intended?
If so, is there any option to enable the indel phasing?

Thanks!
Yan

**Comment by aquaskyline** [comment]
Clair3 uses Whatshap for phasing the variants after variant calling. All variants, including indels are included for phasing.
