### ISSUE TITLE
chrM by default

### ISSUE THREAD

**Issue by Coppini** [HKU-BAL/Clair3#178]
This is just a suggestion, since the solution is quite clear by specifying contigs with `--ctg_name`. 

We were running Clair3 for a large number of samples and only recently did we realize it wasn't calling variants in chrM. Since it's such a small contig and it's considered of clinical importance, would you consider adding it to the default chromosomes Clair3 considers for variant-calling?

We believe that introducing it to the defaults would be beneficial to other users as well.

**Comment by aquaskyline** [comment]
Thank you for the suggestion. Just in case useful to other users, using a customized list that includes `chrM` for the `--ctg_name` option can add mitochondrial variants to the final results.

Clair3 can call variants in `chrM` if being set to do so. But no training data on chrM were used for model training, and the diploid assumption in Clair3 actually doesn't fit variant calling in chrM perfectly. Our tests showed that mitochondrial variants with AF <0.2 cannot be sensitively called by Clair3.
