### ISSUE TITLE
Post processing via conda

### ISSUE THREAD

**Issue by damioresegun** [HKU-BAL/Clair3#182]
Hi, 

I installed clair3 via conda and ran it successfully on ONT amplicon reads. However I was unable to run the postprocessing "SwitchZygosityBasedOnSVCalls" module. Upon further looks, it seems like the postprocessing directory and scripts are completely missing from the conda release. Unsure if this can be fixed by simply cloning that directory off github and inserting it into my conda install or should I follow these guidelines here: https://github.com/HKU-BAL/Clair3/issues/146#issuecomment-1294717606

**Comment by zhengzhenxian** [comment]
Hi, 

Thanks for reporting, we made a new [PR](https://github.com/bioconda/bioconda-recipes/pull/39919/commits/2f309654e72c9f9daee893ddc1b8e7ba4f95c4c8) in bioconda. Please kindly install the latest conda package. Or you could  follow the guidelines you mentioned to copy the postprocessing folder to your conda envrionment.

Zhenxian

**Comment by damioresegun** [comment]
Hi, 

Thanks for getting back so quickly. Yes I followed those guidelines and copied just the postprocessing directory over and it ran. Although it gave me 0 SNPs being switched. Which I'm currently not sure is right but that's my problem. 

Thanks again for your work!
Dami
