### ISSUE TITLE
run SwitchZygosityBasedOnSVCalls with singularity image?

### ISSUE THREAD

**Issue by MariBGO** [HKU-BAL/Clair3#183]
Hi, 
I have successfully ran clair3 with a singularity image on ONT reads. However, when I try to run "SwitchZygosityBasedOnSVCalls" module, I run into problems- error message does not recognize the options --clair3_vcf_input --sv_vcf_input or  --vcf_output. Is there a workaround for this or is this module not available through docker installation?

FYI, I have made my image using the latest version on docker hub (as of 8 days ago). 

Thanks,
Mari

**Comment by zhengzhenxian** [comment]
Hi, Mari,

Could you send the logs ${OUPUT_DIR}/run_clair3.log and ${OUPUT_DIR}/log to my email [zxzheng@cs.hku.hk](mailto:zxzheng@cs.hku.hk)? Thanks!

Zhenxian

**Comment by zhengzhenxian** [comment]
The postprocessing "SwitchZygosityBasedOnSVCalls" module should in docker image already, pls re-run the whole workflow again, thanks.
