### ISSUE TITLE
SwitchZygosityBasedOnSVCalls error

### ISSUE THREAD

**Issue by biorococo** [HKU-BAL/Clair3#186]
SwitchZygosityBasedOnSVCalls is showing the following error when using VCF from latest version of Sniffles2:

Traceback (most recent call last):
  File "/opt/bin/clair3.py", line 105, in <module>
    main()
  File "/opt/bin/clair3.py", line 99, in main
    submodule.main()
  File "/opt/bin/postprocess/SwitchZygosityBasedOnSVCalls.py", line 456, in main
    Run(args)
  File "/opt/bin/postprocess/SwitchZygosityBasedOnSVCalls.py", line 348, in Run
    and v.af <= max_af_for_zygosity_switching \
TypeError: '<=' not supported between instances of 'NoneType' and 'float'

Sniffles2 VCF do not contain AF in the FORMAT column, it is present in INFO column and I that seems to break the execution. I'm not sure if it is related to Sniffles version but that seems the case.

I'm attaching a test.vcf with couple of records. Also have in mind there are records without AF annotated in Sniffles2 so might be safe to deal with those. 

[test.vcf.gz](https://github.com/HKU-BAL/Clair3/files/11044225/test.vcf.gz)

**Comment by RenzoTale88** [comment]
Hi, sorry to come back with this, would it be possible to update the anaconda release in integrate this change?
Thanks in advance
Andrea

**Comment by zhengzhenxian** [comment]
@RenzoTale88 Sorry to miss your request, we have updated conda version to v1.0.1 with the bug fixed.
