### ISSUE TITLE
Bump Whatshap to v1.7?

### ISSUE THREAD

**Issue by SamStudio8** [HKU-BAL/Clair3#193]
Clair3 [pins WhatsHap at version 1.4](https://github.com/bioconda/bioconda-recipes/blob/9fba3ce5bd119835dee0242b06372b984074f797/recipes/clair3/meta.yaml#L36) and is missing out on some performance improvements, [particularly related to the `haplotag` step](https://github.com/whatshap/whatshap/commit/dd139ce445e87027a5da21e3729b98e85b48e372). Would it be appropriate to bump the version in the package and distribute a new version of Clair3 to conda with WhatsHap 1.7 pinned?

**Comment by aquaskyline** [comment]
Bumping up WhatsHap to 1.7 in the next release. Any idea if this issues is also fixed in the next WhatsHap version #163 ?

**Comment by SamStudio8** [comment]
@aquaskyline Much appreciated! Looks like the underlying issue in #163 is from WhatsHap's use of `pyfaidx` which [still raises that error for gzipped files](https://github.com/mdshw5/pyfaidx/blob/v0.7.2.1/pyfaidx/__init__.py#L437-L442).

**Comment by SamStudio8** [comment]
Thanks! I can confirm I'm seeing WhatsHap 1.7 installed from the Clair3 bioconda package now.
