### ISSUE TITLE
model downloads links not working

### ISSUE THREAD

**Issue by scfurl** [HKU-BAL/Clair3#196]
Hi,

none of the model download links are working.  wonder if the server is down?

<img width="707" alt="image" src="https://user-images.githubusercontent.com/16267955/235944770-ad5f3e16-cab0-4143-9953-81927df02158.png">

**Comment by aquaskyline** [comment]
checked and is working.

**Comment by scfurl** [comment]
Interesting, just tried a different browser and pinged and still no contact.  Any ideas?

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/16267955/235971227-3e1375ad-04e3-4dcb-bf21-2b30fd18678c.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/16267955/235974452-b14dca83-8baa-475a-a6a7-b0932d7e0563.png">

**Comment by aquaskyline** [comment]
Firewall or sth behind? I'd try using my cellphone to tell if I was blocked or not.
On the other hand, please visit a copy of the models at https://drive.google.com/file/d/1LLbPxu8cm0zU0dklHl8FTPdrsPaJPBqM/view?usp=sharing

**Comment by scfurl** [comment]
Thanks
