### ISSUE TITLE
BAM file not found with Singularity

### ISSUE THREAD

**Issue by schipma** [HKU-BAL/Clair3#197]
Hello,

I am running clair3 using a Singularity installation and the software cannot find my BAM file.  I've verified that the path is valid and the BAM file is present.

Here is my command:

singularity exec -B /software:/software /software/clair3/1.0.1_singularity/clair3_v1.0.1.sif /software/clair3/1.0.1_singularity/Clair3/run_clair3.sh  \
--bam_fn=/home/mjs/bams/sample1_sorted.bam  \
--ref_fn=../reference/genome.fa \
--output=/home/mjs/clair \
--threads=1 \
--platform=ont \
--model_path=../r941_prom_sup_g5

Here is the output:

[INFO] CLAIR3 VERSION: v1.0.1
[INFO] BAM FILE PATH: /home/mjs/bams/sample1_sorted.bam
[INFO] REFERENCE FILE PATH: ../reference/genome.fa
[INFO] MODEL PATH: ../r941_prom_sup_g5
[INFO] OUTPUT FOLDER: /home/mjs/clair
[INFO] PLATFORM: ont
[INFO] THREADS: 1
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: /home/mjs/miniconda3/envs/clair3
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] LONGPHASE PATH: EMPTY
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] PHASING PROPORTION: 0.7
[INFO] MINIMUM MQ: 5
[INFO] MINIMUM COVERAGE: 2
[INFO] SNP AF THRESHOLD: 0.08
[INFO] INDEL AF THRESHOLD: 0.15
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: False
[INFO] ENABLE REMOVING INTERMEDIATE FILES: False
[INFO] ENABLE LONGPHASE FOR INTERMEDIATE VCF PHASING: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING WHATSHAP: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING LONGPHASE: False
[INFO] ENABLE HAPLOTAGGING FINAL BAM: False
[INFO] ENABLE LONG INDEL CALLING: False
[INFO] ENABLE C_IMPLEMENT: True

[ERROR] BAM file /home/mjs/bams/sample1_sorted.bam not found

real	0m0.001s
user	0m0.000s
sys	0m0.001s

Thank you.

**Comment by zhengzhenxian** [comment]
Hi, 

You might need to bind all the input and output folders in Singularity using `-B /home/mjs`, like:
```
singularity exec -B /home/mjs /software/clair3/1.0.1_singularity/clair3_v1.0.1.sif /software/clair3/1.0.1_singularity/Clair3/run_clair3.sh
--bam_fn=/home/mjs/bams/sample1_sorted.bam
--ref_fn=../reference/genome.fa
--output=/home/mjs/clair
--threads=1
--platform=ont
--model_path=../r941_prom_sup_g5
```
