### ISSUE TITLE
Conda prefix not found

### ISSUE THREAD

**Issue by nhhaidee** [HKU-BAL/Clair3#199]
Hi @zhengzhenxian  We just ran into problem when running Clair3, we downloaded the `r1041_e82_400bps_sup_g615` model files from Rerio and provided this model for Clair3 but we got error `Conda prefix not found, please activate clair3 conda environment first, model path: /mnt/data6/FLU/nf-flu/clair3/bin/models/r1041_e82_400bps_sup_g615`. We run with docker container, can you advice us on this problem?

Thanks,
Hai

`[INFO] CLAIR3 VERSION: v0.1-r10
[INFO] BAM FILE PATH: /mnt/data6/FLU/work/0e/d71d74763126393c363708386cb7d2/23MB310073.Segment_5_NP.MT467124.bam
[INFO] REFERENCE FILE PATH: /mnt/data6/FLU/work/0e/d71d74763126393c363708386cb7d2/23MB310073.Segment_5_NP.MT467124.reference.fasta
[INFO] MODEL PATH: /mnt/data6/FLU/nf-flu/clair3/bin/models/r1041_e82_400bps_sup_g615
[INFO] OUTPUT FOLDER: /mnt/data6/FLU/work/0e/d71d74763126393c363708386cb7d2/23MB310073.Segment_5_NP.MT467124.clair3
[INFO] PLATFORM: ont
[INFO] THREADS: 2
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: 
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] PHASING PROPORTION: 0.7
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: True
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: True
[INFO] ENABLE INCLUDE ALL CTGS CALLING: True
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: False
[INFO] ENABLE REMOVING INTERMEDIATE FILES: False
[INFO] ENABLE PHASING VCF OUTPUT: False
[INFO] ENABLE LONG INDEL CALLING: True

[31m[ERROR] Conda prefix not found, please activate clair3 conda environment first, model path: /mnt/data6/FLU/nf-flu/clair3/bin/models/r1041_e82_400bps_sup_g615[0m

`

**Comment by zhengzhenxian** [comment]
Hi, @nhhaidee,

It appears that model path is not found in the Docker image. Could you try to mount the model folder first via [docker volumn](https://docs.docker.com/storage/volumes/) like: `docker run -v /mnt/data6/FLU/nf-flu/clair3/bin/models:/mnt/data6/FLU/nf-flu/clair3/bin/models -v /mnt/data6/FLU:/mnt/data6/FLU /opt/bin/run_clair3.sh ...`. 


Please also ensure that the model folder is present in your local directory at `/mnt/data6/FLU/nf-flu/clair3/bin/models/`.
