### ISSUE TITLE
Clair3 doesn't work with hs38DH.fa because HLA contigs contain colons

### ISSUE THREAD

**Issue by ymcki** [HKU-BAL/Clair3#203]
I am running ONT's wf-human-variation nextflow pipeline. I found that it crashes when clair3 processes the HLA contigs in the hs38DH genome. Based on my understanding, the problem seems to be caused by the names of HLA contigs containing colons.

Is there a newer version of clair3 that works with the HLA contigs of hs38DH.fa? 

Error messages:
=============
  export REF_PATH=ref_cache/%2s/%2s/%s
  python $(which clair3.py) CallVariantsFromCffi             --chkpnt_fn model/pileup             --bam_fn pod5.pass.cram             --call_fn pileup_HLA-DRB1*10:01:01_1.vcf             --ref_fn hs38DH.fa             --ctgName HLA-DRB1*10:01:01             --chunk_id 1             --chunk_num 1             --platform ont             --fast_mode False             --snp_min_af 0.08             --indel_min_af 0.15             --minMQ 5             --minCoverage 2             --call_snp_only False             --gvcf false             --temp_file_dir gvcf_tmp_path             --pileup

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts
  Calling variants ...
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/clair3.py", line 105, in <module>
      main()
    File "/home/epi2melabs/conda/bin/clair3.py", line 99, in main
      submodule.main()
    File "/home/epi2melabs/conda/bin/clair3/CallVariantsFromCffi.py", line 351, in main
      Run(args)
    File "/home/epi2melabs/conda/bin/clair3/CallVariantsFromCffi.py", line 62, in Run
      call_variants_from_cffi(args=args, output_config=output_config, output_utilities=output_utilities)
    File "/home/epi2melabs/conda/bin/clair3/CallVariantsFromCffi.py", line 156, in call_variants_from_cffi
      batch_output_method(position, alt_info_list, Y, output_config, output_utilities)
    File "/home/epi2melabs/conda/bin/clair3/CallVariants.py", line 1092, in batch_output
      output_with(
    File "/home/epi2melabs/conda/bin/clair3/CallVariants.py", line 1119, in output_with
      chromosome, position, reference_sequence = chr_pos_seq.rstrip().split(':')
  ValueError: too many values to unpack (expected 3)
==============

**Comment by aquaskyline** [comment]
A fix is scheduled in the next version.

**Comment by zhengzhenxian** [comment]
@ymcki, the colons issue is fixed in v1.0.3. 

As you are using the ONT NextFlow pipeline, you might wait for an updated version soon.
