### ISSUE TITLE
Issue with phasing on r10 ONT model

### ISSUE THREAD

**Issue by santoshe1** [HKU-BAL/Clair3#204]
Hello Clair3 Team,

I have an issue running Clair3 with `"r1041_e82_400bps_sup_v400"` ONT model with phasing options. The results don't provide variant calls of chromosomes [chr1 - chr22] and only have results for chrM. I use the options `--enable_phasing` and `--longphase_for_phasing` parameters. 

When I turn off these options, the results are normal. Could you check if there is any bug phasing with the r10 sup model?

Best Regards,
Santosh

**Comment by aquaskyline** [comment]
`--enable_phasing` enables whatshap for phasing as the last step after Clair3 has called some variants. Can you see any whatshap warning or error messages in your log?

**Comment by santoshe1** [comment]
hello @aquaskyline,

I see few errors like these on few chromosomes:

`ERROR: whatshap error: Read name 'e86521ac-52ea-5cfe-87d0-1dcf41bc5047' occurs more than twice in the input file`

Could this be a reason to skip the results for chr1-22?

**Comment by aquaskyline** [comment]
That's Whatshap complaining there are repetitive read names in your BAM input. There might be Whatshap jobs that have not done running, thus Clair3 was unable to collect the results generated by Whatshap.

**Comment by aquaskyline** [comment]
You might want to check for repetitive read names in your input.
