### ISSUE TITLE
Odd ref base?

### ISSUE THREAD

**Issue by Phillip-a-richmond** [HKU-BAL/Clair3#206]
Hello,

Wondering what this means in the Clair3 output?

```
chr3	16902879	.	TGTGB	T	18	PASS	F	GT:GQ:DP:AF	0/1:18:48:0.3125
```

This is a single sample WGS analysis.

Thanks,
Phil

**Comment by aquaskyline** [comment]
It's an [IUPAC](https://en.wikipedia.org/wiki/International_Union_of_Pure_and_Applied_Chemistry) degenerate base symbol that is given in your reference fasta.
