### ISSUE TITLE
a few queries

### ISSUE THREAD

**Issue by prasundutta87** [HKU-BAL/Clair3#207]
Hi,

 I have 2 questions-

1) In the software description, it is mentioned that v1.0.4 was released on Jul 11th. However, github only shows v1.0.3. Where can I get v1.0.4?

2) Is the new model available for variant calling for the R10.4.1 flowcell?

Regards,
Prasun

**Comment by zhengzhenxian** [comment]
Hi Prasun,

1. The package release updated to v1.0.4 on the GitHub page now, and please follow the [installation](https://github.com/HKU-BAL/Clair3#installation) to run Clair3 accordingly.

2. Yes, Clair3 R10.4.1 models are provided in ONT [Rerio](https://github.com/nanoporetech/rerio#clair3-models), pls check [here](https://github.com/HKU-BAL/Clair3#ont-provided-models) for usage.

Zhenxian

**Comment by prasundutta87** [comment]
Hi Zhenxian,

Thanks so much for the quick replies. I actually used bioconda for installation and I saw that v1.0.4 has been now updated there as well. Thanks for sending other links for usage as well. Much appreciated!

Regards,
Prasun
