### ISSUE TITLE
Clair3 1.0.4 from bioconda does not write out INFO/END header

### ISSUE THREAD

**Issue by holtgrewe** [HKU-BAL/Clair3#209]
The `clair3` package in version 1.0.4 from bioconda does not write tout the header from `INFO/END`. Consequently, gCNV merging/calling using GATK fails.

**Comment by holtgrewe** [comment]
The same appears to be true for `MIN_DP`.

**Comment by zhengzhenxian** [comment]
@holtgrewe,

Thanks for reporting the issue. We have updated the [bioconda package](https://anaconda.org/bioconda/clair3/files) with the issue fixed, pls try to re-install the conda environment.
