### ISSUE TITLE
MAF minor variants

### ISSUE THREAD

**Issue by Axze-rgb** [HKU-BAL/Clair3#210]
Hello

I am working on a clonal organism but we believe more and more it might not be so clonal. We have HiFi data and I want to use them to detect MAF. Is it possible with Clair3 to detect that? Do you think the models are capable of that? 

Thank you 

Cheers

**Comment by aquaskyline** [comment]
You can cuz Clair3 allows AF down to 0.15, but Clair3 has a strong diploid assumption of the input in its design, so theoretically, not recommended.

**Comment by Axze-rgb** [comment]
That's what I feared. Thanks!
