### ISSUE TITLE
Question on snp_min_af

### ISSUE THREAD

**Issue by Axze-rgb** [HKU-BAL/Clair3#212]
is it really 0.08 for all the technologies? 
So, whatever Clair3 is fed Pacbio, ont or ilm it can detect SNP present in 8% of the reads? I would have assumed that the detection would work better with long reads and therefore, the af  would be lower. Can you tell me where I am wrong? 

Sorry for the many questions I must account for 30% of the issues here ^^' 

Alex

**Comment by Axze-rgb** [comment]
Thanks, following on my question and referencing this sub
https://github.com/google/deepvariant/issues/682

how to grab the variants Clair3 ultimately rejects, i.e with GT ./. or 0.0 BUT that have minor allele frequencies? Deepvaraint call that VAF, you AF it seems.

But, all the variant that have the FORMAT AF field have 0/1, which means this code always returns an empty file

` $ bcftools query -f '[%GT,%GQ,%AF\n]' biallelic.vcf | grep './.|0/0' > gq_vaf.csv
`
For the record, it's not a competition with deepvariant, I am just looking for something in a "clonal" organisms. 

Thanks

**Comment by aquaskyline** [comment]
Are you looking for this option `--print_ref_calls`? Using this option together with `--vcf_fn=FILE` shows the results of all positions given in FILE.

**Comment by Axze-rgb** [comment]
> Are you looking for this option `--print_ref_calls`? Using this option together with `--vcf_fn=FILE` shows the results of all positions given in FILE.

Ah, I am gonna try that :) I think your default min-af is already amazingly slow enough. 
Thank you :)

**Comment by aquaskyline** [comment]
Do you mean 'low enough' or 'slow enough'? If slow, I can use some more details of your input to see what else my team can do.

**Comment by Axze-rgb** [comment]
It was low enough, sorry, autocorrect issue. I am amazed at the speed of your tool. I use it on a consumer grade laptop, though a high-end one that I customised a bit. But still, I am not using any cluster.

**Comment by aquaskyline** [comment]
Ah, thanks. And just so you know that we usually suggest Clair3 users also run DeepVariants if computational resources allow, and then combine the two results.

**Comment by Axze-rgb** [comment]
How do you combine them? Practtically I mean

**Comment by Axze-rgb** [comment]
> > Are you looking for this option `--print_ref_calls`? Using this option together with `--vcf_fn=FILE` shows the results of all positions given in FILE.
> 
> Ah, I am gonna try that :) I think your default min-af is already amazingly low enough. Thank you :)

If I understand well, I must provide a vcf file with all the positions?

`Candidate sites VCF file input, variants will only be called at the sites in the VCF file if provided`

So I must provide a file with a line for each genomic position ? O_O

**Comment by aquaskyline** [comment]
> How do you combine them? Practically I mean

That very much depends on your project. It can be as easy as "Clair3 AND DV" for maximum accuracy, or "Clair3 OR DV" for maximum sensitivity.

**Comment by aquaskyline** [comment]
> EDIT: clearing the message
> 
> I don't understand the point of
> 
> > --print_ref_calls? Using this option together with --vcf_fn=FILE
> 
> while there is the option --gvcf , isn't the gvcf by default printing all ref calls? and also gives the different candidate alleles (even if in the end they were rejected?

`--print_ref_calls` + `-vcf_fn` is genotyping mode. DV shows the alternative allele with the highest AF support even a 0/0 is called. Clair3 doesn't do it. The feature is not hard to be added to Clair3, but I think it might lead to more confusion than value for relatively noisy data.

**Comment by Axze-rgb** [comment]
> 

I tend to agree, now that I have tried to use that with other callers.
