### ISSUE TITLE
Inconsistency between Clair3 output and IGV 

### ISSUE THREAD

**Issue by keremozdel** [HKU-BAL/Clair3#215]
Hello,
I am encountering a problem while working with nanopore reads. Specifically, I have observed differences in base counts between the VCF output and the IGV image for a particular variant. Here are the details of the variant in question:

`chr12 | 102852875 | . | C | T | 13.06 | PASS | P | GT:GQ:DP:AD:AF:PL | 1/1:13:95:37,48:0.5053:58,14,0`

The total depth at this position is 95, with an observed allele frequency of 48 for the ALT allele and 37 for the REF allele. However, the results differ significantly in the IGV image, as shown below:

![igv_barcode24](https://github.com/HKU-BAL/Clair3/assets/141839630/02987517-9cf0-4ed9-bbec-a171891194b3)

While the ALT allele counts are identical between the VCF output and IGV, the REF allele count is much lower in the IGV image compared to the VCF output. I am curious about the factors that could lead to this type of inconsistency.

Here is the code I am using for the analysis:

`run_clair3.sh --gvcf --min_coverage=2 --platform=ont --snp_min_af=0.05 --indel_min_af=0.05 --enable_phasing  --enable_long_indel --model_path=./path/r1041_e82_400bps_fast_g632 --bam_fn=input.bam --bed_fn=input.bed --ref_fn=reference.fasta --output=output`

Thank you in advance!

**Comment by zhengzhenxian** [comment]
Hi,

In our "DP" tag calculation, we computed the read depth by considering reference bases, alternative bases, and deletion bases while excluding secondary alignments, supplementary alignments, and reads with a mapping quality below 5. Consequently, in your case, you may observe that the DP represents the combined count of reference bases, alternative bases, and deletions, and few of the reads were filtered.

**Comment by keremozdel** [comment]
Thank you for your answer.

Yes, it explains the DP case. But, I still do not understand why REF allele, which corresponds to C in vcf file does not equal to C count in bam file.I don't think this is the issue, but does Clair3 include deletions while computing the allelic depth for the reference allele in the first value of the AD tag?

**Comment by aquaskyline** [comment]
@keremozdel Thank you for spotting the AD counting bug! We will fix the bug and release an update by next week.

**Comment by zhengzhenxian** [comment]
Hi @keremozdel,

The reference count issue in `AD` tag is fixed. The reference count now only reports the counting of the reference base of the record, excluding any mismatches or indels. Please try the updated docker image or the updated [bioconda package](https://anaconda.org/bioconda/clair3/files).

**Comment by keremozdel** [comment]
Hi,

Thank you. It seems fixed now.
