### ISSUE TITLE
Numpy error in Bioconda install

### ISSUE THREAD

**Issue by fidibidi** [HKU-BAL/Clair3#218]
Hello, 

Installed using WSL on windows 10 and using the bioconda method. 

Running I appear to get this warning/error:

/home/ont/miniconda3/envs/clair3/lib/python3.9/site-packages/numpy/core/getlimits.py:542: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)

My final output still has results that seem accurate so really just curious whether this is not a serious issue. 

Wasn't able to find much about what to do. 

Thanks!

**Comment by aquaskyline** [comment]
We share the same curiosity. WSL sometimes produces strange prompts that is not commonly seen in Linux. Please double check your results, and feel safe to ignore the warning if your results look alright.
