### ISSUE TITLE
link in docker install broken

### ISSUE THREAD

**Issue by fidibidi** [HKU-BAL/Clair3#22]
Hi all!

Minor bug, not related to claire3. 
But the installation instruction feature a broken link:

`
Installation
Option 1. Docker pre-built image
A pre-built docker image is available here. With it you can run Clair3 using a single command.
`

I had to manually search for the image, which I think is this? https://hub.docker.com/r/hkubal/clair3

Btw, is there a preferred method of installation? or should all function pretty much the same. 

THanks!

**Comment by aquaskyline** [comment]
Link fixed. All functions are identical between installation options. When we update, we update the image in all installation options.

**Comment by fidibidi** [comment]
Thanks!

I'm really looking forward to using your software, I'm pretty tired of the headache that has been trying to get medaka to work...
