### ISSUE TITLE
[WARNING] Threads setting exceeds maximum available threads 1, set threads=1

### ISSUE THREAD

**Issue by darbrob** [HKU-BAL/Clair3#221]
I'm running Clair3 on a cluster and my node has 80 cores.  I'm not sure why I'm getting this error about the maximum available threads being just 1.  I also am not very clear on what it means in the documentation when it says "Max #threads to be used. The full genome will be divided into small chunks for parallel processing. Each chunk will use 4 threads. The #chunks being processed simultaneously is ceil(#threads/4)*3. 3 is the overloading factor."  What does "overloading factor" mean?  Do I need to change the default chunk size to match the number of threads I am specifying?  

Thanks in advance for your guidance.

**Comment by aquaskyline** [comment]
Try with default parameters first and if error comes up, please share the log.

**Comment by adbeggs** [comment]
Yes, I have the same problem in a slurm HPC environment. I am presenting 32 cores to the process but get:

[INFO] CLAIR3 VERSION: v0.1-r10
[INFO] BAM FILE PATH: /rds/projects/b/beggsa-clinicalnanopore/adb/BRCA_Hereditary_Adaptive_240424/BRCA17_BRCA19/20240424_1108_3H_PAW21722_ab86f461/BRCA17/reclair/BRCA17.sorted.bam
[INFO] REFERENCE FILE PATH: /rds/projects/b/beggsa-clinicalnanopore/GRCh38/genome.fa
[INFO] MODEL PATH: /opt/models/r941_prom_hac_g360+g422
[INFO] OUTPUT FOLDER: /rds/projects/b/beggsa-clinicalnanopore/adb/BRCA_Hereditary_Adaptive_240424/BRCA17_BRCA19/20240424_1108_3H_PAW21722_ab86f461/BRCA17/reclair/clair_fast
[INFO] PLATFORM: ont
[INFO] THREADS: 4
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: /rds/bear-apps/2022a/EL8-cas/software/Miniconda3/22.11.1-1
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] PHASING PROPORTION: 0.7
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: False
[INFO] ENABLE REMOVING INTERMEDIATE FILES: False
[INFO] ENABLE PHASING VCF OUTPUT: False
[INFO] ENABLE LONG INDEL CALLING: False

[WARNING] Threads setting exceeds maximum available threads 1, set threads=1
+ /opt/bin/scripts/clair3.sh --bam_fn /rds/projects/b/beggsa-clinicalnanopore/adb/BRCA_Hereditary_Adaptive_240424/BRCA17_BRCA19/20240424_1108_3H_PAW21722_ab86f461/BRCA17/reclair/BRCA17.sorted.bam --ref_fn /rds/projects/b/beggsa-clinicalnanopore/GRCh38/genome.fa --threads 1 --model_path /opt/models/r941_prom_hac_g360+g422 --platform ont --output /rds/projects/b/beggsa-clinicalnanopore/adb/BRCA_Hereditary_Adaptive_240424/BRCA17_BRCA19/20240424_1108_3H_PAW21722_ab86f461/BRCA17/reclair/clair_fast --bed_fn=EMPTY --vcf_fn=EMPTY --ctg_name=EMPTY --sample_name=SAMPLE --chunk_num=0 --chunk_size=5000000 --samtools=samtools --python=python3 --pypy=pypy3 --parallel=parallel --whatshap=whatshap --qual=2 --var_pct_full=0.7 --ref_pct_full=0.1 --var_pct_phasing=0.7 --snp_min_af=0 --indel_min_af=0 --pileup_only=False --gvcf=False --fast_mode=False --call_snp_only=False --print_ref_calls=False --haploid_precise=False --haploid_sensitive=False --include_all_ctgs=False --no_phasing_for_fa=False --pileup_model_prefix=pileup --fa_model_prefix=full_alignment --remove_intermediate_dir=False --enable_phasing=False --enable_long_indel=False
[INFO] Check environment variables

**Comment by aquaskyline** [comment]
#245 might help. When Clair3 shows `Threads setting exceeds maximum available threads 1`. It means running `nproc` in your computing node (not the job submission node) returns 1 as the maximum number of threads exposed to Clair3.
