### ISSUE TITLE
The output DP is lower than the mapping coverage

### ISSUE THREAD

**Issue by ErminZ** [HKU-BAL/Clair3#222]
Hello, 

Thank you for developing the SNP caller Cliar3! I am using it for a PCR amplicon sample. I have about 380K reads in the sample, and there is an SNP in position 3,213 shown using IGV. 

Total     count: 382,962 on position 3213
A : 441 (0%, 365+, 76- )
C : 380655 (99%, 160821+,     219834- )
G : 486 (0%, 128+, 358- )
T : 1380 (0%, 336+, 1044- )
N     : 0

However, I encountered two challenges using clair3v0.1-r12. 

1. The pileup model has 3 SNPs detected, but the full alignment failed leading to no SNPs detected. Would you explain why the full-alignment model cannot find any variants? 
Here are the results using `--include_all_ctgs --chunk_size=5000 --pileup_only --qual=0 --min_mq=1 --enable_long_indel` 

```
POS        ID            REF        ALT        QUAL    FILTER  INFO      FORMAT              SAMPLE
2196      .               T              .               15.09    RefCall  P             GT:GQ:DP:AD:AF             0/0:15:8584:5434:0.6330
2749      .               C             .               26.66    RefCall  P             GT:GQ:DP:AD:AF             0/0:26:8787:5778:0.6576
3213      .               T              C             24.36    PASS      P             GT:GQ:DP:AD:AF             1/1:24:8709:16,8599:0.9874
```

2. The coverage DP is lower than the coverage depth. If it is because of the downsampling, is there a way to turn the downsampling off? Since we want more accurate allele frequency by calculating the whole reads.

Please let me know if you have any questions. 

Thanks, 
Ermin

**Comment by aquaskyline** [comment]
1. Full-alignment can't handle coverage larger than 89. For amplicon calling, please always use the results from the pileup-calling model.
2. Clair3 is showing the full coverage, but with i. low BQ reads filtered, ii. low MQ reads filtered, and iii. secondary alignments filtered.

**Comment by ErminZ** [comment]
Thank you for your reply! I will only use pileup for amplicon samples. 

Do you mean the BQ is base quality or the average read quality used by guppy filtering parameter? I am using Guppy super-accurate base-calling, so the read quality is higher than 10. Also, my input BAM file is filtered out secondary and supplementary alignments (using -F 2308) already. 

About the coverage, for example, on position 3213, Total count is 382,962 on IGV, where Clair3 detected a SNP with GT:GQ:**DP**:AD:AF (1/1:24:**8709**:16,8599:0.9874). Would you explain the difference between 382,962 on IGV and 8709 called by Clairs3 on this position? 

I have another follow-up question about the DP and AD, would you explain what is the difference between the DP and the sum of AD. Like what would the 2k read be? 8446-(1442+4542)=2k reads. Since secondary and supplementary alignments are filtered out, and most reads MQ are 60 or 59. 

```
chr14 | 22,547,532 | . | T | TA | 11.35 | PASS | P | GT:GQ:DP:AD:AF | 1/1:11:8446:1427,4542:0.5378
```

Let me know if you have any questions. We appreciate your answer and help! 

Thanks, 
Ermin

**Comment by zhengzhenxian** [comment]
Hi, @ErminZ

BQ is the base quality. The read coverage is capped at ~8000x mainly due to the maximum depth setting in samtools mpileup submodule, which we use to parser the alignment. You might refer to the -d option in samtools manual [here](http://www.htslib.org/doc/samtools-mpileup.html). We tried to disable it but with no luck. We might try to add a post-processing step for extremely high-coverage data.

Regarding the AD, it includes counts for alleles other than the reference and the called alternative base. This can encompass other mismatches and indels.

**Comment by ErminZ** [comment]
Thank you so much for your reply! I noticed samtools version older than v1.6 gave different coverage using the `samtools depth`, and the old version samtools max about 8k. But I checked my clair3 docker that has the newer samtools version.

```
Old samtools
ref 1     8000
ref 2     8001
ref 3     8002
ref 4     8003
ref 5     8004
...
ref 3213 8643
 
Samtools version 1.16.1
ref 1    295377
ref 2    302349
ref 3    305483
ref 4    308038
ref 5    315513
...
ref 3213 382962
```
