### ISSUE TITLE
run terminates, core files produced after 4 min

### ISSUE THREAD

**Issue by jpdna** [HKU-BAL/Clair3#223]
I'm running v0.1-r11 to be compatible with an existing dataset.  I used the 
https://github.com/HKU-BAL/Clair3/tree/v0.1-r11.1#option-4-build-an-anaconda-virtual-environment
install process, which seemed successful.
However my run, which takes several hour on the current 1.2 version, fails after about 4 minutes on v0.1-r11, and produces numerous core.XXXX files in the output dir.
The only error reported in the log output is:
`ESC[93m[WARNING] No vcf file found with  .........  output empty vcf fileESC[0m `

I cannot easily use the Singularity/Docker option as need sysadmin update our Singularity version, currently it has a permissions error inside container as its running as my user not root.

**Comment by aquaskyline** [comment]
Probably wrong or incompatible version of libraries in your running environment. There is no easy way for us to tell where exactly the problem is. Sometimes, installing conda from scratch solves the problem, but we'd suggest users to use Singularity to save from hectics.
