### ISSUE TITLE
Question Using Clair3 in Plasmodium

### ISSUE THREAD

**Issue by sachiwije** [HKU-BAL/Clair3#224]
Hi,

Just have a question about running Clair3 on _Plasmodium_ data. Is it possible to use exiting Clair3 models that are trained on Human data or should I consider training a new model. Are there any other recommendations I should consider?

Thanks,
Sach

**Comment by aquaskyline** [comment]
If you are handling haploid cells, use the haploid mode in Clair3.

**Comment by JesseRop** [comment]
Gald to see that this great tool can be applied to plasmodium. Does the haploid mode still apply in case I have more than 1 strain/genotype in a sample?

**Comment by aquaskyline** [comment]
Yes if there are multiple strains but each of them are still haplotype.-------- 原始邮件 --------发件人： JC Rop ***@***.***>日期： 2024年8月19日周一03:55收件人： HKU-BAL/Clair3 ***@***.***>抄送： Ruibang Luo ***@***.***>, State change ***@***.***>主    题： Re: [HKU-BAL/Clair3] Question Using Clair3 in Plasmodium (Issue #224)
Gald to see that this great tool can be applied to plasmodium. Does the haploid mode still apply in case I have more than 1 strain/genotype in a sample?

**Comment by JesseRop** [comment]
Thanks for the reply! I'll give it a go
