### ISSUE TITLE
Can I concatenate ONT reads base-called with different models for SNP calling?

### ISSUE THREAD

**Issue by weishwu** [HKU-BAL/Clair3#226]
I have several runs of ONT data that were sequenced with a long time in between, so they were base-called with different models. I'd like to concatenate the reads to get a higher depth for SNP and methylation calling. Is this feasible? How should I deal with the difference of the models?
If I redo the base calling with the concatenated fast5 files using the latest model, will there be any incompatibility issue between the old ONT and the new model?

**Comment by aquaskyline** [comment]
You can't mix R9 and R10 data. For either R9 or R10 data, they can be combined, but before variant calling, I'd suggest to basecall all fast5 using the latest basecaller.

**Comment by weishwu** [comment]
Thanks!
