### ISSUE TITLE
Issue with conda installation

### ISSUE THREAD

**Issue by martabaragli** [HKU-BAL/Clair3#227]
Hi,
I am trying to install clair3 on a server, since I don't have root's rights and cannot use Docker or Singularity, but I get this error.

`UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.28=0
  - clair3 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.28`

I don't understand why glibc 2.28 version is not compatible, since a version >=2.17 is needed.
Do you have any guess how to solve this?
Thank you

**Comment by aquaskyline** [comment]
please try singularily, it requires no root
