### ISSUE TITLE
vcf pileup file not created

### ISSUE THREAD

**Issue by rongiergaetan** [HKU-BAL/Clair3#228]
I launch Clair3 like this:

./run_clair3.sh --bam_fn=Bam/consensus_sample_sorted.bam --ref_fn=ref/ref_seq.fasta --threads=8 --platform="ont" --model_path=models/r941_prom_sup_g5014 --output=output/ --include_all_ctgs --chunk_size=2000

The run stop during 1/7  Call variants using pileup model Because he cannot found the file: output/tmp/pileup_output/pileup_SP9D_LR_F2/R2_1.vcf

I join the log file. 
[run_clair3.log](https://github.com/HKU-BAL/Clair3/files/12584673/run_clair3.log)

**Comment by zhengzhenxian** [comment]
@rongiergaetan,

`FileNotFoundError: [Errno 2] No such file or directory: '/Clair3/output_clair3/tmp/pileup_output/pileup_SP9D_LR_F2/R2_3.vcf'"`

It appears that the output directory `/Clair3/output_clair3` is not writable. Please consider using a different output directory that allows for write access.
