### ISSUE TITLE
Variants not reported in merge_output. Why?

### ISSUE THREAD

**Issue by SkabbiVML** [HKU-BAL/Clair3#229]
Hello developers!

I'm running Clair3 on WGS data from tumor biopsies. I'm a but confused to how variants are reported in the merge_output.vcf file. In the example below, two variants can be seen with AF of around 35 %.  Both are reported in the pileup.vcf file, not filtered out. Both appear in the full_alignment.vcf file but are filtered out as - RefCall. Neither appears in the merge_output file.

Why are they filtered from the full alignment if the AF is 35%? Why are they not included in the merge_output file? Clair3 was run with a reference genome and clair3 model, everything else was default. Are there settings that I need set to get these reported? Should I perhaps only be looking at the pileup file and ignore the full_alignment?

Both variants have been confirmed by illumina sequencing

![image](https://github.com/HKU-BAL/Clair3/assets/61014551/cacebff5-def3-4be2-920a-093e6219b1aa)

Thanks for you help

Skabbi

**Comment by aquaskyline** [comment]
Is this a known true variant? The reads that have C on the left are all without G on the right. It is not 100% but can be a strong indication of false positive variants.

**Comment by SkabbiVML** [comment]
Hi @aquaskyline 

Both of these variants have been previously reported in this sample by illumina. The variants separate completely by phasing. 

![image](https://github.com/HKU-BAL/Clair3/assets/61014551/9da3380a-8f81-4698-a16c-3904f5c3ee3e)
