### ISSUE TITLE
Issue with Tensorflow in Clair3 v1.0.4 install with Conda env: import tensorflow as tf ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by nbertholdpgc** [HKU-BAL/Clair3#230]
Hi all,
I'll just caveat this by saying I'm still fairly new to bioinformatics and coding so it's likely a simple fix on my end!
Briefly, I am trying to perform some SV genotyping of human DNA samples sequenced with nanopore adaptive sampling. I downloaded Clair3 following the conda install and env option. The script I'm using is as follows:
```
for num in 0; 
do 
	if [[ -s $DataOut/Sample${num}Clair3/ ]] || [[ -s $TmpWD/Sample${num}Clair3/ ]]
	then
		echo "Clair3 ${num} is already present"
		cp -rn $DataOut/Sample${num}Clair3 $TmpWD
		ls $TmpWD
	else
		if [[ ! -s $DataOut/Sample${num}Clair3/ ]] && [[ ! -s $TmpWD/Sample${num}Clair3/ ]]
		then
			export PATH="$PATH:/dir/to/usr/Conda/envs/clair3/lib/python3.9/site-packages/"
			echo "must make ${num} Clair3" 
			mkdir $TmpWD/Sample${num}Clair3
			cd /group/shs001/nberthold/Conda/envs/clair3/Clair3
			INPUT_DIR="$TmpWD"        
			OUTPUT_DIR="$TmpWD/Sample${num}Clair3" 
			THREADS="8" 
			MODEL_NAME="r941_prom_sup_g5014"
			source /path/to/python/anaconda3/etc/profile.d/conda.sh
			conda activate clair3
			./run_clair3.sh \
			  --bam_fn=${INPUT_DIR}/S${num}DoradoWF-O_srtd.bam \
			  --ref_fn=$Ref \
			  --threads=${THREADS} \
			  --platform="ont" \
			  --model_path="/dir/to/usr/Conda/envs/clair3/Clair3/models/${MODEL_NAME}" \
			  --output=${OUTPUT_DIR} \
			  --sample_name="Sample${num}" \
			  --bed_fn=$Targ.bed \
			  --include_all_ctgs \
			  --whatshap=/home/usr/.local/bin/whatshap \
			  --use_whatshap_for_final_output_phasing \
			  --use_whatshap_for_final_output_haplotagging 
		fi 
	fi 
```
This outputs the following error message;

> Traceback (most recent call last):
>   File "/dir/to/usr/Conda/envs/clair3/Clair3/scripts/../clair3.py", line 105, in <module>
>     main()
>   File "/dir/to/usr/Conda/envs/clair3/Clair3/scripts/../clair3.py", line 92, in main
>     submodule = import_module("%s.%s" % (directory, submodule_name))
>   File "/server/path/to/python/python/3.9.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/dir/to/usr/Conda/envs/clair3/Clair3/clair3/CallVariantsFromCffi.py", line 3, in <module>
>     import tensorflow as tf
> ModuleNotFoundError: No module named 'tensorflow'

I tried it first without the export path or cd ing to the Clair3 env directory, and it didnt work either. 
Is it something to do potentially with me working within an organisation server, and conflicts are arising? I don't have root, so I also tried singularity but that didn't want to work either!

Thanks so much in advance!
Natasha

**Comment by zhengzhenxian** [comment]
@nbertholdpgc 

It seems the activation of the clair3 conda environment was not successful. You can try directly sourcing the absolute path of the Clair3 conda environment by using the command `source activate /dir/to/usr/Conda/envs/clair3`, and find if you could find TensorFlow package.
