### ISSUE TITLE
Unnecessary warning when phasing is disabled

### ISSUE THREAD

**Issue by mbhall88** [HKU-BAL/Clair3#231]
https://github.com/HKU-BAL/Clair3/blob/5708e725c31c208c97c00f8803654381aec1bf7e/preprocess/CheckEnvs.py#L473

Even when I use the `--no_phasing_for_fa` flag I still get this warning message. Might be good to do a check to see if that option has already been provided before warning?

**Comment by aquaskyline** [comment]
fixed in v1.0.5
