### ISSUE TITLE
Consensus sequence from Clair3 output

### ISSUE THREAD

**Issue by gchevignon** [HKU-BAL/Clair3#232]
Hello guys,

Probably a dumb question sorry for that ...

Can anyone explain why the tools (Clair3) advised by Nanopore (from the Medaka git page and implemented in epi2me) for diploid polishing do not output fasta consensus sequence as Medaka do ?

So the next question is: what is the best way to accurately get fasta consensus from the vcf file produced by clair3 ?

Nothing better than this ? : cat reference.fa | bcftools consensus calls.vcf.gz > consensus.fa

Maybe this should appear in the manual of Clair3.

Thanks a lot for your help !

**Comment by aquaskyline** [comment]
`bcftools consensus` is the way to go.
