### ISSUE TITLE
Format error, unexpected "N" at line 1

### ISSUE THREAD

**Issue by LauraSkak** [HKU-BAL/Clair3#233]
I can for the life of me not figure out what is going wrong... i'm variant calling a bam-file produced by dorado aligner with the T2T v2.0 reference, but when i run the program it gives many many lines of this;

Calling variants ...
[E::fai_build_core] Format error, unexpected "N" at line 1

In the end it gives this error;

No vcf file found, output empty vcf file

The bamfile has tags for methylation... idk if that makes any difference maybe?

**Comment by zhengzhenxian** [comment]
Hi, @LauraSkak,

It seems a reference index issue, could you please try to re-index the reference file and see if the issue persists?
