### ISSUE TITLE
Unable to Lower Mapping Quality Filter

### ISSUE THREAD

**Issue by mproberts99** [HKU-BAL/Clair3#235]
Hello,
I am running into an issue where I cannot set the mapping quality filter to be less than 5. This is necessary for us as we have amplicon sequencing reads that have large structural variants and the mapping quality tends to be equal to 1. Whenever I try to set --min_mq=1 I get errors:

[WARNING] Invalid minimum mapping quality input --min_mq>=5 

I dug into the code, and the parameter is currently restricted to >=5:
if [[ ! ${MIN_MQ} =~ ^[\-0-9]+$ ]] || (( ${MIN_MQ} < 5)); then echo -e "${WARNING} Invalid minimum mapping quality input --min_mq>=5 ${NC}"; MIN_MQ=5; fi

Can this be modified to allow less than 5 for the filter?

Thank you!

**Comment by aquaskyline** [comment]
Yes. You can comment or remove that line of code. But please verify the results after relieving the MQ requirement. If it's not because of amplicon sequencing, a large portion of reads with MQ < 5 do not belong to where they were aligned.
