### ISSUE TITLE
do different aligner affect NGS-based SNP calling?

### ISSUE THREAD

**Issue by tinyfallen** [HKU-BAL/Clair3#237]
Hi dear developer, I would like to know whether it would affect the performance using bowtie2 instead of bwa-mem for NGS reads, thanks a lot!

**Comment by aquaskyline** [comment]
Different aligners perform differently, so, yes.

**Comment by tinyfallen** [comment]
已收到您发送的邮件！

**Comment by aquaskyline** [comment]
Both bwa-mem and bowtie2 are top-notch short read aligners. Clair3 has no preference. One needs to decide empirically which aligner to use for their own setup.

**Comment by tinyfallen** [comment]
I see. Thanks a lot!
