### ISSUE TITLE
TBI errors; support for CSI?

### ISSUE THREAD

**Issue by bcantarel** [HKU-BAL/Clair3#239]
I am trying to use clair3 on a marsupial genome (has extra long chrs) and while clair3 does take cram format, I am still getting an error for TBI error which results in the tool failing and not producing final results.

[E::hts_idx_check_range] Region 748919259..748919260 cannot be stored in a tbi index. Try using a csi index
tbx_index_build failed: /data/temp/./tmp/phase_output/phase_vcf/phased_chr1.vcf.gz
[E::hts_idx_check_range] Region 665926387..665926388 cannot be stored in a tbi index. Try using a csi index
tbx_index_build failed: /data/temp/./tmp/phase_output/phase_vcf/phased_chr2.vcf.gz
[E::hts_idx_check_range] Region 544689956..544689957 cannot be stored in a tbi index. Try using a csi index
tbx_index_build failed: /data/temp/./tmp/phase_output/phase_vcf/phased_chr3.vcf.gz

**Comment by zhengzhenxian** [comment]
Hi @bcantarel,

It appears that the `tabix` cannot index the intermediate phasing VCF file, not sure why the VCF index is relevant to BAM csi indexing.  

Could you send the logs `${OUPUT_DIR}/run_clair3.log` and `${OUPUT_DIR}/log` to my email [zxzheng@cs.hku.hk](mailto:zxzheng@cs.hku.hk) for us to pinpoint the indexing issue?

**Comment by bcantarel** [comment]
Logs sent.

**Comment by zhengzhenxian** [comment]
@bcantarel,

Thank you for providing the log. We tested the software on our local data but were unable to replicate the indexing error. We now skip the VCF indexing and pls kindly re-pull the latest docker image(you might need to remove your local docker image if necessary). The calling result will remain unchanged. Please let us know if the issue persists with your data, thanks.
