### ISSUE TITLE
SNP missing

### ISSUE THREAD

**Issue by HJArdin** [HKU-BAL/Clair3#240]
Hello,
I'm testing Clair3 to identify drugs resistance mutation and some snp are not found even if they are in .bam file and can be see on IGV.
![image](https://github.com/HKU-BAL/Clair3/assets/100346160/473a72f2-e39f-48c5-b59d-ac23348ea356)
![image](https://github.com/HKU-BAL/Clair3/assets/100346160/5ba45186-d9c2-495a-91f8-e5ca1a9f10a3)
 Other snp with less coverage/frequence are detect.
Here is the command I used : 
```
run_clair3.sh -b 50E150E2_MixA1.trimmed.rg.sorted.bam -f ./primer-schemes/custom_CMV/V8/custom_CMV.reference.fasta -m clair3_models/r941_prom_hac_g360+g422/ --include_all_ctgs -t 25 --snp_min_af=0.1 --indel_min_af=0.15 --haploid_sensitive -p ont -o .
```
Some idea why I can't find this two snp ?

**Comment by aquaskyline** [comment]
If you are dealing with amplicon data, please try setting --var_pct_full, --ref_pct_full and --var_pct_phasing to 1.

**Comment by HJArdin** [comment]
Thanks you, it looks like it works for the second one but the first is still not in VCF
