### ISSUE TITLE
Request to make the samtools mpileup --max-depth variable user defined

### ISSUE THREAD

**Issue by mbdabrowska1** [HKU-BAL/Clair3#242]
I was wondering if it was possible to make the samtools mpileup --max-depth variable definable by the clair3 user. I'm running amplicon data (high coverage) with a very small reference genome on the institution HPC system, so the memory usage is not a worry for my data, I would like to however increase the number of reads used for the pileup (instead of the 8000 default) to increase the sensitivity to lower frequency variants. We are looking to comfortably go down to 5% minority variants if possible. Other suggestions on how to achieve that are also welcome!

**Comment by aquaskyline** [comment]
Clair3 can hardly go down to 5%. Clair3 is still basically a germline caller, in which 5% can hardly qualify as a germline variant.

**Comment by mbdabrowska1** [comment]
Hmm I see. I wonder it there are any settings within Clair3 that stop it from working with a haploid organism and low frequency variants? We are interested in detecting variants within a viral population and looking to adapt Clair3 for a similar use case scenario.

**Comment by aquaskyline** [comment]
No more suggestions except for using the `--haploid_sensitive` option. With the current design, Clair3 cannot be used for detecting variants with AF<0.15.
