### ISSUE TITLE
Why doesn't clair3_c_impl.sh have step 5?

### ISSUE THREAD

**Issue by oranges7** [HKU-BAL/Clair3#243]
Why does clair3_c_impl.sh not need to generate phase_bam files？

**Comment by zhengzhenxian** [comment]
@oranges7,

We have integrated the `whatshap haptagging` functionality into the full-alignment submodule implemented in [c implement](https://github.com/HKU-BAL/Clair3/blob/main/src/clair3_full_alignment.c#L254). In this implementation, all reads are haptagged during the read parsing, eliminating the need for generating intermediate phased BAM files. This optimization significantly reduces the disk space usage.

**Comment by oranges7** [comment]
I see. Thank you very much for your quick reply.
