### ISSUE TITLE
Does Clair3 normalize?

### ISSUE THREAD

**Issue by Axze-rgb** [HKU-BAL/Clair3#246]
Hello, 

I know vcf normalization is a highly complex topic. There was a time when you had to use bcftools norm. But since then, I noticed more and more callers trying their best to normalize "out of the box". Is it the case of Clair3? I didn't find any issue asking this. I'm sorry if I already asked you before. I have a little doubt. I plan to call on seven samples and merge into a single vcf. I don't want joint calling because I am looking for variants present only in each sample (private variants), and according to Heng Li, joint calling is conservative. 

Again, apologize if I have asked this before. 

Thanks a lot (and for Clair3, it's a very excellent piece of software, I am working on a complicated genome and its performance are stellar).

**Comment by aquaskyline** [comment]
Thanks for using Clair3. Normalization is complicated and depends on how users want to use the variants in the downstream. Say for example, some downstream analyses require multiallelic sites to be split into multiple rows, some don't. And the two different requirements make a difference in normalization especially for a multi-sample VCF file. So it seems to me that it is better to leave normalization to the users.

**Comment by Axze-rgb** [comment]
Thanks for your answer, I had yet to consider this point. It seems a valid reason to leave it to the user, indeed. Thanks for your answer.
