### ISSUE TITLE
Running Clair on a .bam with mixed flowcell types

### ISSUE THREAD

**Issue by fidibidi** [HKU-BAL/Clair3#250]
Hello, 

Would love some input in this scenario:

We have two bam files for the same sample that we've merged into one bam. 

However, one was generated from R9 flowcell, and the other R10. 

We'd like to run Clair on the samples but are unsure of how to proceed since clair uses specific models for the flowcell used.

**Comment by aquaskyline** [comment]
It can run to the end but the results are not reliable because R9 and R10 data have very different patterns.

**Comment by fidibidi** [comment]
Thanks for confirming!
