### ISSUE TITLE
Do I need to filter the input BAMs?

### ISSUE THREAD

**Issue by tinyfallen** [HKU-BAL/Clair3#255]
Hi dear developers,

Thanks for your works. 

When I used GATK to call variants, it was suggested to mark the duplicated reads in the BAM files.

So I would like to ask whether it is in need to filter the BAMs using mapping quality or some other thresholds and mark duplicates for use as inputs of Clair3?

**Comment by aquaskyline** [comment]
The common practice doesn't require mark duplicate for long-read. Filters are done internally in Clair3.

**Comment by tinyfallen** [comment]
已收到您发送的邮件！
