### ISSUE TITLE
SNP calling from bisulfite converted ONT

### ISSUE THREAD

**Issue by weishwu** [HKU-BAL/Clair3#256]
We are planning to use the Twist protocol to do targeted ONT sequencing. The protocol includes an enzymatic conversion step to convert all unmethylated Cs to Ts, so the analysis will be similar to Illumina BS-Seq. Our purpose is to do allele-specific methylation so we have to first call SNPs and then use them to phase methylation to the two alleles. Is there a way to use Clair3 for this type of SNP calling? If not, does anyone know of any other tool that I can try? I know there are multiple BS SNP callers for Illumina, but I'm not sure if they are applicable for ONT. Besides, my experience is that the accuracy of BS SNP calling is not that good.

Ideally, we should use adaptive sampling to do the targeted sequencing so that we can keep the DNA native. However, AS right now does not provide high enough fold enrichment and we are restricted by funding.

**Comment by aquaskyline** [comment]
I think it's doable, but instead of using all SNPs, please maybe choose only the top n% SNPs for your phasing purpose. I believe Clair3 can still identify most of the C->T, but the model would still consider the excessive number of C->T abnormal and thus lowering their scores.

**Comment by weishwu** [comment]
@aquaskyline Thanks!
