### ISSUE TITLE
Snp prediction accuracy is low in all difficult mapping areas

### ISSUE THREAD

**Issue by oranges7** [HKU-BAL/Clair3#258]
Hi,
I use v3.1 stratification BED files,HG003 GUPPY3.6.0 data for testing, why the accuracy of snp and indel is not high，The results show that only 55%. I queried the results of Truth Challenge V2 and found that the accuracy of snp is more than 98%.Is this normal? I use bed files with high confidence regions, and the results are normal. What is the reason?
The default parameters I use.
[INFO] CLAIR3 VERSION: v1.0.0
[INFO] BAM FILE PATH: /mnt/usb2/data/hg003_g360.sort.bam
[INFO] REFERENCE FILE PATH: /mnt/usb2/data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
[INFO] MODEL PATH: /home/ywenjing/anaconda3/envs/clair3/bin/models/r941_prom_hac_g360+g422

**Comment by aquaskyline** [comment]
The performance was elaborated in papers. For updated performance, please try r10 data and newer basecallers.
