### ISSUE TITLE
Do I have to train a model for specific organism?

### ISSUE THREAD

**Issue by Modernism-01** [HKU-BAL/Clair3#259]
Hi, Developers,

I am confused about whether I have to train a model for ONT data from Pig before running the Clair3 variants calling command. Or can I use the provided model from humans?

Best,

Lingsen

**Comment by aquaskyline** [comment]
You can use the human model for any other species.

**Comment by Modernism-01** [comment]
That is OK. Thank you very much.

**Comment by Modernism-01** [comment]
Thank you very much for your response. 

I am sorry to reopen this issue. 

Although I found some studies applying the human model called SNP and INDEL, I don't quite understand the reason for this. Whether the genomic characteristics of different species have a great influence like the different platforms on calling SNPs? In addition, is it too difficult to train a super-precise model for other species because we do not have a high-quality ground truth file?

Best,

Lingsen

**Comment by aquaskyline** [comment]
Short answer is because species-specific errors are way less significant than the alignment errors and sequencing-platform errors that are learned by the Clair3 models.

**Comment by Modernism-01** [comment]
Got it. Thank you very very much!
