### ISSUE TITLE
pileup_*.vcf': No such file or directory

### ISSUE THREAD

**Issue by Andrea-SS** [HKU-BAL/Clair3#26]
Hello!
I'm  using Claire3 v0.1-r3 with ONT reads. I'm running the command: 

docker run -it -v $INPUT_DIR:$INPUT_DIR -v $OUTPUT_DIR:$OUTPUT_DIR hkubal/clair3:"$BIN_VERSION" /opt/bin/run_clair3.sh --print_ref_calls --qual=15 --bam_fn=$INPUT_DIR/bar1.bam --ref_fn=$INPUT_DIR/Serratia_UMH9.fa --threads="1" --platform="ont" --model_path="/opt/models/ont" --output=$OUTPUT_DIR --ctg_name=NZ_CP018923.1

However, I obtain the following error in the first step:

BrokenPipeError: [Errno 32] Broken pipe
[INFO] Delay 5 seconds before starting variant calling ...
[faidx] Truncated sequence: NZ_CP018923.1:1512296-6024592
[mpileup] 1 samples in 1 input files
Traceback (most recent call last):
  File "/opt/bin/clair3/../clair3.py", line 89, in <module>
    main()
  File "/opt/bin/clair3/../clair3.py", line 83, in main
    submodule.main()
  File "/opt/bin/preprocess/CreateTensorPileup.py", line 547, in main
    CreateTensorPileup(args)
  File "/opt/bin/preprocess/CreateTensorPileup.py", line 411, in CreateTensorPileup
    tensor_can_fp.stdin.write(l)
BrokenPipeError: [Errno 32] Broken pipe

real	0m14.781s
user	0m2.819s
sys	0m0.579s
[INFO] Merge chunked contigs vcf files
cat: '/home/andrea/Escritorio/Brote_Serratia/2021_Brote_HAV/FILT_ASSEMBLY/14_Mapeo_ref/CLAIR3/tmp/pileup_output/pileup_*.vcf': No such file or directory
[ERROR] No vcf file found, please check the setting

[output.zip](https://github.com/HKU-BAL/Clair3/files/6632202/output.zip)

**Comment by aquaskyline** [comment]
We noticed `[faidx] Truncated sequence: NZ_CP018923.1:1512296-6024592` in your error message. The error message is from `samtools` at https://github.com/samtools/samtools/blob/5fcc7a4fa822bb216030b6d6803e846f99b7ad41/faidx.c, line 114. It might happen when your records in the `.fai` file doesn't match with your `.fa` file. Could you please try if you could use `faidx` to extract a part of NZ_CP018923.1 successfully.

**Comment by Andrea-SS** [comment]
I can extract a region without any problem:

faidx Serratia_UMH9.fa NZ_CP018923.1:1-10
>NZ_CP018923.1:1-10
GCTCCATCAG

I atach the reference sequence.
[Serratia_UMH9.zip](https://github.com/HKU-BAL/Clair3/files/6636307/Serratia_UMH9.zip)

**Comment by aquaskyline** [comment]
What about `samtools faidx Serratia_UMH9.fa NZ_CP018923.1:1512296-6024592`? We tried it on your reference and had no problem, is it the same on your side?

**Comment by Andrea-SS** [comment]
I can extract the region correctly, but the message "[faidx] Truncated sequence" is displayed, I suppose due to the size of the sequence (5024591 pb). 

samtools faidx Serratia_UMH9.fa NZ_CP018923.1:1512296-6024592 | head -n 2

[faidx] Truncated sequence: NZ_CP018923.1:1512296-6024592
>NZ_CP018923.1:1512296-6024592
CATCTGTTTACTCCGCAGGAGTGGCCGAAACTGGTGCTCGGCCTGATCGCCTTCGGCGGC

I don't understand if the problem is due to this and why this length is being used.

**Comment by aquaskyline** [comment]
Thanks for the feedback, if the sequence can be output properly, the error message "[faidx] Truncated sequence" wouldn't be a concern, my previous guess was wrong.

We looked again into your log and got no hint on what was wrong. We would like to repeat your experiment using the exact files in our environment to trace the problem. Is the BAM file you used publicly available?

**Comment by Andrea-SS** [comment]
https://drive.google.com/drive/folders/1v0MyAxTDqVuTA2C0kMe6mxmNl2HkTZeH?usp=sharing

Thanks for your help.

**Comment by zhengzhenxian** [comment]
Hi, thanks for providing bam file, interestingly, we ran successfully using both docker and the conda envrionment. For your reference, we used the command below:
```platform='ont'
INPUT_DIR=${INPUT_DIR}
OUTPUT_DIR=${INPUT_DIR}/output
samtools faidx ${INPUT_DIR}/Serratia_UMH9.fa
mkdir -p ${OUTPUT_FOLDER}
BIN_VERSION="v0.1-r3"
docker run -it \
    -v ${INPUT_DIR}:${INPUT_DIR} \
    -v ${OUTPUT_DIR}:${OUTPUT_DIR} \
    hkubal/clair3:"${BIN_VERSION}" \
    /opt/bin/run_clair3.sh \
    --bam_fn=${INPUT_DIR}/bar1.bam \
    --ref_fn=${INPUT_DIR}/Serratia_UMH9.fa \
    --model_path="/opt/models/ont" \
    --threads="1" \
    --platform="ont" \
    --output=${OUTPUT_DIR} \
    --ctg_name="NZ_CP018923.1" \
    --print_ref_calls \
    --qual=15
```
Attached please also find the VCF file we have generated for your reference. We don’t have a good guess of the reason at the moment, but a rule of thumb is to try to pull the docker image or rebuild the conda environment again.
[merge_output.vcf.gz](https://github.com/HKU-BAL/Clair3/files/6642362/merge_output.vcf.gz)

**Comment by Andrea-SS** [comment]
I have already tried that but I get the same result with both conda and docker.

**Comment by zhengzhenxian** [comment]
Hi, we have created a google colab notebook to show how we have processed the data you sent us. Please upload the reference fa file and bam file to your google drive and change the two paths accordingly. Hopefully, the notebook can provide some hints on which step be the culprit in your running environment.

 https://colab.research.google.com/drive/1T6QPYvWAmOy8Ux4SGI85U_KaAPJhTHzc?usp=sharing

**Comment by aquaskyline** [comment]
We further added three google colab notebooks as a quick demo for the three sequencing platforms.

Issue closed due to inactivity.
