### ISSUE TITLE
Variants below min_coverage still being called

### ISSUE THREAD

**Issue by mproberts99** [HKU-BAL/Clair3#262]
Hi,

I have set the min_coverage parameter to 10, but am still observing calls with read counts below that number in the final VCF. When I up the parameter to 20, then I see those have disappeared. Is there a range around the min_coverage that Clair3 still allows that would explain the presence of these calls? I have attached the VCF and the log.
[run_clair3.log](https://github.com/HKU-BAL/Clair3/files/13992803/run_clair3.log)
[merge_output.vcf.gz](https://github.com/HKU-BAL/Clair3/files/13992804/merge_output.vcf.gz)

**Comment by zhengzhenxian** [comment]
@mproberts99,

Thanks for the log, seem all low-coverage variants were reported by the full-alignment model, we will check and get back to you soon.

**Comment by aquaskyline** [comment]
Hi, @mproberts99, sorry for the late response, we have checked and confirmed it is a problem in our code. The problem doesn't affect the correctness of each variant but allows some variants below the minimum coverage to be outputted. We will solve the problem in the next update, but before that, a hard filter on DP after calling could also solve the problem.

**Comment by aquaskyline** [comment]
Fixed in v1.0.6
