### ISSUE TITLE
r1041_e82_400bps_hac_v420 model of Guppy basecaller

### ISSUE THREAD

**Issue by cuzzlisa** [HKU-BAL/Clair3#264]
Hi, 

    I'm aiming to execute clair3, but I couldn't find the r1041_e82_400bps_hac_v420 model of Guppy basecaller within rerio. The basecalling process was carried out by the sequencing company. Upon inspecting the read names in the Fastq files, I found the tag 'basecall_model_version_id=dna_r10.4.1_e8.2_400bps_hac@v4.2.0' embedded within. The Guppy version used is 7.1.4. Could you recommend the most suitable model for my analysis? Thank you!

**Comment by aquaskyline** [comment]
any dorado model trained for r10.4.1 hac data will work I think.

**Comment by cuzzlisa** [comment]
> any dorado model trained for r10.4.1 hac data will work I think.

thank you!

**Comment by eesiribloom** [comment]
would the same apply to R9.4.1 data? i.e. Would a guppy R9.4.1 model be suitable for R9.4.1. data basecalled with dorado ?
