### ISSUE TITLE
Why are these SNPs called as RefCall?

### ISSUE THREAD

**Issue by weishwu** [HKU-BAL/Clair3#266]
These SNPs look true on IGV. Why are they labelled as RefCall by Clair3? The AF values in the output VCF are around 0.5.
<img width="1440" alt="Screenshot 2024-02-12 at 9 55 01 PM" src="https://github.com/HKU-BAL/Clair3/assets/13355007/ddd30ae6-3ee7-4517-813b-0202e38d51aa">

Another question: Clair3 is to find germline variants. However, my data is amplicon sequencing and may contain mosaic variants whose frequencies can have a wide range. Can Clair3 identify these variants? I don't have tumor-normal pairs so can't use ClairS.

**Comment by aquaskyline** [comment]
Are you using these options? https://github.com/HKU-BAL/Clair3?tab=readme-ov-file#dealing-with-amplicon-data

**Comment by weishwu** [comment]
@aquaskyline 
Thanks! I added those options and they rescued 2 out of the 4 SNPs. However, these 2 SNPs appear true in IGV, but were still labelled as RefCall:
```
C412_SP	2296	.	G	.	16.36	RefCall	P	GT:GQ:DP:AD:AF	0/0:16:4515:3614:0.8004
C412_SP	2299	.	C	.	15.97	RefCall	P	GT:GQ:DP:AD:AF	0/0:15:4552:3724:0.8181
```

<img width="1440" alt="Screenshot 2024-02-13 at 10 02 15 AM" src="https://github.com/HKU-BAL/Clair3/assets/13355007/823963ca-10be-457e-b5e2-5ce507325b5e">

The variant AF values shown in IGV are higher than in the VCF, which I guess was because part of the reads didn't pass the quality threshold.

My command-line:

```
  run_clair3.sh \
  --bam_fn={input} \
  --ref_fn={params.genome_fasta} \
  --include_all_ctgs \
  --ref_pct_full=1.0 \
  --var_pct_full=1.0 \
  --no_phasing_for_fa \
  --output={params.outdir} \
  --threads={threads} \
  --platform=ont \
  --model_path=r1041_e82_400bps_hac_v410
```

**Comment by aquaskyline** [comment]
Could you please show what the records of C412_SP:229 and C412_SP:2299	are like in the `full_alignment.vcf.gz` file?

**Comment by weishwu** [comment]
```
C412_SP	2296	.	G	.	30.17	RefCall	F	GT:GQ:DP:AD:AF	0/0:30:11094:7072:0.6375
C412_SP	2299	.	C	.	31.41	RefCall	F	GT:GQ:DP:AD:AF	0/0:31:11131:7248:0.6512
```
Thanks.

**Comment by aquaskyline** [comment]
Clair3's model has decided with good quality (GQ) that 2296 and 2299 are not a variant, and the reads supporting an alternative allele are more likely to be sequencing or alignment errors.

**Comment by weishwu** [comment]
@aquaskyline OK. Thansk!
