### ISSUE TITLE
genome phasing

### ISSUE THREAD

**Issue by DiegoSafian** [HKU-BAL/Clair3#269]
Hi,
 
I am writing because I want to phase a genome that I assembled using  nanopore long reads and then I used HiC data to scaffold chromosomes.  I was wondering if you could provide me with some advance on how to do this. What tool would you use to phase the genome?? I must say that the draft genome was assembled using flye, so, maternal and paternal might be collapsed and, therefore, I may need to use another assembler. Do you know a good option for nanopore reads?? 

 I have ~250M valid HiC reads for the genome, so I also wonder if it would be possible to phase male and female nanopore reads using Clair3, assemble them separately and then us hic for scaffold
 
My best,
Diego

**Comment by COMInterop** [comment]
hi diego

you might like to try PECAT:

https://github.com/lemene/PECAT

i find it works better with 'phase_method=1'

then ALLHiC should sort out the linkage groups

in my hands phasing reads and then assembling separately doesn't work
