### ISSUE TITLE
Detect very low SNP frequencies

### ISSUE THREAD

**Issue by HJArdin** [HKU-BAL/Clair3#270]
Hello,
We are looking to test a really low frequencies (2.5, 5, 10, 20%) SNP detection in viral sample.
We analyse two BAC with one mutation, mix in different proportion. I use Calir3 with this parameter :
-m r1041_e82_400bps_hac_v410/
--haploid_sensitive
--include_all_ctgs
--snp_min_af=0.01
--min_coverage=10
--no_phasing_for_fa
--var_pct_full=1
--ref_pct_full=1
--var_pct_phasing=1
--call_snp_only
-p ont

Clair3 catch all SNP > 20%
But when the proportion is bellow 20% even if I can see the SNP on IGV 
![image](https://github.com/HKU-BAL/Clair3/assets/100346160/6d2a18b7-8bb1-4721-803e-5a235904dfac)
It appears as RefCall in full_alignment.vcf :
![image](https://github.com/HKU-BAL/Clair3/assets/100346160/252f201e-6715-471b-9e31-87117be18549)
And in pileup.vcf:
![image](https://github.com/HKU-BAL/Clair3/assets/100346160/88198eec-a630-4a68-a850-f1160458c9a9)

Maybe I missunderstand something but why this SNP is tag as a 'RefCall' ?

Best regards,
Hugo

**Comment by aquaskyline** [comment]
Clair3 is for germline mutation, germline mutations have zygosity.
For detecting variants with AF<0.2, try ClairS-TO.
