### ISSUE TITLE
Is there a way to report a MAPQ or MQ metrics?

### ISSUE THREAD

**Issue by Axze-rgb** [HKU-BAL/Clair3#275]
Hello, 

We are dealing with non-model organisms that prevent us from having ultra-long ONT reads. Most of them are 10 Kb long. It's an issue because it's not long enough to span all repeats. Therefore, we have apparent false 0/1 calls (obvious when eyeballing in IGV). However, I understand why Clair3 made the mistake. It's important to note that my organism's Het rate is around 3%, much higher than the 0.1% seen in the human genome. Therefore, due to the repeat and relatively short reads, even if a position has an AD of 10,70, it can still have a genotype of 0/0.  I would have liked to try a mapping quality filter (we have some truth set in the form of an assembled phased genome). But there seems to be none... My understanding is that it's because Clair3 deals internally with MAPQ. 

I see there is a snp_min_af setting. But it's a vague proxy because if raised relatively high, it will prevent false calls in the repeats. Still, it will probably induce false negatives in non-repetitive regions. 

Would you have any specific advice on how to tweak Clair3? Otherwise, I will try to deal with the false calls using pileup from the genome assemblies; it's going to be a bit experimental. 

I realise it's possible to retrain Clair3, but it requires significant GPU power, right? 

Thanks for any insight you might have. I realise there might be no solution since the issue is the shortened reads we get with this organism. Feel free to close this if you think there is nothing we can do with the caller. 

Thanks a lot for your work on clair3 (I am not saying this to flatter you, but it's genuinely awesome; even if I have issues, they are already orders of magnitudes lower than with other callers). 

Alex

**Comment by aquaskyline** [comment]
With 3% heterozygosity, assembled phased genome based variant calling seems to the most viable and reliable way to go. Retraining a model helps but I am not sure if it is worth it in your case because not only you need high quality training data, but also that 3% heterozygosity is even higher than the average base error rate of the latest ONT reads, making it a problem worth studying before production using the current design of Clair3.

**Comment by Axze-rgb** [comment]
Thanks so much for the insights. Hopefully, we have enough data to assemble and phase. It's an interesting problem: How can we generalize these AI models for organisms with higher heterozygosity since the human genome is relatively low in heterozygosity?
