### ISSUE TITLE
[ERROR] No pileup model found in provided model path and model prefix 

### ISSUE THREAD

**Issue by jsromanowski** [HKU-BAL/Clair3#277]
Hello,

I followed installation instructions using conda and ran the follow clair3 command in bash to call variants in nanopore sequencing data:

$ run_clair3.sh --bam_fn=1026NJ4_NHEJ_FLsorted.bam --ref_fn=NHEJAssayABshortref.fas --output=/mnt/c/users/josep/Downloads/ROMANOWSKI_CUSTOM_253/NHEJassay_IGV_files --threads=16 --platform=ont --model_path=/home/joeromanowski/miniconda3/envs/clair3/bin/models/

To which I received the following output:

[INFO] CLAIR3 VERSION: v1.0.5
[INFO] BAM FILE PATH: /mnt/c/users/josep/Downloads/ROMANOWSKI_CUSTOM_253/NHEJassay_IGV_files/1026NJ4_NHEJ_FLsorted.bam
[INFO] REFERENCE FILE PATH: /mnt/c/users/josep/Downloads/ROMANOWSKI_CUSTOM_253/NHEJassay_IGV_files/NHEJAssayABshortref.fas
[INFO] MODEL PATH: /home/joeromanowski/miniconda3/envs/clair3/bin/models
[INFO] OUTPUT FOLDER: /mnt/c/users/josep/Downloads/ROMANOWSKI_CUSTOM_253/NHEJassay_IGV_files
[INFO] PLATFORM: ont
[INFO] THREADS: 16
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: /home/joeromanowski/miniconda3/envs/clair3
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] LONGPHASE PATH: EMPTY
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] PHASING PROPORTION: 0.7
[INFO] MINIMUM MQ: 5
[INFO] MINIMUM COVERAGE: 2
[INFO] SNP AF THRESHOLD: 0.08
[INFO] INDEL AF THRESHOLD: 0.15
[INFO] BASE ERROR IN GVCF: 0.001
[INFO] GQ BIN SIZE IN GVCF: 5
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: False
[INFO] ENABLE REMOVING INTERMEDIATE FILES: False
[INFO] ENABLE LONGPHASE FOR INTERMEDIATE VCF PHASING: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING WHATSHAP: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING LONGPHASE: False
[INFO] ENABLE HAPLOTAGGING FINAL BAM: False
[INFO] ENABLE LONG INDEL CALLING: False
[INFO] ENABLE C_IMPLEMENT: True

[ERROR] No pileup model found in provided model path and model prefix /home/joeromanowski/miniconda3/envs/clair3/bin/models/pileup

real    0m0.065s
user    0m0.011s
sys     0m0.004s

Any help to overcome this is appreciated!

Best,

Joe

**Comment by zhengzhenxian** [comment]
Hi, @jsromanowski 

The pileup* and full-alignment* models are not found in `/home/joeromanowski/miniconda3/envs/clair3/bin/models/`, please check the model path.

**Comment by zhengzhenxian** [comment]
[Here](https://github.com/HKU-BAL/Clair3?tab=readme-ov-file#pre-trained-models) is the instruction to download models. You can also try the following command to download the models:
```
mkdir models
wget http://www.bio8.cs.hku.hk/clair3/clair3_models/clair3_models.tar.gz 
tar -zxvf clair3_models.tar.gz -C ./models
```
And then select the appropriate models using the `--model_path` command such as: `--model_path=./models/r941_prom_sup_g5014`.

If you require the latest ONT-provided model, please visit [Rerio](https://github.com/nanoporetech/rerio/tree/master/clair3_models) to download the models.
