### ISSUE TITLE
Is Representation Unification required for all depths for pileup model training?

### ISSUE THREAD

**Issue by dehui333** [HKU-BAL/Clair3#279]
Hi, 

According to revision 1 of the instructions for training the full-alignment model, we only need to run Representation Unification once for the full depth. Since there is no such revision for the pileup training instructions, does it mean it still requires one run of Representation Unification for each depth? 

Thank you.

**Comment by zhengzhenxian** [comment]
Hi, 

You only need to run RU for the full depth only, no need for each subsampled depth.
