### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by agos316** [HKU-BAL/Clair3#28]
Hi, 
Everything seems to work until selection of candidates for full alignment. 

"var_qual_cut_off = variant_qual_list[:int(var_pct_full * len(variant_qual_list))][-1]
IndexError: list index out of range"

Is there a way to bypass this or the reason for this error? 

thanks 

Marc

**Comment by zhengzhenxian** [comment]
Hi, Marc,

Thanks for trying out Clair3. For us to pinpoint the problem, could you send the running log `${OUTPUT_DIR}/run_clair3.log` and the log directory  `${OUTPUT_DIR}/log` to zxzheng@cs.hku.hk.

zhenxian

**Comment by agos316** [comment]
Zheng, 

It is no problem, the clair software works great for my application. let me gather the files and send them. Additionally, yes I am using v0.1-r3

Best

**Comment by zhengzhenxian** [comment]
Hi, Marc, 

Thanks for providing your log, we have confirmed it to be a bug in Clair3. 

We found the bug that will be triggered when candidate variants are too few. We updated the code with a boundary check (`preprocess/SelectQual.py`  line 52 and line 70, `preprocess/SelectCandidates.py` line 234). The fix will be included in r4 that will be rollout by the end of June.

**Comment by agos316** [comment]
Look forward to the update. Thanks for your help.

**Comment by aquaskyline** [comment]
fixed in v0.1-r4
