### ISSUE TITLE
Pileup model to use for full-alignment training step

### ISSUE THREAD

**Issue by dehui333** [HKU-BAL/Clair3#281]
Hi, 

In step 

**II. Build compressed binary files for full-alignment model training, 1. Run Clair3 pileup model**

in the instructions for full alignment model training/fine-tuning, the pileup model used is by default 

**--model_path="${CONDA_PREFIX}/bin/models/ont"**

If I intend to use the fine-tuned full-alignment model together with a fine-tuned pileup model, should I replace the above with the fine-tuned pileup model or leave it as it is - the ont model? 

Thank you.

**Comment by zhengzhenxian** [comment]
@dehui333 
Just leave it as the default ONT model.

**Comment by dehui333** [comment]
Thank you for the very prompt reply!
