### ISSUE TITLE
Failed to Merge gvcf files into multiple gvcf and vcf

### ISSUE THREAD

**Issue by Modernism-01** [HKU-BAL/Clair3#283]
I have finished the vcf calling with clair3, the command is below: 

```
singularity exec \
  -B ${INPUT_DIR}:${INPUT_DIR} \
  -B ${OUTPUT_DIR}:${OUTPUT_DIR} \
  $IMAGE_PATH/clair3_latest.sif \
  /opt/bin/run_clair3.sh \
  --bam_fn=${INPUT_DIR}/${BAM} \
  --ref_fn=${REF} \
  --threads=${THREADS} \
  --platform=${PLATFORM} \
  --model_path="/opt/models/${MODEL_NAME}" \
  --output=${OUTPUT_DIR}/${SLURM_JOB_NAME} \
  --sample_name=${SLURM_JOB_NAME} \
  --print_ref_calls \
  --gvcf \
  --no_phasing_for_fa \
  --include_all_ctgs
```
Then I attempted to merge gvcf files from different samples into a gvcf and genotype, but it was failed.

the GATK version :
The Genome Analysis Toolkit (GATK) v4.5.0.0
HTSJDK Version: 4.1.0
Picard Version: 3.1.1

```
gatk CombineGVCFs \
   -R $REF \
   --variant $gvcf1 \
   --variant $gvcf2 \
   --variant $gvcf4 \
   --variant $gvcf5 \
   -O $output1
```
the log file: 

> 21:05:10.190 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/public/home/zenglingsen/04.software/02.Anaconda/Or/envs/pytorch/share/gatk4-4.5.0.0-0/gatk-package-4.5.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
> 21:05:10.646 INFO  CombineGVCFs - ------------------------------------------------------------
> 21:05:10.650 INFO  CombineGVCFs - The Genome Analysis Toolkit (GATK) v4.5.0.0
> 21:05:10.650 INFO  CombineGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
> 21:05:10.650 INFO  CombineGVCFs - Executing as zenglingsen@comput7 on Linux v3.10.0-862.el7.x86_64 amd64
> 21:05:10.650 INFO  CombineGVCFs - Java runtime: OpenJDK 64-Bit Server VM v17.0.3-internal+0-adhoc..src
> 21:05:10.651 INFO  CombineGVCFs - Start Date/Time: 2024年3月14日 CST 下午9:05:09
> 21:05:10.651 INFO  CombineGVCFs - ------------------------------------------------------------
> 21:05:10.651 INFO  CombineGVCFs - ------------------------------------------------------------
> 21:05:10.652 INFO  CombineGVCFs - HTSJDK Version: 4.1.0
> 21:05:10.652 INFO  CombineGVCFs - Picard Version: 3.1.1
> 21:05:10.652 INFO  CombineGVCFs - Built for Spark Version: 3.5.0
> 21:05:10.653 INFO  CombineGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
> 21:05:10.653 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
> 21:05:10.653 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
> 21:05:10.653 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
> 21:05:10.654 INFO  CombineGVCFs - Deflater: IntelDeflater
> 21:05:10.654 INFO  CombineGVCFs - Inflater: IntelInflater
> 21:05:10.654 INFO  CombineGVCFs - GCS max retries/reopens: 20
> 21:05:10.654 INFO  CombineGVCFs - Requester pays: disabled
> 21:05:10.655 INFO  CombineGVCFs - Initializing engine
> 21:05:11.017 INFO  FeatureManager - Using codec VCFCodec to read file file:///public/home/zenglingsen/01.data/01.ONT_data/01.ONT_20X_fastq_SNP_calling/04.clair3/AW/merge_output.gvcf.gz
> 21:05:11.319 INFO  FeatureManager - Using codec VCFCodec to read file file:///public/home/zenglingsen/01.data/01.ONT_data/01.ONT_20X_fastq_SNP_calling/04.clair3/BKS/merge_output.gvcf.gz
> 21:05:12.084 INFO  CombineGVCFs - Done initializing engine
> 21:05:12.122 INFO  ProgressMeter - Starting traversal
> 21:05:12.123 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
> 21:05:12.291 WARN  ReferenceConfidenceVariantContextMerger - Detected invalid annotations: When trying to merge variant contexts at location NW_018084912.1:462 the annotation F=true was not a numerical value and was ignored
> 21:05:12.892 INFO  CombineGVCFs - Shutting down engine
> [2024年3月14日 CST 下午9:05:12] org.broadinstitute.hellbender.tools.walkers.CombineGVCFs done. Elapsed time: 0.05 minutes.
> Runtime.totalMemory()=671088640
> **_java.lang.IllegalStateException: The elements of the input Iterators are not sorted according to the comparator htsjdk.variant.variantcontext.VariantContextComparator_**
> 	at htsjdk.samtools.util.MergingIterator.next(MergingIterator.java:107)
> 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
> 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
> 	at org.broadinstitute.hellbender.engine.MultiVariantWalker.traverse(MultiVariantWalker.java:136)
> 	at org.broadinstitute.hellbender.engine.MultiVariantWalkerGroupedOnStart.traverse(MultiVariantWalkerGroupedOnStart.java:165)
> 	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1098)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:149)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:198)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:217)
> 	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:166)
> 	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:209)
> 	at org.broadinstitute.hellbender.Main.main(Main.java:306)
> Using GATK jar /public/home/zenglingsen/04.software/02.Anaconda/Or/envs/pytorch/share/gatk4-4.5.0.0-0/gatk-package-4.5.0.0-local.jar
> Running:
>     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /public/home/zenglingsen/04.software/02.Anaconda/Or/envs/pytorch/share/gatk4-4.5.0.0-0/gatk-package-4.5.0.0-local.jar CombineGVCFs -R /public/home/zenglingsen/01.data/03.Reference/GCF_000003025.6_Sscrofa11.1_genomic.fna --variant /public/home/zenglingsen/01.data/01.ONT_data/01.ONT_20X_fastq_SNP_calling/04.clair3/AW/merge_output.gvcf.gz --variant /public/home/zenglingsen/01.data/01.ONT_data/01.ONT_20X_fastq_SNP_calling/04.clair3/BKS/merge_output.gvcf.gz -O /public/home/zenglingsen/01.data/01.ONT_data/01.ONT_20X_fastq_SNP_calling/04.clair3/01.merge/test.merged.gvcf.gz

who can give me  some advice ? 
Thank you.

**Comment by zhengzhenxian** [comment]
@Modernism-01 Seem GATK reported that the VCF files are not sorted from the log: 
```
java.lang.IllegalStateException: The elements of the input Iterators are not sorted according to the comparator htsjdk.variant.variantcontext.VariantContextComparator
```

Could you try to use the GATK SortVCF submodule to sort all the VCFs like:
`gatk SortVcf -I input.gvcf.gz -O input.gatk_sorted.gvcf.gz`

and then re-run `CombineGVCFs` using the GATK sorted VCF?

**Comment by Modernism-01** [comment]
Thank you very much😊, @zhengzhenxian.

 I have solved this problem using SortVcf command and run CombineGVCFs successfully. However, I found that the order of contig in gvcf header did not match the order below #CHROM column. I do not know if this suitation led to this error.
