### ISSUE TITLE
Intermittent failure during parallel variant calling: Died at /opt/conda/envs/clair3/bin/parallel line 9375, <$fh> chunk 1.

### ISSUE THREAD

**Issue by gtollefson** [HKU-BAL/Clair3#284]
I'm developing a snakemake pipeline for running clair3 variant calling which runs the clair3 singularity container over a set of individual samples. Some sample runs fail and the clair3 logs report: Died at /opt/conda/envs/clair3/bin/parallel line 9375, <$fh> chunk 1. I've attached a txt file with the error message at line 80. It looks like clair3 fails during parallelization of variant calling on a single sample. 

When I rerun the snakemake, I see that usually, all of the failed samples complete running without error. I see this intermittent error behavior each time I run the snakemake. A majority of the failed runs are in smaller samples which leads me to wonder if it's an issue with many samples being handled for parallel processing at one time.

Can you help me to troubleshoot this intermittent error? 

My Clair3 call from snakemake is as follows:

```python
rule run_clair3_raw:
	"""
	call variants in all regions in sorted bams with clair3 and output gvcf and vcf files. Using 0.0001 as the minimum allele frequency for both snps and indels.
	"""
	input:
		samples_to_run=config["output_dir"]+'/mapping/bam_files/{sample}.sorted.bam',
		REF = config['genome_directory']+'/genome.fa', # TODO:make demo resources with Pf3D7 genome for built in tutorial demo data
		sif_path = config["clair3_sif_path"] # TODO: this can be handled by the singularity container eventually so users dont install clair3 themselves.
	output:
		vcf=config["output_dir"]+'/variant_calling/{sample}_raw'+'/merge_output.vcf.gz',
		gvcf=config["output_dir"]+'/variant_calling/{sample}_raw'+'/merge_output.gvcf.gz'
	params:
		INPUT_DIR = config["output_dir"]+'/mapping/bam_files',
		OUTPUT_DIR = config["output_dir"]+'/variant_calling/{sample}_raw',
		REF_DIR = config['genome_directory'],
		RESOURCE_DIR = config["project_resources"],
		THREADS = 4,
		MODEL_NAME = 'r941_prom_sup_g5014',
		targets_vcf = config["project_resources"]+'/targets.vcf.gz'
	shell:
		'''
		echo 'Processing sample: {wildcards.sample}'
		singularity exec \
			-B {params.INPUT_DIR} \
			-B {params.OUTPUT_DIR} \
			-B {params.REF_DIR} \
			-B {params.RESOURCE_DIR} \
			{input.sif_path} \
			/opt/bin/run_clair3.sh \
			--bam_fn={input.samples_to_run} \
			--ref_fn={input.REF} \
			--model_path=/opt/models/{params.MODEL_NAME} \
			--output={params.OUTPUT_DIR} \
			--threads={params.THREADS} \
			--platform=ont \
			--include_all_ctgs \
			--no_phasing_for_fa \
			--sample_name={wildcards.sample} \
			--gvcf \
			--snp_min_af=0.001 \
			--indel_min_af=0.001 \
			--include_all_ctgs \
			--threads=1 \
			--print_ref_calls
		'''
```

My full clair3 log:

> gtollefs@login009 RW-17017-502502-ArtR23RW-1_raw $ more run_clair3.log
[INFO] CLAIR3 VERSION: v1.0.5
[INFO] BAM FILE PATH: /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/mapping/bam_files/RW-17017-502502-ArtR23RW-1.sorted.bam
[INFO] REFERENCE FILE PATH: /nfs/jbailey5/baileyweb/bailey_share/resources/MIP_species_resources/pf/Pf_3D7/genomes/genome.fa
[INFO] MODEL PATH: /opt/models/r941_prom_sup_g5014
[INFO] OUTPUT FOLDER: /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw
[INFO] PLATFORM: ont
[INFO] THREADS: 1
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: /users/gtollefs/mambaforge/envs/snakemake
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] LONGPHASE PATH: EMPTY
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] PHASING PROPORTION: 0.8
[INFO] MINIMUM MQ: 5
[INFO] MINIMUM COVERAGE: 2
[INFO] SNP AF THRESHOLD: 0.001
[INFO] INDEL AF THRESHOLD: 0.001
[INFO] BASE ERROR IN GVCF: 0.001
[INFO] GQ BIN SIZE IN GVCF: 5
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: True
[INFO] ENABLE OUTPUT GVCF: True
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: True
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: True
[INFO] ENABLE REMOVING INTERMEDIATE FILES: False
[INFO] ENABLE LONGPHASE FOR INTERMEDIATE VCF PHASING: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING WHATSHAP: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING LONGPHASE: False
[INFO] ENABLE HAPLOTAGGING FINAL BAM: False
[INFO] ENABLE LONG INDEL CALLING: False
[INFO] ENABLE C_IMPLEMENT: True

> \+ /opt/bin/scripts/clair3_c_impl.sh --bam_fn /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/mapping/bam_files/RW-17017-502502-Ar
> tR23RW-1.sorted.bam --ref_fn /nfs/jbailey5/baileyweb/bailey_share/resources/MIP_species_resources/pf/Pf_3D7/genomes/genome.fa --threads 1 --model_path /opt/models/r941_prom_sup_g5014 --platfor
> m ont --output /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw --bed_fn=EMPTY --vc
> f_fn=EMPTY --ctg_name=EMPTY --sample_name=RW-17017-502502-ArtR23RW-1 --chunk_num=0 --chunk_size=5000000 --samtools=samtools --python=python3 --pypy=pypy3 --parallel=parallel --whatshap=whatsha
> p --qual=2 --var_pct_full=0.7 --ref_pct_full=0.1 --var_pct_phasing=0.8 --snp_min_af=0.001 --indel_min_af=0.001 --min_mq=5 --min_coverage=2 --min_contig_size=0 --pileup_only=False --gvcf=True -
> -base_err=0.001 --gq_bin_size=5 --fast_mode=False --call_snp_only=False --print_ref_calls=True --haploid_precise=False --haploid_sensitive=False --include_all_ctgs=True --no_phasing_for_fa=Tru
> e --pileup_model_prefix=pileup --fa_model_prefix=full_alignment --remove_intermediate_dir=False --enable_phasing=False --enable_long_indel=False --keep_iupac_bases=False --use_gpu=False --long
> phase_for_phasing=False --longphase=EMPTY --use_whatshap_for_intermediate_phasing=True --use_longphase_for_intermediate_phasing=False --use_whatshap_for_final_output_phasing=False --use_longph
> ase_for_final_output_phasing=False --use_whatshap_for_final_output_haplotagging=False
> 
> [INFO] Check environment variables
> [INFO] Create folder /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw/log
> [INFO] Create folder /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw/tmp/pileup_ou
> tput
> [INFO] Create folder /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw/tmp/merge_out
> put
> [INFO] Create folder /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw/tmp/phase_out
> put
> [INFO] Create folder /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw/tmp/gvcf_tmp_
> output
> [INFO] Create folder /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw/tmp/full_alig
> nment_output
> [INFO] Create folder /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw/tmp/phase_out
> put/phase_vcf
> [INFO] Create folder /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw/tmp/phase_out
> put/phase_bam
> [INFO] Create folder /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1_raw/tmp/full_alig
> nment_output/candidate_bed
> [INFO] --include_all_ctgs enabled
> [WARNING] Contig name chr1 provided but no mapped reads in BAM, skip!
> [WARNING] Contig name chrP provided but no mapped reads in BAM, skip!
> [INFO] Call variant in contigs: chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chrM
> [INFO] Chunk number for each contig: 1 1 1 1 1 1 1 1 1 1 1 1 1 1
> [INFO] 1/7 Call variants using pileup model
> Died at /opt/conda/envs/clair3/bin/parallel line 9375, <$fh> chunk 1.
> 
> real	0m0.220s
> user	0m0.094s
> sys	0m0.063s
> [WARNING] No vcf file found with prefix:/nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR2
> 3RW-1_raw/tmp/pileup_output/pileup, output empty vcf file
> [WARNING] Copying pileup.vcf.gz to /nfs/jbailey5/baileyweb/gtollefs/mips_to_nanopore_gt/240215_MtoN_P2/second_output_rerun_for_completeness_check/variant_calling/RW-17017-502502-ArtR23RW-1
> _raw/merge_output.vcf.gz
> [INFO] Exit in pileup variant calling
> 
> real	0m2.892s
> user	0m0.684s
> sys	0m0.220s

**Comment by zhengzhenxian** [comment]
@gtollefson  Seem the `parallel` died according the log:"Died at /opt/conda/envs/clair3/bin/parallel line 9375, <$fh> chunk 1.".  Have you tried to use other parallel env path using the `--parallel` option?
