### ISSUE TITLE
Missense variant in FBN2 gene not reported by Clair3

### ISSUE THREAD

**Issue by tsneddon** [HKU-BAL/Clair3#287]
Hi:
We just ran Clair3 on our first human ONP long-read data. In comparing SNV calls that we identified in the same genome with Illumina short-reads, we found a missense variant that did not make it into the Clair3 vcf file:

>
##fileformat=VCFv4.2
##source=Clair3
##clair3_version=1.0.4
##cmdline=/nas/longleaf/rhel8/apps/clair3/1.0.4/Clair3/run_clair3.sh   --bam_fn=FBA-0005LR_merged.bam --ref_fn=../Homo_sapiens_assembly38.fasta   --threads=40 --platform=ont --model_path=./r1041_e82_400bps_hac_v420   --output=./clair3_results/
##reference=/proj/barc/projects/GENYSIS_Nov2023/FBA-0005LR/../Homo_sapiens_assembly38.fasta
##FILTER=<ID=PASS,Description="All   filters passed">
##FILTER=<ID=LowQual,Description="Low   quality variant">
##FILTER=<ID=RefCall,Description="Reference   call">
##INFO=<ID=P,Number=0,Type=Flag,Description="Result   from pileup calling">
##INFO=<ID=F,Number=0,Type=Flag,Description="Result   from full-alignment calling">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype   Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate   read depth (reads with MQ<20 or selected by 'samtools view -F 2316' are   filtered)">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic   depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized,   Phred-scaled likelihoods for genotypes as defined in the VCF   specification">
##FORMAT=<ID=AF,Number=1,Type=Float,Description="Observed   allele frequency in reads, for each ALT allele, in the same order as listed,   or the REF allele for a RefCall">

Looking at the alignment in IGV, it seems like it should have been called:

![Screenshot 2024-03-27 at 10 27 53 AM](https://github.com/HKU-BAL/Clair3/assets/7256012/ee6c3ff5-1e01-4274-ac7a-3b15de28f474)

Any thoughts on why it is not in the Clair3 output file?
Thanks!

**Comment by aquaskyline** [comment]
It's a bit hard to decide due to strand bias, among the four Ts, four are on positive strand and none on negative strand.

**Comment by tsneddon** [comment]
OK, thanks, does Clair3 have a default cut-off to filter based on strand bias? If so, how do we override it?

**Comment by aquaskyline** [comment]
Clair3 handles strand bias in its neural network, it does not use a hard filter. Our observation is that Clair3 loosens the cutoff when coverage is low but all other supports are good. However, extreme cases like having all reads on one strand are mostly filtered.

**Comment by tsneddon** [comment]
Thank you for the explanation!
