### ISSUE TITLE
Ref/Alt number (AD info)

### ISSUE THREAD

**Issue by airichli** [HKU-BAL/Clair3#288]
Hi,

I am confused with the Ref/Alt number in AD field, one example from my Clair3 result is as following:
chr19   3063757 .       G       GTTA    12.62   PASS    F       GT:GQ:DP:AD:AF  1/1:12:10:2,7:0.7000
It shows that there are 2 reads have the reference allele ('G'), 7 reads have the alternative allele ('GTTA'), however, when I check all the reads from my bam file. I found:
<img width="387" alt="image" src="https://github.com/HKU-BAL/Clair3/assets/44386140/36e9ec40-2c69-4edb-beb1-58f800a97058">
There are totally 10 reads, actually 9 reads have alternative allele ('GTTA'). Could you please give me some suggestion? The version of Clair3 I used is v1.0.6. Thanks.

I attached the txt
[testbamfile.txt](https://github.com/HKU-BAL/Clair3/files/14796276/testbamfile.txt)
 file with all the 10 reads. Looking forward to hearing from you.

**Comment by aquaskyline** [comment]
Some reads are filtered using `samtools view -F 2316`

**Comment by airichli** [comment]
> Some reads are filtered using `samtools view -F 2316`

Thanks, aquaskyline. The input bam file for Clair3 has been filtered, but I am still confused which 2 reads have the reference allele ('G')? I think no reads have this allele.

**Comment by zhengzhenxian** [comment]
@airichli, We tested your test file with Clair3 filtering with the following command: `samtools mpileup  --min-MQ 5 --min-BQ 0 --ff 2316  testbamfile.txt`. In the site 3063757, the output is "G+3TTAG+3TTAg+3ttag+3ttag+3ttaG+3TTAT**g**g+3tta**g**", You might find that there are two reference allele 'g' (string in bold).

**Comment by airichli** [comment]
> @airichli, We tested your test file with Clair3 filtering with the following command: `samtools mpileup --min-MQ 5 --min-BQ 0 --ff 2316 testbamfile.txt`. In the site 3063757, the output is "G+3TTAG+3TTAg+3ttag+3ttag+3ttaG+3TTAT**g**g+3tta**g**". You might find that there are two reference alleles 'g' in the mpileup output (string in bold).

Hi Zhenxian,
I see! Thanks for your explanation. Really appreciate it.

**Comment by airichli** [comment]
@zhengzhenxian 
Hi Zhenxian,
I see! Thanks for your explanation. Really appreciate it.
