### ISSUE TITLE
Calling MNVs

### ISSUE THREAD

**Issue by tsneddon** [HKU-BAL/Clair3#289]
Hi:
We annotate our short-read FreeBayes generated SNV vcfs with SNPeff.
SNPeff can annotate MNVs.
The default running of clair3 does not call MNVs.
Is there an option to call MNVs with clair3?
Thanks,
Tam

**Comment by aquaskyline** [comment]
when you say MNV, do you mean those with GT 1/2?

**Comment by tsneddon** [comment]
MNVs = multi-nucleotide variants: https://www.nature.com/articles/s41467-019-12438-5

**Comment by aquaskyline** [comment]
No. Clair3 calls only single small variants. We suggest using downstream phasing and annotation tools to identify MNVs.

**Comment by tsneddon** [comment]
OK, thank you for the information.
