### ISSUE TITLE
Documentation - conda install

### ISSUE THREAD

**Issue by holtjma** [HKU-BAL/Clair3#29]
Hello,

I was following the instructions for [building the anaconda virtual environment](https://github.com/HKU-BAL/Clair3#option-3-build-an-anaconda-virtual-environment) and encountered the following error while running Clair3:

```
OSError: Cannot load library <redacted>/Clair3/preprocess/realign/realigner: <redacted>/Clair3/preprocess/realign/realigner: cannot open shared object file: No such file or directory
```

After poking around the docker image, I noticed that [these two steps](https://github.com/HKU-BAL/Clair3/blob/39c1385965d97b1e2550cc90599bc9b07dd33cfc/Dockerfile#L46-L47) were missing from the above instructions:
```
    g++ -std=c++14 -O1 -shared -fPIC -o realigner ssw_cpp.cpp ssw.c realigner.cpp && \
    g++ -std=c++11 -shared -fPIC -o debruijn_graph -O3 debruijn_graph.cpp && \
```

After running those two steps, re-running clair3 seemed to work.  Just wanted to let you know so the docs could be updated.

**Comment by aquaskyline** [comment]
Thanks for the feedback, we have added them into `quick_demo/illumina_quick_demo.md`. We will also add a bioconda installation option to save users from some tedious installations.

**Comment by aquaskyline** [comment]
bioconda option added in v0.1-r4
