### ISSUE TITLE
ONT R10 Model

### ISSUE THREAD

**Issue by HelloYanming** [HKU-BAL/Clair3#290]
Hi Clair3 team,

Thanks for developing this tool! I am wondering if there is pre-trained model on ONT R10.4.1, of if current ONT model has been tested on R10.4.1 data.

**Comment by zhengzhenxian** [comment]
@HelloYanming Yes, pls visit [ONT-provided model](https://github.com/HKU-BAL/Clair3?tab=readme-ov-file#ont-provided-models) to download the R10.4.1 pre-trained model.
