### ISSUE TITLE
No module named 'libclair3'

### ISSUE THREAD

**Issue by Thaleslsilva** [HKU-BAL/Clair3#295]
I'm testing the workflow proposed by the Cattle Long Read Sequencing Consortium to process long read sequencing data (using minimap and sniffles), which is available online on their GitHub repository: https://github.com/BovLRC/bovLRC-documentation/blob/main/document.md

I tried to use Clair3 to call small variants within individual. To do this, I installed Clair3 according to option 4 in the repository (https://github.com/nanoporetech/Clair3/tree/main?tab=readme-ov-file#option-4-build-an-anaconda-virtual-environment)
But when I call the tool with my test data (https://www.ebi.ac.uk/ena/browser/view/ERX6660198) I receive the following message:

```
> File "~/Clair3/preprocess/CreateTensorPileupFromCffi.py", line 10, in <module>
      import libclair3
ModuleNotFoudError: No module named 'libclair3'
```
Any suggestions to fix this?
Thank you for your attention!

**Comment by aquaskyline** [comment]
`conda install bioconda::clair3-illumina` installs the libclair3 library. But the library is needed only when using Clair3 with Illumina data.

**Comment by sarahjeeeze** [comment]
I am getting the same, that illumina package didn't include libclair3

**Comment by daysmcgrath** [comment]
I am getting the same error: Clair3/preprocess/CreateTensorPileupFromCffi.py", line 10, in <module>
    import libclair3
ModuleNotFoundError: No module named 'libclair3'

**Comment by Thaleslsilva** [comment]
> I am getting the same, that illumina package didn't include libclair3

Have you found a solution to this problem? conda install bioconda::clair3-illumina doens't work for me.

**Comment by zhengzhenxian** [comment]
@Thaleslsilva

We attempted to install clair3-illumina using the command:
 `conda create -n clair3-ilmn -c bioconda clair3-illumina` 

After activating the conda environment, we found that libclair3.so is located at `${CONDA_PREFIX}/bin/libclair3.so`. Could you please check if you can locate this file?

If you are still experiencing issues, we recommend trying [singularity installation](https://github.com/HKU-BAL/Clair3?tab=readme-ov-file#option-2-singularity). The image was pulled from our pre-built Docker image and should work well for running Clair3.
