### ISSUE TITLE
Clair3 application

### ISSUE THREAD

**Issue by QuentinPerriere** [HKU-BAL/Clair3#296]
Hello,
I hope that you can help me with this : 
- Can I use Clair3 on my fastq.gz files generated using ONT minion ? 
- Can I use it to detect variants in **oomycetes**?

**Comment by aquaskyline** [comment]
Yes.
I don't know about oomycetes, but you can try because Clair3 models are not species specific.

**Comment by QuentinPerriere** [comment]
> Yes. I don't know about oomycetes, but you can try because Clair3 models are not species specific.

thank you , oomycetes are **diploid organism** 
but based on this example of usage : 
![image](https://github.com/HKU-BAL/Clair3/assets/167074757/8e262164-5736-43a4-ba44-e69919221e11)
How can I generate :  **-m, --model_path=STR          The folder path containing a Clair3 model (requiring six files in the folder, including pileup.data-00000-of-00002, pileup.data-00001-of-00002 pileup.index, full_alignment.data-00000-of-00002, full_alignment.data-00001-of-00002  and full_alignment.index).**

**Comment by aquaskyline** [comment]
Check out https://github.com/HKU-BAL/Clair3?tab=readme-ov-file#pre-trained-models for the available models.
