### ISSUE TITLE
empty vcf file

### ISSUE THREAD

**Issue by DaliBAmor** [HKU-BAL/Clair3#297]
Hello,

I am currently using the MinION technology from Oxford Nanopore Technologies, and basecalling was performed with Guppy version 3.2.9 or 4.3.4 for all Nanopore runs.

I am trying to use Clair3, but I encountered an issue where the output VCF file is empty. Here is the command I used:

**/opt/conda/envs/clair3/bin/run_clair3.sh --bam_fn /user/data/BAMS_1_pip/file_1.bam --ref_fn /user/data/ref_seq.fa --threads 8 --model_path /opt/conda/envs/clair3/bin/models/ont --platform ont --output /user/data/clair3**

I **suspect the problem may be related to the model_path; I am unsure which model to use.** 
I am working on a **fungus** genome. Any guidance on selecting the appropriate model for my analysis would be greatly appreciated.

**Comment by aquaskyline** [comment]
r9.4.1 data?

**Comment by DaliBAmor** [comment]
> r9.4.1 data?

I don't know if this helps or not but nanopore libraries  were sequenced on Flongle flow cells (FLO-FLG001, ONT) with Mk1C or MinION coupled with MinIT.

**Comment by aquaskyline** [comment]
FLO-FLG001 is r9.4.1. Use r941_prom_sup_g5014. Try to follow the steps in README, and let us know if you fail at the specific step.
