### ISSUE TITLE
 No contig intersection found, output header only in /lab/user/data/test1/clair3/merge_output.vcf.gz

### ISSUE THREAD

**Issue by DaliBAmor** [HKU-BAL/Clair3#298]
Hello,
my bam file was generated using minimap2.
As reference I'm using a reference sequence of a particular gene. This gene is expressed in fongus ( not a human chromosome)
I did what you asked me to do in #297 ( I installed clair3 using conda , I activated the env , then I runned the script below)
 
/opt/conda/envs/clair3/bin/run_clair3.sh \
  --bam_fn="/lab/user/data/test1/BAMS/file_1.sorted.bam" \
  --ref_fn="/lab/user/data/test1/demulti/ref_seq_bioedit/ref_bioedit.fa" \
  --threads=4 \
  --platform="ont" \
  --model_path="/opt/conda/envs/clair3/bin/models/r941_prom_sup_g5014/" \
  --output="/lab/user/data/test1/clair3"

_but I'm getting this error :_ 

**[INFO] Check environment variables
[INFO] --include_all_ctgs not enabled, use chr{1..22,X,Y} and {1..22,X,Y} by default
[WARNING] No contig intersection found, output header only in /lab/user/data/test1/clair3/merge_output.vcf.gz
[INFO] Exit in environment checking**

note : I have already used freebayes on the same bam file and I generated multiple variants.
note: my log folder is empty
I hope that you could help me with this !!

**Comment by zhengzhenxian** [comment]
@DaliBAmor 

As you are calling fongus data,  could you try to add `--include_all_ctgs` option?

**Comment by DaliBAmor** [comment]
> --include_all_ctgs

thank you !!!!
**I have these warning :** 
[WARNING] Cannot find any 0/1 variant in pileup output using variant quality cut-off proportion: 0.19999999999999996, total heterozygous variants: 0
[WARNING] Set low variant quality score cut-off to 0.0

[WARNING] Current maximum contig length 2281 is much smaller than default chunk size 5000000, You may set a smaller chunk size by setting --chunk_size=$ for better parallelism.

**Comment by zhengzhenxian** [comment]
Pls also enable ` --no_phasing_for_fa` for non-diploid organisms. More detail is shown [here](https://github.com/HKU-BAL/Clair3?tab=readme-ov-file#call-variants-in-non-diploid-organisms-haploid-calling).

**Comment by DaliBAmor** [comment]
> Pls also enable ` --no_phasing_for_fa` for non-diploid organisms. More detail is shown [here](https://github.com/HKU-BAL/Clair3?tab=readme-ov-file#call-variants-in-non-diploid-organisms-haploid-calling).

and for this warning ?
**[WARNING] Cannot find any 0/1 variant in pileup output using variant quality cut-off proportion: 0.19999999999999996, total heterozygous variants: 0
[WARNING] Set low variant quality score cut-off to 0.0**
