### ISSUE TITLE
ONT Flowcells 

### ISSUE THREAD

**Issue by fidibidi** [HKU-BAL/Clair3#30]
Hello!

Clair3 has been working great, and thank you guys for sharing such solid tech.

I just have a few questions, I was hoping you could help me with!

I've processed a few PromethION and minION samples through clair3, but those were run using R9.4.1 flowcells. 
My team is interested in ONT tech, but will likely use their newer flowcells the R10.3.

Based on this, is it a bad idea to continue using the existing ONT models in Clair3 to do variant calling? Or would creating a new model trained with these flowcells be the correct step?

**Comment by aquaskyline** [comment]
We haven't seen much R10.3 data, but it seems to be having an error profile substantially different from R9.4.1. So I think a model fine-tuned (not training from scratch) for R10.3 is likely to provide better performance. Maybe we have missed it, but if you know any public R10.3 data of the GIAB samples, we are very interested in training a model for it and testing it out.

**Comment by fidibidi** [comment]
How hard is it to tune as you suggest?

I've been playing around with the data sets found here. https://labs.epi2me.io/gm24385_2020.09/

There are new ones, but these ones were working with ONTs Megalodon / Guppy, while I was having some issues with the newer data.

**Comment by aquaskyline** [comment]
We are downloading the R10.3 data and will see what we can do.

**Comment by fidibidi** [comment]
Thank you!!!
