### ISSUE TITLE
Best practices to use different and/or new models for variant calling

### ISSUE THREAD

**Issue by EmilioKolo** [HKU-BAL/Clair3#302]
Hello, 
I'm trying to add new models from Rerio to my pipeline using Clair3. I'm currently using the prebuilt docker image and need to use a new model. I've come to the solution of building a new image every time I need to use a new model, but it feels a bit rudimentary if I need to do it every other update. Is there an already existing way to use models from Rerio or other similar packages? Rerio in particular says nothing about how to use its models on Clair3 and just redirects to Dorado, which says nothing about variant calling, and this page also seems to say nothing about using models from outside the prebuilt ones. 

Thanks in advance.

**Comment by aquaskyline** [comment]
Agree that releasing models and code together in a prebuilt docker image further saves users from troubles. The current mode on the other hand gives both my team and ONT more flexibility to release new code and models on new chemistries without relying on each other to green light a release. What I suggest (albeit is still an additional trouble) is to input model to a prebuilt docker as user resource file at runtime.

**Comment by EmilioKolo** [comment]
Adding the model to the input files is a great solution for my particular pipeline, thank you.
