### ISSUE TITLE
print_version reports wrong version in 1.0.8

### ISSUE THREAD

**Issue by SamStudio8** [HKU-BAL/Clair3#304]
Clair3 1.0.8 reports itself as v1.0.7 when calling `run_clair3.sh --version`, I think [this line](https://github.com/HKU-BAL/Clair3/blob/main/run_clair3.sh#L4) needs updating.

**Comment by zhengzhenxian** [comment]
Hi @SamStudio8,

Thanks so much for reporting this! We have updated the code and re-pushed the docker image with the updated caller version.

Zhenxian
