### ISSUE TITLE
Read Depth in VCF

### ISSUE THREAD

**Issue by mproberts99** [HKU-BAL/Clair3#305]
Hi,
I found a typo in the output VCF that is causing errors when parsing. The AF parameter has NUMBER=1, so it must have exactly 1 entry, but with the recent update of adding af for all alternate alleles, it has more than one value so it should be NUMBER=G I believe.
##FORMAT=<ID=AF,Number=G,Type=Float,Description="Observed allele frequency in reads, for each ALT allele, in the same order as listed, or the REF allele for a RefCall">
Also, because we use amplicon sequencing, we have to lower the MQ filter to 0 so having the DP automatically display reads with MQ>20 rather than what was specified in the command may be misleading?

**Comment by zhengzhenxian** [comment]
@mproberts99 

Thanks for reporting this! The number of `AF`  has been updated in the header, and we also revised the `DP` description in the header for clarification. Pls kindly re-pull the latest docker image, thanks!

Zhenxian

**Comment by mproberts99** [comment]
Thanks so much!

**Comment by mproberts99** [comment]
Ah sorry @zhengzhenxian , it looks like it should actually be NUMBER=R. I got this error:
Incorrect number of FORMAT/AF values at chr5:70070208, cannot merge. The tag is defined as Number=G, but found
    2 values and 3 alleles. See also http://samtools.github.io/bcftools/howtos/FAQ.html#incorrect-nfields

**Comment by zhengzhenxian** [comment]
@mproberts99 

It seems assigning ‘A’ would be more flexible, I tested with `bcftools merge` and it worked well. I have updated the docker image and pls kindly re-pull, thanks!
