### ISSUE TITLE
Link to fa file is broken 

### ISSUE THREAD

**Issue by v-lakhujani** [HKU-BAL/Clair3#307]
I am following this documentation - https://github.com/HKU-BAL/Clair3/blob/main/docs/quick_demo/ont_quick_demo.md

Here there is a shell script to download - the fa file mentioned here cannot be downloaded

Link - http://www.bio8.cs.hku.hk/clair3/demo/quick_demo/ont/GRCh38_no_alt_chr20.fa

![image](https://github.com/HKU-BAL/Clair3/assets/84500633/e4355561-3230-4c93-83c6-4dc10b752451)

**Comment by zhengzhenxian** [comment]
@v-lakhujani 

Data re-uploaded, pls try again.

**Comment by v-lakhujani** [comment]
Strange that i can download all files except this one and the bam file 
![image](https://github.com/HKU-BAL/Clair3/assets/84500633/67c96f57-a9a7-4b28-ad58-a5ff694bd828)

**Comment by zhengzhenxian** [comment]
The link is good for me. I have attached the file for you to download below:
[GRCh38_no_alt_chr20.fa.gz](https://github.com/HKU-BAL/Clair3/files/15373497/GRCh38_no_alt_chr20.fa.gz)
