### ISSUE TITLE
Troubles with VCFs

### ISSUE THREAD

**Issue by fidibidi** [HKU-BAL/Clair3#31]
Hi!

Thank you guys for everything!

Just having some issues with the vcfs... 

After a run clair3, I've had problems with opening the merge.vcf.gz inside of IGV. 
I haven't run a command with the property --gvcf, yet the file is output as a vcf.gz. 

Whats odd, is then it'll appear on my computer, with the extension not visible. 
merge.vcf ( even though it is actually called merge.vcf.gz )
Trying to open in igv leads to

Unexpected error: Unable to parse header with error: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file, for input source: /Users/fidibidi/Downloads/merge_output (1).vcf. See igv.log for more details

I unzip the file, and manually add a vcf extension to the end... and then I'm able to view them in IGV. 
Am I doing something wrong here?

**Comment by aquaskyline** [comment]
We are not sure about what was wrong. Is it a recurring problem? Could it be some filename caching problems?

**Comment by aquaskyline** [comment]
Would you mind help me with this small experiment? Create `tmp.vcf.gz` by using command `gzip -dc merge_output.vcf.gz | gzip -c > tmp.vcf.gz`, and then upload `tmp.vcf.gz` to S3 and download again to see if the `.gz` would be dropped.

**Comment by fidibidi** [comment]
I will give this a shot!

**Comment by fidibidi** [comment]
Interesting. 

Created the tmp.vcf.gz, uploaded to s3. 

When I redownload the .gz is dropped, and it becomes tmp.vcf. 

(Just to clarify another thing, if the --gvcf flag isn't set, and default is false, should the output not be .gz?)

**Comment by aquaskyline** [comment]
Clair3 compresses the VCF and GVCF outputs using `bgzip`. It is interesting that the `.gz` suffix was still being dropped, but that also indicates the problem might not be with Clair3.
