### ISSUE TITLE
Using a bam file with haplotag information with Clair3 

### ISSUE THREAD

**Issue by eaooms** [HKU-BAL/Clair3#310]
Dear developers,

I have a Illumina haplotagged bam file which i phased with Nanopore data with the WhatsHap phasing tool.

I was wondering if it is possible to pass Clair3 an already phased file and that Clair3 takes the haplotype/haplotag information with it in the variant calling process?

I saw the --phasing_info_in_bam parameter in the full_alignment_training steps but if i add that to a standard Clair3 run i get an error : `run_clair3.sh: unrecognized option '--phasing_info_in_bam'`

kind regards, 
Ewoud

**Comment by aquaskyline** [comment]
Clair3 will do phasing itself, thus ignoring the phasing information provided in bam. Clair3 does its own phasing because no phasing is better than a wrong phasing for Clair3. Clair3's intermediate phasing step is conservative.

**Comment by eaooms** [comment]
Thank you for this information. 
I ask it because i have Nanopore and Illumina data of the same patient and want to combine these techniques to take advantage of the qualities that both techniques have. 
I have read the paper of Clair3mp and also used the tool but i did not give me good results. 

So i wanted to see if i could do my own phasing using WhatsHap and give Clair3 the haplotagged bam. 
But that is not possible?

**Comment by eaooms** [comment]
Thank you for this information.
I ask it because i have Nanopore and Illumina data of the same patient and want to combine these techniques to take advantage of the qualities that both techniques have.
I have read the paper of Clair3mp and also used the tool but i did not give me good results because the tool uses old versions of other tools (like WhatsHap) and is not possible to update.

So i wanted to see if i could do my own phasing using WhatsHap and give Clair3 the haplotagged bam.
But that is not possible?

**Comment by eaooms** [comment]
Thank you for this information.
I ask it because i have Nanopore and Illumina data of the same patient and want to combine these techniques to take advantage of the qualities that both techniques have.
I have read the paper of Clair3mp and also used the tool but i did not give me good results because the tool uses old versions of other tools (like WhatsHap) and is not possible to update.

So i wanted to see if i could do my own phasing using WhatsHap and give Clair3 the haplotagged bam.
But that is not possible?

**Comment by aquaskyline** [comment]
In Clair3-MP, you can use option `--whatshap=` to specify the path of binary to a new version of whatshap.

**Comment by eaooms** [comment]
This issue (https://github.com/HKU-BAL/Clair3-MP/issues/2#issuecomment-1619671171) of Clair3mp tells us that the Clair3mp model is trained on python3.6 and this is not possible to change. The latest version of WhatsHap requires python 3.9 so it is not possible to update that then. 

But the previous question that i asked is not possible? 
(So i wanted to see if i could do my own phasing using WhatsHap and give Clair3 the haplotagged bam.
But that is not possible?)

**Comment by aquaskyline** [comment]
Possible but requires a lot of modifications to the code.

**Comment by eaooms** [comment]
Could you maybe give me an tip on how to do that, do i need to make my own model or how to make this happen?
