### ISSUE TITLE
Error merging GVCFs of multiple samples in cDNA sequencing experiment

### ISSUE THREAD

**Issue by eiwai81** [HKU-BAL/Clair3#311]
Hello Developers,
I am trying to merge gvcfs generated with Clair3 based on reads from a cDNA sequencing experiment involving 10 samples. The details of the workflow so far are as follows:

1. Use Minimap2 to align cDNA reads to a reference (This was done as part of  nf-core/nanoseq pipeline).

2. Generate VCFs and GVCFs for each sample with Clair3 v1.0.8
```
run_clair3.sh \
--bam_fn=${bam_dir}/${sample_name}.sorted.bam \
--ref_fn=${ref} \
--threads=16 \
--platform=${platform} \
--model_path=${model_path} \
--output=${out_dir}/${sample_name} \
--print_ref_calls --gvcf --base_err=0.06 \
--include_all_ctgs \
--no_phasing_for_fa \
--sample_name=${sample_name}
```

3. Sort each GVCF with GATK v4.3.0.0
```
$HOME/.conda/envs/clair3/bin/gatk SortVcf \
-I ${out_dir}/sample_01/merge_output.gvcf.gz \
-O ${out_dir}/sample_01/merge_output.sorted.gvcf.gz
```

4.  Merge sorted GVCFs with GATK v4.3.0.0
```
$HOME/.conda/envs/clair3/bin/gatk CombineGVCFs \
-R ${ref} \
--variant ${out_dir}/sample_01/merge_output.sorted.gvcf.gz \
--variant ${out_dir}/sample_02/merge_output.sorted.gvcf.gz \
.
.
--variant ${out_dir}/sample_09/merge_output.sorted.gvcf.gz \
--variant ${out_dir}/sample_10/merge_output.sorted.gvcf.gz \
-O ${out_dir}/combined.gvcf.gz
```

However, this still raises an error: **The elements of the input Iterators are not sorted according to the comparator htsjdk.variant.variantcontext.VariantContextComparator**

May I also mention that headers of the GVCFs have variable lengths. For example `bcftools view -h ${sample_name}/merge_output.gvcf.gz | wc -l` shows:
sample01: 758
Sample 04: 618
Sample_10: 467

Also, GLNexus fails to merge the GVCFs as well. 

I would greatly appreciate any recommendations or suggestions on this matter. 

Thank you.

**Comment by aquaskyline** [comment]
1. What GLNexus reports? 2. What caused the variable length headers? You can also send over the headers so we can check for you.

**Comment by eiwai81** [comment]
@aquaskyline 
1. GLNexus reports that gvcfs are "Invalid" and "Incompatible".  Also, that "The reference contigs must match the database configuration exactly".
2. It could be that the list of chromosome/contig names  do not match. Probably related to the same issue causing GLNexus to fail. Will it be alright to send the headers to your mail?

**Comment by aquaskyline** [comment]
Are the headers already different in length after step 2 before step 3?

**Comment by eiwai81** [comment]
Yes. The header section in the merge_output.gvcf.gz files prior to sorting are:
758
618
467

**Comment by aquaskyline** [comment]
thanks for the info. could you please send the headers to ***@***.*** 原始邮件 --------发件人： eiwai81 ***@***.***>日期： 2024年6月15日周六14:10收件人： HKU-BAL/Clair3 ***@***.***>抄送： Ruibang Luo ***@***.***>, Mention ***@***.***>主    题： Re: [HKU-BAL/Clair3] Error merging GVCFs of multiple samples in cDNA sequencing experiment (Issue #311)
Yes. The header section in the merge_output.gvcf.gz files prior to sorting are:
758
618
467

**Comment by eiwai81** [comment]
I have done so. 

Thank you.

**Comment by zhengzhenxian** [comment]
@eiwai81 The error seems to be the contig names not matching among different sample headers. Some samples have some contigs names that are missing in other samples. 

We suggest you make a union set of contigs from all the samples and then modify the header manually for each sample before GATK CombineGVCFs. Also, pls also make sure all the samples are aligned with the same reference genome.

**Comment by eiwai81** [comment]
@zhengzhenxian I had thought to do this but was thinking there was something that could be done upstream. I have used the same reference sequence in all steps.

It is a bit odd that the GVCFs have different header lengths whereas the VCFs produced from the same samples in the same command all the have the same header lengths. 

Many thanks for your help with this issue.
