### ISSUE TITLE
Run does not respect AF settings

### ISSUE THREAD

**Issue by Krannich479** [HKU-BAL/Clair3#314]
Dear Clair3 dev team,

## Background
I am using Clair3 for SNV/indel detection from ONT sequence data. The sequence data is from an amplicon sequencing experiment (high read coverage) of a mixed SARS-CoV-2 sample.

## Clair3 call
```Nextflow
run_clair3.sh \
    --bam_fn="${bam}" \
    --bed_fn="${params.bed}" \
    --ref_fn="${params.ref}" \
    --threads="${task.cpus}" \
    --platform="ont" \
    --model_path="${params.model}" \
    --snp_min_af=0.08 \
    --indel_min_af=0.15 \
    --no_phasing_for_fa \
    --var_pct_full=1 \
    --ref_pct_full=1 \
    --output="${baseDir}/${params.outdir}"
```

## Issue
The run of Clair3 does not respect the set `snp_min_af` and `indel_min_af`. Does any combination of parameters here interfere or overwrite each other? In the `merge_output.vcf.gz` as well as the `full_alignment.vcf.gz` I see a line 
```
NC_045512.2     22386   .       TTC     T       16.05   PASS    F       GT:GQ:DP:AD:AF  0/1:16:846:634,9:0.0106
```
which should not be present according to the parameters because AF=0.01.

## Expected behavior
I expected to not have any variant records (at least not with a FILTER=PASS) in the VCF files that are of AF lower than 0.08 and 0.15 for SNPs and indels, respectively.

## Additional info
Clair3 version: 1.0.8
Clair3 model: r1041_e82_400bps_hac_g632
OS: Ubuntu 20.04.6 LTS

**Comment by aquaskyline** [comment]
Please check if this addresses your concern [#253](https://github.com/HKU-BAL/Clair3/issues/253#issuecomment-1855197920).

**Comment by Krannich479** [comment]
That does help explaining my findings. Thanks a lot!
