### ISSUE TITLE
Correct variant found by pileup is changed after full alignment

### ISSUE THREAD

**Issue by f-ferraro** [HKU-BAL/Clair3#316]
Hi, 
Thanks for your work with clair3! 

We are running clair3 v1.0.9 via docker and we encountered an expected result that we would like your opinion about. 

We have a previously known and validated variant in EHMT1.

We recently sequenced the same sample with ONT (SUP basecalling, dna_r10.4.1_e8.2_400bps_sup@v5.0.0) and we didn't find this variant in the clair3 merge_output.vcf. We initially suspected something went wrong with the sequencing itself but the variant is clearly visible in the bam. We however realized that the variant is found in the pileup vcf but it's changed into another variant after the full alignment. Below you can see the screenshot of the variant and zooming out a bit more of the region. 
Do you perhaps have any suggestions? 
Thanks in advance! 
Federico 

![image](https://github.com/HKU-BAL/Clair3/assets/58588827/b34d6c33-d44d-4119-9ad0-5f0ffdc6cfd8)

![image](https://github.com/HKU-BAL/Clair3/assets/58588827/bebf3e4a-0dd9-4f76-be13-221f4bf0cca9)

**Comment by aquaskyline** [comment]
Weird, would you be able to send us a minibam (only the reads spanning the variant of interest) so we could look into the details.
