### ISSUE TITLE
Clair3 GVCF created file is 1bp of the end sequence so validatevariants fails

### ISSUE THREAD

**Issue by klausyboi** [HKU-BAL/Clair3#317]
Hi,

Im trying to combine my gvcfs, first using gatks validatevariants but i get the error:

A GVCF must cover the entire region. Found 16 loci with no VariantContext covering it. The first uncovered segment is:Pf3D7_01_v3:640851

Looking at a sample that worked from illumina the bp is always 1 short for each chromosome and 640851 is the end of the chromosome in this case so i think thats the problem.

I used clair3 to get the gvcf using:
barcode=\$(basename "\$barcode_dir")
            run_clair3.sh \\
            --bam_fn=barcodes/\$barcode/calls_"\$barcode"_sorted.bam \\
            --ref_fn=${ref_seq} \\
            --threads=${threads} \\
            --platform="ont" \\
            --model_path=/mnt/storageG1/data/software/rerio/clair3_models/r1041_e82_${bps}_${type}_v500 \\
            --output=vcf/\$barcode/ \\
            --include_all_ctgs \\
            --gvcf
            
I then used sortvcf from gatk because the variants were all in the wrong order and I was getting this error, hoping it would fix it but alas it did not.
            
Any help with this is greatly appreciated.

Thanks

**Comment by aquaskyline** [comment]
Could you please send over the reads and reference sequence of `Pf3D7_01_v3`. We will try the repeat the problem on our side.

**Comment by klausyboi** [comment]
[ref genome](https://github.com/user-attachments/files/16064418/Pfalciparum.genome.zip)
[my bam](https://drive.google.com/file/d/1Xg6gWX5r5NFmzulDgddIHAVQd-907soH/view?usp=sharing)
[my fastq if you wanted to start from there which was created from the bam anyway but otherwise id be sending over lots of pod5s](https://drive.google.com/file/d/1Ee9gmCUFex7wwU7_fkejPK35T4RRbX6G/view?usp=sharing)

**Comment by zhengzhenxian** [comment]
@klausyboi  Thanks for sharing the data; we will fix the gvcf range issue in the next release.

**Comment by zhengzhenxian** [comment]
Fixed in v1.0.10.
