### ISSUE TITLE
[ERROR] Model path not found

### ISSUE THREAD

**Issue by Wshengquan** [HKU-BAL/Clair3#319]
Hi，
I have used Rerio to download the models for R10.4.1 data and I run :
run_clair3.sh 
--bam_fn=../LR1D.sort.bam 
--ref_fn=/share/home/yzwl_hanxs/basecalling/referenceGene/Sus_scrofa.Sscrofa11.1.dna_sm.toplevel.fa 
--threads=4 --platform='ont' 
--model_path='/share/home/yzwl_hanxs/app/rerio/clair3_models/r1041_e82_400bps_sup_g615_model' 
--output=/share/home/yzwl_hanxs/company-third/LR1D/bam/SNP
And then the error was reported：
[INFO] CLAIR3 VERSION: v1.0.8
[INFO] BAM FILE PATH: /share/home/yzwl_hanxs/company-third/LR1D/bam/SNP/../LR1D.sort.bam
[INFO] REFERENCE FILE PATH: /share/home/yzwl_hanxs/basecalling/referenceGene/Sus_scrofa.Sscrofa11.1.dna_sm.toplevel.fa
[INFO] MODEL PATH: /share/home/yzwl_hanxs/app/rerio/clair3_models/r1041_e82_400bps_sup_g615_model
[INFO] OUTPUT FOLDER: /share/home/yzwl_hanxs/company-third/LR1D/bam/SNP
[INFO] PLATFORM: ont
[INFO] THREADS: 4
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: /share/home/yzwl_hanxs/anaconda3/envs/clair3
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] LONGPHASE PATH: EMPTY
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] PHASING PROPORTION: 0.7
[INFO] MINIMUM MQ: 5
[INFO] MINIMUM COVERAGE: 2
[INFO] SNP AF THRESHOLD: 0.08
[INFO] INDEL AF THRESHOLD: 0.15
[INFO] BASE ERROR IN GVCF: 0.001
[INFO] GQ BIN SIZE IN GVCF: 5
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: False
[INFO] ENABLE REMOVING INTERMEDIATE FILES: False
[INFO] ENABLE LONGPHASE FOR INTERMEDIATE VCF PHASING: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING WHATSHAP: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING LONGPHASE: False
[INFO] ENABLE HAPLOTAGGING FINAL BAM: False
[INFO] ENABLE LONG INDEL CALLING: False
[INFO] ENABLE C_IMPLEMENT: True

ESC[31m[ERROR] Model path not foundESC[0m

and then I checked this :
![1720265139733](https://github.com/HKU-BAL/Clair3/assets/145557567/71ba7c9f-674e-4eeb-8d13-526417ea7b7b)
Why does this happen
Any help to overcome this is appreciated!

Best

**Comment by schmart95** [comment]
I have the same problem using clair3 with conda.
I give the absolute path for the model like this:
`--model_path=/r1/people/user/bin/miniforge3/envs/clair3/bin/models/full_alignment.data-00000-of-00002`
but it still returns:
`[ERROR] Model path not found`
I also checked that the file is model is actually located there.

Any ideas why that is?

**Comment by sachingadakh** [comment]
I have the same exact issue

**Comment by liuqianhn** [comment]
I have the same issue. Any solution?

**Comment by aquaskyline** [comment]
Please give the quick demos https://github.com/HKU-BAL/Clair3?tab=readme-ov-file#quick-demo a look.

**Comment by dwells-eit** [comment]
> I have the same problem using clair3 with conda. I give the absolute path for the model like this: `--model_path=/r1/people/user/bin/miniforge3/envs/clair3/bin/models/ont/full_alignment.data-00000-of-00002` but it still returns: `[ERROR] Model path not found` I also checked that the file is model is actually located there.
> 
> Any ideas why that is?

In your case try `--model_path=/r1/people/user/bin/miniforge3/envs/clair3/bin/models/ont/`

clair3 requires both the `full_alignment.*` and `pileup.*` models to work. So point at the folder containing them rather than any specific file.
