### ISSUE TITLE
upgrading longphase to 1.7.3

### ISSUE THREAD

**Issue by signalbox2** [HKU-BAL/Clair3#321]
There is a bug in longphase 1.7 that causes an error on reading FASTA files.  For example:

```reading reference ... [E::fai_load3_core] Failed to open FASTA file```

This has been fixed in longphase 1.7.3:

[https://github.com/twolinin/longphase/issues/74](url)

Please can you update longphase in Clair3?  We are using ClairS but presumably if fixed in Clair3 it will be picked up in the conda clair3-illumina package used by ClairS?

**Comment by aquaskyline** [comment]
Will update longphase in the next version.

Before that, the option `--longphase` allows users to specify their own longphase binary.

**Comment by aquaskyline** [comment]
upgraded in v1.0.10
