### ISSUE TITLE
Clair3 with T2T aligned reads

### ISSUE THREAD

**Issue by DHmeduni** [HKU-BAL/Clair3#322]
Hi,
I'm having problems getting clair3 to call variants in T2T that it will call in Hg38, done alot of troubleshooting and the variants are called in the merge_output.vcf but not the full_alignment... in fact in full_alignment it is making strange calls and missing all obvious SNVs.
Dave

**Comment by aquaskyline** [comment]
Hi Dave,

Is it possible that you can show us a few examples.
