### ISSUE TITLE
Which model?

### ISSUE THREAD

**Issue by ascialla** [HKU-BAL/Clair3#323]
Hi all, I don't know if this is the correct section (first time posting on github, sorry!) but I would like to do a variant call analysis, I have 3 DNA samples sequenced with ONT platform with an old model r9.4.1_e8_sup@v3.3 and I was wondering which model should or could I use? 

Thanks in advance 🙏🏼

**Comment by schmart95** [comment]
I was also wondering about that.
To me it seems like there are 6 models.
`full_alignment.data-00000-of-00002  full_alignment.data-00001-of-00002  full_alignment.index  pileup.data-00000-of-00002  pileup.data-00001-of-00002  pileup.index`
But what is the difference between them?
Where can I read up on that?
