### ISSUE TITLE
Exit in environment checking

### ISSUE THREAD

**Issue by xiaolongliang** [HKU-BAL/Clair3#325]
Hello,
I encountered an issue while running Clair3. Could you please advise me on how to resolve this problem?

[INFO] Check environment variables
[INFO] Create folder /opt/synData2/2024/kazak_sheep/SNP/BH2/log
[INFO] Create folder /opt/synData2/2024/kazak_sheep/SNP/BH2/tmp/pileup_output
[INFO] Create folder /opt/synData2/2024/kazak_sheep/SNP/BH2/tmp/merge_output
[INFO] Create folder /opt/synData2/2024/kazak_sheep/SNP/BH2/tmp/phase_output
[INFO] Create folder /opt/synData2/2024/kazak_sheep/SNP/BH2/tmp/gvcf_tmp_output
[INFO] Create folder /opt/synData2/2024/kazak_sheep/SNP/BH2/tmp/full_alignment_output
[INFO] Create folder /opt/synData2/2024/kazak_sheep/SNP/BH2/tmp/phase_output/phase_vcf
[INFO] Create folder /opt/synData2/2024/kazak_sheep/SNP/BH2/tmp/phase_output/phase_bam
[INFO] Create folder /opt/synData2/2024/kazak_sheep/SNP/BH2/tmp/full_alignment_output/candidate_bed
[INFO] --include_all_ctgs not enabled, use chr{1..22,X,Y} and {1..22,X,Y} by default
[WARNING] No contig intersection found, output header only in /opt/synData2/2024/kazak_sheep/SNP/BH2/merge_output.vcf.gz
[INFO] Exit in environment checking

**Comment by zhengzhenxian** [comment]
@xiaolongliang 

Pls try to enable the `--include_all_ctgs` option.

**Comment by xiaolongliang** [comment]
@zhengzhenxian Thanks a lot, it worked!
