### ISSUE TITLE
REF=TGTGB

### ISSUE THREAD

**Issue by minw2828** [HKU-BAL/Clair3#326]
Hello,

I hope you're doing well. Thank you for developing this tool! 😊

There is an unknown locus at `(hg38) chr3:16,902,859-16,902,898` labeled as `TGTGN`, which I've highlighted in yellow in the attached IGV and UCSC screenshots.

<img width="1325" alt="Figure1" src="https://github.com/user-attachments/assets/0610418d-5d8d-4652-8001-9b3af8044aeb">

![Figure2](https://github.com/user-attachments/assets/d6245e54-3475-4cfa-80fb-4a7986a7dc04)

Clair3 has identified this site in the REF field as `TGTGB`:
```
gunzip -c tumor.clair3.vcf.gz | grep TGTGB
chr3	16902879	.	TGTGB	T	25.68	PASS	P	GT:GQ:DP:AD:AF	1/1:25:25:2,22:0.88
``` 

`TGTGB` has caused the following error when I tried to load the VCF file into IGV: 
```
Error loading features for interval: chr3:16902858-16902898 htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 215: unparsable vcf record with allele TGTGB
```

When I tested with TGTGN, the file loaded successfully.

I just wanted to bring this to your attention.

Many thanks,
Min

**Comment by aquaskyline** [comment]
which clair3 version were you using?

**Comment by minw2828** [comment]
This one: [hkubal/clair3:latest](https://hub.docker.com/layers/hkubal/clair3/latest/images/sha256-89e1ad86d5982a870f423ae29499a8b6eb1551eb88c42834e691facb8c5797fc?context=explore)
sha256:89e1ad86d5982a870f423ae29499a8b6eb1551eb88c42834e691facb8c5797fc

**Comment by aquaskyline** [comment]
Unless you have enabled `--keep_iupac_bases`, all non ACGT bases will be converted to 'N'. The topic was discussed in [#153](https://github.com/HKU-BAL/Clair3/issues/153).

**Comment by minw2828** [comment]
Thank you @aquaskyline! 👍
