### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by osvatic** [HKU-BAL/Clair3#330]
I installed Clair3 using the bioconda and anaconda (once each) and get a broken pipe error when running this following command on data.

```
Clair3/run_clair3.sh --bam_fn=$DIR/10N.286.55.E8_N03_JMF-2403-01-0004A.mapped.sorted.bam --ref_fn=$DIR/../../genomes/10N.286.55.E8_N03.fa --threads=8 --platform=ilmn --model_path=Clair3/models/ilmn/ --output=$DIR/${f%%.bam}_CLAIR3 --no_phasing_for_fa --haploid_precise --include_all_ctgs
```
I am using an illumina dataset that was aligned to the reference and sorted before running the command. 

Is there a clear reason that this isn't working?

[run_clair3.log](https://github.com/user-attachments/files/16496076/run_clair3.log)

**Comment by zhengzhenxian** [comment]
Seem tensorflow version issue. Could you try [docker installation](https://github.com/HKU-BAL/Clair3?tab=readme-ov-file#option-1--docker-pre-built-image) or [singularity installation](https://github.com/HKU-BAL/Clair3?tab=readme-ov-file#option-2-singularity)?
