### ISSUE TITLE
Clair3 with polyploids

### ISSUE THREAD

**Issue by ewoutcrombez** [HKU-BAL/Clair3#331]
Hello,

Thank you very much for the development of this tool!
I saw in the README that it is possible to call variants in non-diploid organisms. 
Is this meant for polyploid genomes? And in what way does it differ with the diploid variant calling? I do not seem to find anything about it in the publication and I would like to use Clair3 for tetraploid data. Many thanks in advance.

**Comment by zhengzhenxian** [comment]
Basically no. Clair3 applies a strong diploid assumption to its output.
