### ISSUE TITLE
No vcf output from clair3 run

### ISSUE THREAD

**Issue by lynnjo** [HKU-BAL/Clair3#333]
I have setup clair3 to run via docker and while the output from the command shows processing happening, no output file is written.  The BAM file  I'm using was created by aligning illumina short reads against a reference fasta file.

Here is my script to run clair3 via docker:

```
INPUT_DIR=/workdir/lcj34/phg_v2/clair3/p39top39BamFastas
OUTPUT_DIR=/workdir/lcj34/phg_v2/clair3/p39top39_clair3Output
THREADS="10"

docker1 run \
        -v ${INPUT_DIR}/:/input/ \
        -v ${OUTPUT_DIR}/:/output/ \
        hkubal/clair3:latest \
        /opt/bin/run_clair3.sh \
        --ref_fn=/input/P39.fa \
        --bam_fn=/input/P39toP39MergedBams.sorted.bam \
        --ctg_name="chr9" \
        --output=${OUTPUT_DIR} \
        --platform="ilmn" \
        --model_path="/opt/models/ilmn" \
        --threads=${THREADS}
```
I"ve attached the output file from the run.  I don't see any errors and it appears to be processing the data.  At the end it says "Finished calling, output file: ..." What would prevent the vcf file from being created ?  I ran this twice with the same result.  

[clair3p39top39_output.txt](https://github.com/user-attachments/files/16581083/clair3p39top39_output.txt)

**Comment by zhengzhenxian** [comment]
@lynnjo 

In your command,  the ${OUTPUT_DIR} is mounted in `/output` in your docker image, pls try to use the `--output=/output` instead of `--output=${OUTPUT_DIR}`.

**Comment by lynnjo** [comment]
Thank you - that was it!
