### ISSUE TITLE
Missing calls with --min_coverage=1

### ISSUE THREAD

**Issue by gc-content** [HKU-BAL/Clair3#334]
Hello,

I have a specific use case where I need to call variants even if the position is covered by only one read. However, setting --min_coverage=1 doesn't seem to lower the limit below the default, as only positions covered by at least two reads are reported.

Is there any way to configure Clair for this purpose?

Best regards,
Piotr

**Comment by aquaskyline** [comment]
No, Clair3 cannot do calling at coverage 1. You might want to explore `samtools mpileup` for the purpose.

**Comment by gc-content** [comment]
Thanks!
