### ISSUE TITLE
Mito variant calling

### ISSUE THREAD

**Issue by leonschuetz** [HKU-BAL/Clair3#338]
Hello,

for our samples we would like to call also variants on chrM. Would you recommend to simply add the region to the target region, or to do a separate calling with adjusted parameters (and if so, which settings do you recommend)?
(On the short-read data we do mito calling in an extra step with adjusted parameters ( no_ploidy, ...) and merge the files afterwards.) 

Best,
Leon

**Comment by aquaskyline** [comment]
I suggest an extra step for mito calling only, using the following parameters:
`chunk_num=-1 --haploid_sensitive --ctg_name="chrM"`
