### ISSUE TITLE
Clair3 didn't run the final merge step!

### ISSUE THREAD

**Issue by fidibidi** [HKU-BAL/Clair3#38]
Hello!

The other day, Clair3 appeared to be finished, however upon investigation, I noticed that the final merge output was never created. 

The last lines of the log are:

`[mpileup] 1 samples in 1 input files
Total process positions in chrY : 10000
Total time elapsed: 197.78 s

real	567m0.735s
user	8014m59.665s
sys	191m58.762s
[INFO] 7/7 Merge pileup vcf and full alignment vcf
`

I have the full-alignment and the pileup files, so I decided to try and run the MergeVcf.py on them. 

However I'm not sure I understand how, and if this is even a good idea? 

I tried to run

`python MergeVcf.py`

and received the following error

`Traceback (most recent call last):
  File "MergeVcf.py", line 9, in <module>
    from shared.utils import subprocess_popen, str2bool
ModuleNotFoundError: No module named 'shared'`

Any help greatly appreciated!
Thanks.

**Comment by zhengzhenxian** [comment]
Hi,
Thanks for trying out Clair3. For us to pinpoint the problem, could you send us the running log at `${OUTPUT_DIR}/run_clair3.log` and  `${OUTPUT_DIR}/log` folders to my email address zxzheng@cs.hku.hk? Much appreciated.

**Comment by fidibidi** [comment]
Hey Zheng!

I sent along the logs. 

One other question I had though was:

Is it feasible to run that MergeVcf.py script if I have the full alignment and pileup vcfs? 
And if so, how one does that? 

Thanks!

**Comment by fidibidi** [comment]
Thank you guys!

For anyone in the future here was the resolution via email:
`
Dear Fidi,

      Really appreciated for providing your logs! We have checked in detail and found that Clair3 stopped at the last step(merge pileup and full-alignment vcf) without any warning or errors. This behaviour is very strange and new to us we have no clue on the real cause. Not sure the memory cases this and we will continue to find the reason.

      For your convenience, I have attached a script for you to finish the last step. And maybe you just need to activate Clair3 conda environment and make sure you are in Clair3 source code directory (there is a clair.py in the same folder with run_clair3.sh). Then it will output exactly the same result of Clair3 normal workflow(merge_output.vcf.gz). 

     Hope it would work for you!  Pls kindly let us know if you have any questions!

     Really for your precise comments and support in Clair3! 

Wishes,
zhenxian
`
