### ISSUE TITLE
Segmentation fault while running hap.py

### ISSUE THREAD

**Issue by disha-14** [HKU-BAL/Clair3#39]
Hey! So I was running the 'run hap.py for benchmarking' script from the ont_quick_demo file and ran into an error. Variant calling ran perfectly well and I also got the required vcf files, but while running the hap.py script I ran into an issue saying 'Segmentation Fault'. Is there any way I can fix this?
![error_stuff](https://user-images.githubusercontent.com/77445861/125983974-01047108-4c53-46b7-be11-55eb49be0a5c.png)

**Comment by zhengzhenxian** [comment]
Hi, 

Not sure it is bed format problem, is it possible to paste the whole hap.py command (using `echo`) for us to better pinpoint the problem? 

Thanks!

**Comment by disha-14** [comment]
This is the hap.py command that I ran -

INPUT_DIR="/home/u72582/project/Clair3"
OUTPUT_DIR="/home/u72582/project/Clair3"
BASELINE_VCF_FILE_PATH="Original/temp_o/merge_output.vcf.gz"
BASELINE_BED_FILE_PATH="bed_file.bed"
OUTPUT_VCF_FILE_PATH="Pruned/temp_p/merge_output.vcf.gz"
REF="reference.fasta"
CONTIGS="1"
START_POS=13
END_POS=5354543
THREADS=24
source activate happy-env
conda install -c bioconda rtg-tools -y 
hap.py \
    ${INPUT_DIR}/${BASELINE_VCF_FILE_PATH} \
    ${OUTPUT_DIR}/${OUTPUT_VCF_FILE_PATH} \
    -f "${INPUT_DIR}/${BASELINE_BED_FILE_PATH}" \
    -r "${INPUT_DIR}/${REF}" \
    -o "${OUTPUT_DIR}/happy" \
    -l ${CONTIGS}:${START_POS}-${END_POS} \
    --engine=vcfeval \
    --threads="${THREADS}" \
    --pass-only

Thanks!

**Comment by zhengzhenxian** [comment]
It seems that you are using Clair3 output as truth vcf for hap.py benchmarking, we have tried to use Clair3 output vcf but failed to repeat your errors. We might need more knowledge to pinpoint the errors occurring in hap.py.

**Comment by disha-14** [comment]
Hey!

I would like to apologize for the delay in replying to the previous comment
I wanted to evaluate the vcf file that was produced after variant calling. Could you please help me out with the procedure I need to follow to do so. 

Thanks!

**Comment by zhengzhenxian** [comment]
Hi,
    We have tried to repeat your errors but still have no clues. It should be an unknown segmentation fault occurring in hap.py.  You might want to visit https://github.com/Illumina/hap.py for more details of user guidelines. Hope it would help to solve your problem.

**Comment by disha-14** [comment]
Hey!

So the issue was with the bed file. I had put the wrong start and end positions in the bed file. My end position was greater than the sequence length due to which this segmentation fault had occurred. 

I still have a question though. How exactly do we generate the end position in the bed file so that we can go through the whole sequence?

Thanks!

**Comment by zhengzhenxian** [comment]
That's really great that you have fixed the issue! Actually, you can discard the `--bed_fn` option if you wanna scan the whole BAM file without bed region restriction. Clair3 will call all candidates that meet the minimum allelic frequency and coverage requirement. 

Optionally, you can check your reference index file (`cat fa.fai`) to get the total length and offset of each contig, you might check [samtools faidx](http://www.htslib.org/doc/faidx.html) for more details. Using the offset plus length of each contig as bed region is quite adequate to cover all aligned reads.

Hope it help!
