### ISSUE TITLE
Option to call SNPs only

### ISSUE THREAD

**Issue by yekaizhou** [HKU-BAL/Clair3#40]
Hi,

Thanks for developing Clair3. It is really fast and accurate for small variant calling.

I am wondering if Clair3 can have the option to be more specific to call SNPs only?

Thanks!

**Comment by zhengzhenxian** [comment]
Hi,

We will try to add an option to call candidates that only pass SNP minimum AF in the next release. 

Thanks!

**Comment by zhengzhenxian** [comment]
Hi,

We have added the `--call_snp_only` option to only call SNP only, pls feel free to have a try.

Thanks!
