### ISSUE TITLE
Which Reference to use during Training?

### ISSUE THREAD

**Issue by champ1994** [HKU-BAL/Clair3#43]
![clair3](https://user-images.githubusercontent.com/36463244/128860878-26118c6c-761b-4f49-880b-641076197e88.png)

In the highlighted portion

The reference should be the standard GRCh38 or GRCh37 fasta file OR as mentioned in the example part: the fasta seq of the sample being trained ??

**Comment by zhengzhenxian** [comment]
Hi,

There is no strict requirement for you to use the specific reference genome, just make sure the aligned BAM file is consistent with the reference file. We used GRCh38 to train Clair3's model and here is the [training data](https://github.com/HKU-BAL/Clair3/blob/main/docs/training_data.md) for your reference. 

Thanks!

**Comment by champ1994** [comment]
Thank you for clearing my doubt.
