### ISSUE TITLE
Does it require root to run the singularity image?

### ISSUE THREAD

**Issue by charliechen912ilovbash** [HKU-BAL/Clair3#44]
Hi, I am using singularity image to run `/opt/bin/run_clair3.sh`
It run successfully when I add `sudo` before `singularity exec /home/charlie/singularity_imgs/clair3-latest.simg \
  /opt/bin/run_clair3.sh`
and came out the following message  if I did not add `sudo`

```
[INFO] Check environment variables
Fatal Python error: Py_Initialize: Unable to get the locale encoding
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
PermissionError: [Errno 13] Permission denied: '/opt/conda/envs/clair3/lib/python3.6/encodings/__init__.py'
/opt/bin/scripts/clair3.sh: line 103: 20817 Aborted                 (core dumped) ${PYTHON} ${CLAIR3} CheckEnvs --bam_fn ${BAM_FILE_PATH} --bed_fn ${BED_FILE_PATH} --output_fn_prefix ${OUTPUT_FOLDER} --ref_fn ${REFERENCE_FILE_PATH} --vcf_fn ${VCF_FILE_PATH} --ctg_name ${CONTIGS} --chunk_num ${CHUNK_NUM} --chunk_size ${CHUNK_SIZE} --include_all_ctgs ${INCLUDE_ALL_CTGS} --threads ${THREADS} --python ${PYTHON} --pypy ${PYPY} --samtools ${SAMTOOLS} --whatshap ${WHATSHAP} --parallel ${PARALLEL} --qual ${QUAL} --sampleName ${SAMPLE} --var_pct_full ${PRO} --ref_pct_full ${REF_PRO} --snp_min_af ${SNP_AF} --indel_min_af ${INDEL_AF}
```

I could run `run_clair3.sh ` with conda installation successfully.

**Comment by zhengzhenxian** [comment]
Hi,

Unfortunately, the singularity image could finish running without `sudo` authentication using a normal user in my testing environment.  It seems that it is a permission issue for the `/opt` directory in singularity.  You might try to open up the `/opt` permission with `%post` building file to build the singularity image, here is a similar [issue](https://github.com/hpcng/singularity/issues/1616#issuecomment-393699521) for your reference.  

Preferably, I would suggest you use the conda environment as it would produce the same result as the docker or singularity environment. 

Hope it helps you, thanks!

**Comment by charliechen912ilovbash** [comment]
I see, thanks for the information.
Is it possible to provide the singularity definition file?
I could do it by myself on some level but it will be better if there is an official one, thanks : )

**Comment by zhengzhenxian** [comment]
Currently, we did not have a separate singularity definition file because we directly built the singularity sandbox from a pre-built docker image using `singularity pull docker://hkubal/clair3:latest`. 

As the docker image could be built using Dockerfile in [installation option 5](https://github.com/HKU-BAL/Clair3#option-5-docker-dockerfile), you could optionally build a local docker image and then convert it to a singularity image, like:
```
git clone https://github.com/hku-bal/Clair3.git
cd Clair3

docker build -f ./Dockerfile -t local/clair3 .
singularity build clair3.sif docker-daemon://local/clair3:latest
```

Hope it helps!

**Comment by charliechen912ilovbash** [comment]
Thanks very much! 
By the way, what paper should I cite if I use Clair3?
