### ISSUE TITLE
ERROR: Too many open files

### ISSUE THREAD

**Issue by stefandiederich** [HKU-BAL/Clair3#47]
Hi,

I have run Clair on WGS ONT data an got the following error:
```
...
[mpileup] 1 samples in 1 input files
Total processed positions in chrY (chunk 4/4) : 9661
Total time elapsed: 129.47 s

real    186m27.439s
user    8776m44.801s
sys     77m56.150s
Traceback (most recent call last):
  File "/media/Data/clair3/clair3/bin/scripts/../clair3.py", line 89, in <module>
  File "/media/Data/clair3/clair3/bin/scripts/../clair3.py", line 83, in main
  File "/media/Data/clair3/clair3/bin/preprocess/SortVcf.py", line 193, in main
  File "/media/Data/clair3/clair3/bin/preprocess/SortVcf.py", line 132, in sort_vcf_from
OSError: [Errno 24] Too many open files: '/media/Data/NA12878_run1-5/NA12878_run1-5.vcf/tmp/full_alignment_output/full_alignment_chrX.101_193.vcf'

real    735m16.230s
user    31395m25.386s
sys     151m23.800s
(/media/Data/clair3/clair3) die9s@k-hg-srv3:/media/Data/clair3/clair3/bin>
```

Do you have any idea what migth be the cause of this error?
Bests
Stefan

**Comment by aquaskyline** [comment]
This is a system limitation that was reported in a previous issue, please take a look at https://github.com/HKU-BAL/Clair3/issues/45#issuecomment-909946616

**Comment by stefandiederich** [comment]
Thanks for your reply. I will test version 0.1.6 as soon as it is released. If it is not working either, I will increase the ulimit. 

Bests Stefan

**Comment by zhengzhenxian** [comment]
Hi,

Version 0.1-r6 released with lower `ulimit -n` requirement, please feel free to have a try, Thanks!

**Comment by aquaskyline** [comment]
@stefandiederich does the new version solve your problem?
