### ISSUE TITLE
Homo / heterozygous call issue

### ISSUE THREAD

**Issue by kim-fehl** [HKU-BAL/Clair3#49]
We noticed the presence of such line in *.vcf result file: 
`chr1	13116	.	T	G	15.23	PASS	P	GT:GQ:DP:AD:AF:PL	1/1:15:27:18,9:0.3333:22,27,0`

With AD of 18,9 shouldn't the GT be heterozygous (0/1) and not homozygous (1/1) as in output?

Full command from the log:

```bash
clair3.sh --bam_fn fk4034.merged.hg19.bam --ref_fn hg19.fna --threads 24 --model_path ont_guppy5 \
--platform ont --output clair3.gvcf --bed_fn=EMPTY --vcf_fn=EMPTY --ctg_name=EMPTY \
--sample_name=SAMPLE --chunk_num=0 --chunk_size=5000000 --samtools=samtools --python=python3 \
--pypy=pypy3 --parallel=parallel --whatshap=whatshap --qual=2 --var_pct_full=0.3 --ref_pct_full=0.1 \
--snp_min_af=0 --indel_min_af=0 --pileup_only=False --gvcf=True --fast_mode=False --call_snp_only=False \
--print_ref_calls=False --haploid_precise=False --haploid_sensitive=False --include_all_ctgs=False \
--no_phasing_for_fa=False --pileup_model_prefix=pileup --fa_model_prefix=full_alignment
```

**Comment by aquaskyline** [comment]
Not necessarily if the Ts at the position are coexisting with a certain
pattern of mismatches in its adjacency. In ONT reads, there are a few cases
that authentic homozygous variant is having sub-0.5 allele frequency.
Technically, allele frequency is just a factor to be consider by the Clair3
model, together with the signals in the flanking positions. If the supports
for the reference allele are suspicious, they could be ignored, thus
leading to a 1/1 decision with a high reference allele count. The variant
quality is relatively low in your case, so it could either be a mistake by
Clair3 or it's in fact a 1/1.
