### ISSUE TITLE
Cannot write to --joblog parallel_1_call_var_bam_pileup.log

### ISSUE THREAD

**Issue by MeHelmy** [HKU-BAL/Clair3#5]
Hi, 

I'm  using Clair3 as the following:
`${HOME}/Clair3/run_clair3.sh --bam_fn ~/projects/tests/clair3/HG002.ONT.bam --ref_fn ~/hs37d5_mainchr.fa --threads 10 --platform ont --model_path ~{HOME}/Clair3/modules/ont --output SNVs`

I have this error:

`+ Clair3/scripts/clair3.sh --bam_fn ~/projects/tests/clair3/HG002.ONT.bam --ref_fn ~/hs37d5_mainchr.fa --threads 10 --model_path ${HOME}/Clair3/modules/ont --platform ont --output SNVs --bed_fn=EMPTY --vcf_fn=EMPTY --ctg_name=EMPTY --sample_name=EMPTY --chunk_num=0 --chunk_size=5000000 --samtools=samtools --python=python3 --pypy=pypy3 --parallel=parallel --whatshap=whatshap --qual=0 --var_pct_full=0.3 --ref_pct_full=0.3 --snp_min_af=0.0 --indel_min_af=0.0 --pileup_only=False --gvcf=False --fast_mode=False --print_ref_calls=False --haploid_precise=False --haploid_sensitive=False --include_all_ctgs=False --no_phasing_for_fa=False
[INFO] Check envrionment variables
[INFO] --include_all_ctgs not enabled, use chr{1..22,X,Y} and {1..22,X,Y} by default
[INFO] Call variant in contigs: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y
[INFO] Chunk number for each contig: 50 49 40 39 37 35 32 30 29 28 28 27 24 22 21 19 17 16 12 13 10 11 32 12
[INFO] 1/7 Calling variants using pileup model
tee: SNVs/log/1_call_var_bam_pileup.log: No such file or directory
parallel: Error: Cannot write to --joblog SNVs/log/parallel_1_call_var_bam_pileup.log.`

Thanks,
Medhat

**Comment by zhengzhenxian** [comment]
Hi Medhat,

Thanks so much for reporting this. Can you try to use an absolute output directory? When running the run_clair3.sh shell script, the working directory will transfer, so the parallel cannot find the relative joblog path correctly.

You can try to change `--output SNVs`  to ` --output ${HOME}/SNVs`.

**Comment by huangnengCSU** [comment]
Hi,
    I had the same error. And when all the inputs use the absolute path, the error does not appear.

**Comment by MeHelmy** [comment]
As mentioned by @huangnengCSU  it works.
Thanks,
Medhat

**Comment by aquaskyline** [comment]
Relative path supported in v0.1-r1.

**Comment by MeHelmy** [comment]
> Relative path supported in v0.1-r1.

For both bam and output directory? 
Thank you

**Comment by aquaskyline** [comment]
Yes. Are you using docker? If yes, absolute paths are still necessary, It's a problem with docker, and I have updated my previous reply to show when is absolute path still necessary. We are also adding a checkpoint that will stop the program early if a docker environment and non-absolute paths are detected.

**Comment by MeHelmy** [comment]
I'm using conda  env installation.
