### ISSUE TITLE
[ERROR] BAM file not found

### ISSUE THREAD

**Issue by christopher-vollmers** [HKU-BAL/Clair3#50]
Hi, 

I'm trying to run clair3 on a sorted index bam file using the following command

`sudo docker run -it hkubal/clair3:latest /opt/bin/run_clair3.sh --bam_fn /mnt/memorycore4/nanopore_data/realTimeTest/basecalled/consensus/demultiplexed/Sample1.sorted.bam -f ~/refs/hg38.fa -m ~/Downloads/models/ont_guppy5 -t 30 -p ont -o ~/Downloads/test/`

But am only getting this far

`[INFO] CLAIR3 VERSION: v0.1-r6
[INFO] BAM FILE PATH: /mnt/memorycore4/nanopore_data/realTimeTest/basecalled/consensus/demultiplexed/Sample1.sorted.bam
[INFO] REFERENCE FILE PATH: /home/ig88/refs/hg38.fa
[INFO] MODEL PATH: /home/ig88/Downloads/models/ont_guppy5
[INFO] OUTPUT FOLDER: /home/ig88/Downloads/test/
[INFO] PLATFORM: ont
[INFO] THREADS: 30
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX:
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.3
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: False

[ERROR] BAM file /mnt/memorycore4/nanopore_data/realTimeTest/basecalled/consensus/demultiplexed/Sample1.sorted.bam not found`

The file exists at the path that is given as does its index.

Any idea what might be happening here?

Thank you,
Chris

**Comment by zhengzhenxian** [comment]
Hi, Chirs,

You might need to add volume (`-v`) to run the docker container. You could try like:
```
BAM_FOLDER="/mnt/memorycore4/nanopore_data/realTimeTest/basecalled/consensus/demultiplexed"
REF_FOLDER="${HOME}/refs"
OUTPUT_FOLDER="${HOME}/Downloads"

sudo docker run -it \
-v ${BAM_FOLDER}:${BAM_FOLDER} \
-v ${REF_FOLDER}:${REF_FOLDER} \
-v ${OUTPUT_FOLDER}:${OUTPUT_FOLDER} \
hkubal/clair3:latest /opt/bin/run_clair3.sh \
    -b /mnt/memorycore4/nanopore_data/realTimeTest/basecalled/consensus/demultiplexed/Sample1.sorted.bam \
    -f ${HOME}/refs/hg38.fa \
    -m ${HOME}/Downloads/models/ont_guppy5 \
    -t 30 \
    -p ont \
    -o ${HOME}/Downloads/test
```

Hope it helps. Thanks!

**Comment by christopher-vollmers** [comment]
That fixed it. Apologies for me not being too familiar with docker. Thank you for your help.

Best,
Chris
