### ISSUE TITLE
Clair3 ONT model

### ISSUE THREAD

**Issue by kokyriakidis** [HKU-BAL/Clair3#51]
Hi!

Let's say I have ONT data basecalled with Guppy 5. I see there are two models trained. One of them used HG002 with Guppy5_sup. How does clair3 choose the model?

`--model_path=/opt/models/ont` will just choose the most recent model or I should enter `--model_path=/opt/models/ont_guppy5`?

**Comment by zhengzhenxian** [comment]
Hi,

We recommand use the `--model_path=/opt/models/ont_guppy5` for ONT Guppy5 data and `--model_path=/opt/models/ont` for Guppy3 and Guppy4 data. Here is the [pre-trained model detail](https://github.com/HKU-BAL/Clair3#pre-trained-models) for your reference. 

Hope it helps. Thanks!

**Comment by zhengzhenxian** [comment]
@rekham1077, 'ont_guppy5' is just the soft-link of 'r941_prom_sup_g506' for consistency with the previous release. You might use either of them to call your Guppy 5 data.

**Comment by ftostevin-ont** [comment]
@rekham1077 There is currently no R10.3-specific model. I expect that you will get best performance with `ont_guppy5`, despite this being trained on R9.4.1 data.

**Comment by llk578496** [comment]
Hi all!
I have a set of data using r9.4.1 flow cell sequenced on Gridion, basecalled with SUP and guppy 5.0.11, may I know it is ok to use 'r941_prom_sup_g506' as the model? Or is there a pre-trained model for 'r941_min_sup_g506' ?

**Comment by zhengzhenxian** [comment]
@llk578496 there is no `r941_min_sup_g506` pre-trained model available currently. We suggest you use the `r941_prom_sup_g506` model for your sequencing data.

**Comment by aquaskyline** [comment]
@llk578496 `r941_prom_sup_g506` works on MinION, GridION, and PromethION data.
