### ISSUE TITLE
Wrong allele frequency and depth for haploid Illumina data

### ISSUE THREAD

**Issue by BertBog** [HKU-BAL/Clair3#54]
Dear,

I have been trying out Clair3 for haploid variant calling in bacterial datasets using both Illumina and ONT data and have obtained great performance so far.
However, when I'm comparing SNPs called across different samples I noticed some strange behavior in the variant calling at some positions with mixed nucleotides.

For the screenshot below you can see that this position the reference base is present at high allele frequency (~80%), but still Clair3 calls a variant call with the wrong depth and allele frequency:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
NC_002695.2     345587  .       A       C       16.73   PASS    P       GT:GQ:DP:AF     1/1:16:10:1

![image](https://user-images.githubusercontent.com/16325875/134508931-6bfa5655-ea4a-4dc0-846e-eb0723996fd6.png)

Is this a bug, or is there another reason why this occurs?

I'm using Clair3 v0.1-r6 with the Clair3-illumina Conda environment installed according to the instruction on GitHub.
The command that I used is:
`run_clair3.sh --bam_fn=TIAC1169.bam --ref_fn=reference.fasta --platform ilmn --model_path=models/ilmn --output=out --no_phasing_for_fa --include_all_ctgs --haploid_precise --threads=2
`
I have extracted the region of the BAM file in the archive below, which also contains the reference genome and the VCF file I obtained:
[variants_tiac1169.zip](https://github.com/HKU-BAL/Clair3/files/7217637/variants_tiac1169.zip)

**Comment by aquaskyline** [comment]
Well received and turn back to you soon.

**Comment by zhengzhenxian** [comment]
Hi,

When scanning the BAM alignment, Clair3 **discarded** secondary alignments, supplementary alignments and reads with mapping quality < 5. Those reads were considered not confident enough for calling. The output `DP` and `AF` tags were also calculated after filtering. 

Here is the `samtools mpileup` output, where there were only 10 'C' bases remaining,  which is consistent with the Infos in the vcf. 
```
samtools mpileup TIAC1169.bam -F 2316 --min-MQ 5 | grep 345587
[mpileup] 1 samples in 1 input files
NC_002695.2     345587  N       10      cccccccccc      GGGGFGGGFG
```
You might want to add the same filtering in IGV for consistency. Thanks!

**Comment by BertBog** [comment]
Thank you for your quick response, makes sense indeed.
I think I can close the issue now.
