### ISSUE TITLE
cannot get the data: Alignments, GRCh38

### ISSUE THREAD

**Issue by shiying-sxu** [HKU-BAL/Clair3#59]
I cannot open the network:
http://www.bio8.cs.hku.hk/clairvoyante/orginalData_hg001/ont-hg38-minimap2-rel6/rel6_hs38d1.sorted.bam,
how can i get the BAM file?

**Comment by zhengzhenxian** [comment]
Here are also some other ONT HG001 data from [GIAB](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/NA12878/Ultralong_OxfordNanopore/) or from [human-pangenomics](https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=NHGRI_UCSC_panel/HG001/nanopore/Guppy_4.2.2/) for your reference.

**Comment by aquaskyline** [comment]
We suggest you using pre-trained models provided by us or ONT.
