### ISSUE TITLE
Error in training model 

### ISSUE THREAD

**Issue by shiying1595** [HKU-BAL/Clair3#62]
Dear author:
Hello, I encountered some problems when running the program：
When I try to train the model, run the command：
${PYTHON3} ${CLAIR3} Train \
    --bin_fn ${BINS_FOLDER_PATH} \
    --ochk_prefix ${MODEL_FOLDER_PATH}/pileup \
    --pileup \
    --add_indel_length False \
    --random_validation \
    --platform ${PLATFORM}
An error occurred：Floating point exception (core dumped) 
When I commented out the unnecessary parameters for training, 
${PYTHON3} ${CLAIR3} Train \
    --bin_fn ${BINS_FOLDER_PATH} \
    --ochk_prefix ${MODEL_FOLDER_PATH}/pileup \
I got an error again:
ValueError: Input 0 of layer conv2d is incompatible with the layer: expected ndim=4, found ndim=3. Full shape received: [0, 33, 18]

Can you help me see how to solve it?
thank you very much!

**Comment by aquaskyline** [comment]
We are unable to help you to solve it. "Float point exception" means some problems in your running environment.
