### ISSUE TITLE
How to generate the quick_demo.bed file in ONT Variant Calling Quick Demo

### ISSUE THREAD

**Issue by shiying1595** [HKU-BAL/Clair3#65]
echo -e "${CONTIGS}\t${START_POS}\t${END_POS}" > ${INPUT_DIR}/quick_demo.bed
Unable to implement this command, hand-write a bed file by myself, 
chr20	100000	300000
the result shows：
[ERROR] BED file work/Clair3-main/data/datatest/chr20/quick_demo.bed provides but not found

can you help me ?

**Comment by zhengzhenxian** [comment]
Hi,
The input BED file is not found, pls make sure it exists. You might want to generate the quick_demo.bed like:
```
CONTIGS="chr20"
START_POS=100000
END_POS=300000
echo -e "${CONTIGS}\t${START_POS}\t${END_POS}" > ${INPUT_DIR}/quick_demo.bed
```
