### ISSUE TITLE
Minimum depth and minimum base quality for haploid variant calling

### ISSUE THREAD

**Issue by llk578496** [HKU-BAL/Clair3#66]
Hi, could we set the minimum depth and minimum base quality in haploid variant calling for nanopore reads (e.g. > 60X and Qscore > 13)?

**Comment by zhengzhenxian** [comment]
Hi,

You might need to clone the repository and modify the two options (`--minCoverage` and `--minBQ`) to achieve it.  There are four lines to change (https://github.com/HKU-BAL/Clair3/blob/main/preprocess/CreateTensorPileup.py#L495, https://github.com/HKU-BAL/Clair3/blob/main/preprocess/CreateTensorPileup.py#L501, https://github.com/HKU-BAL/Clair3/blob/main/preprocess/CreateTensorFullAlignment.py#L912 and https://github.com/HKU-BAL/Clair3/blob/main/preprocess/CreateTensorFullAlignment.py#L918). 

Then you can run Clair3 using the modified `run_clair3.sh` entry.  The changes might affect the performance significantly so please check the outputs carefully.

**Comment by llk578496** [comment]
@zhengzhenxian Thanks a lot!
