### ISSUE TITLE
the number of parameters of the trained model

### ISSUE THREAD

**Issue by shiying1595** [HKU-BAL/Clair3#68]
Sorry for another question. I want to check the number of parameters of the trained model, but I can’t find how to calculate it. Can you help me? In addition, I want to use code to visualize model input. I can’t find the code in the doc folder. Can you provide it? Or can you guide me?
Thank you very much! Thank you!
Best wishes!
Ying

**Comment by aquaskyline** [comment]
Number of parameters:
https://stackoverflow.com/questions/38160940/how-to-count-total-number-of-trainable-parameters-in-a-tensorflow-model

Draw input:
https://seaborn.pydata.org/generated/seaborn.heatmap.html
