### ISSUE TITLE
Are spliced/cDNA ONT reads supported?

### ISSUE THREAD

**Issue by billytcl** [HKU-BAL/Clair3#69]
This isn't clear in the documentation -- are transcriptome/spliced reads from cDNA supported by Clair3?

**Comment by aquaskyline** [comment]
As long as the reads are properly aligned.

**Comment by billytcl** [comment]
My reads are minimap aligned with some soft clips on each side. Will that
be fine?

**Comment by aquaskyline** [comment]
It should be fine, although we have not tested Clair3 on any RNA data, and I don't have a feeling about how Clair3 would perform on RNA data. Let us know more.

**Comment by sparthib** [comment]
hi @aquaskyline , any idea at present on how Clair3 works on ONT cDNA data? thanks!
