### ISSUE TITLE
multi bam files calling 

### ISSUE THREAD

**Issue by zhoudreames** [HKU-BAL/Clair3#71]
can i used multiple bam files to calling variants by using clair3 ？

**Comment by aquaskyline** [comment]
Could you please specify is it multiple bam files of a single sample or multiple samples.

**Comment by zhoudreames** [comment]
> Could you please specify is it multiple bam files of a single sample or multiple samples.

multiple samples

**Comment by aquaskyline** [comment]
No since Clair3 is not a joint caller. You can output GVCF and then use joint callers for joint calling.

**Comment by zhoudreames** [comment]
ok,thanks~
