### ISSUE TITLE
Variant Calling in Low-Complexity Regions

### ISSUE THREAD

**Issue by zhoudreames** [HKU-BAL/Clair3#72]
there are some variants where located in Low-Complexity Regions can not be identified by using clair3 HiFi mode. how to solve it ？ thanks ~
![image](https://user-images.githubusercontent.com/54714639/145783239-ab31f1e2-0357-43c1-afac-f0483fb00647.png)

**Comment by aquaskyline** [comment]
It seems most of the reads are with 0 or very low mapping quality. Clair3 does not make use of alignments with MQ<5 by default settings. You can set `--minMQ` to 0 to make use of all alignments but the accuracy could suffer especially at the low complexity regions.

**Comment by zhoudreames** [comment]
thanks~
