### ISSUE TITLE
aligner for variant calling using PacBio HiFi reads

### ISSUE THREAD

**Issue by PengNi** [HKU-BAL/Clair3#73]
Dear the authors,

Thanks for this great tool! 
I want to try the lastest version of minimap2 (v2.23) to align PacBio HiFi reads before using Clair3 for variant calling. So I am wondering if the aligner significantly influences the results, since the pre-trained hifi model was trained on aligned reads of pbmm2 (wrapper of minimap2 v2.15), I guess?

Thanks in advance!

Best,
Peng

**Comment by aquaskyline** [comment]
Hi Peng, different versions of the same aligner wouldn't affect Clair3's performance too much unless there are changes to the default parameters that significantly changes the alignments.

**Comment by PengNi** [comment]
Dear Dr. Luo, thanks very much for your reply. I notice that there are some differences between the default parameters of these two tools (_minimap2 -x map-hifi_ vs _pbmm2 --preset CCS_), so I'll try both for a comparison.
```shell
# minimap2 -x map-hifi:
-k19 -w19 -U50,500 -g10k -A1 -B4 -O6,26 -E2,1 -s200
# pbmm2 --preset CCS:
-k 19 -w 10 -u -o 5 -O 56 -e 4 -E 1 -A 2 -B 5 -z 400 -Z 50  -r 2000 -L 0.5 -g 5000
```
Closing this issue now.
