### ISSUE TITLE
Can we run Clair3 with CLR data using ONT model?

### ISSUE THREAD

**Issue by SHuang-Broad** [HKU-BAL/Clair3#74]
Hi,

I have a simple Q: would you expect Clair3 to run on CLR data using the ONT model?
We experimented with that but it looks like Clair3 refuses to run it.
The reason we say "it looks like" is because there appears to be no log. It simply quits.

Here's the command

```bash
/opt/bin/run_clair3.sh  \
    --bam_fn=/cromwell_root/fc-36ec993a-12dc-4644-9554-33f5d5508088/c09f3fd1-ec2c-4593-a742-4a474d81f8f2/PBCLRWholeGenome/f12c387f-3f0c-45cd-8434-5df1dad6bd41/call-CallVariants/CallVariants/1c224795-4983-4a48-8d6d-d7b8082bb580/call-SmallVariantsScatter/shard-0/cacheCopy/subset.bam \
    --ref_fn=/cromwell_root/broad-dsde-methods-long-reads/resources/references/grch38_noalt/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa \
    --threads=16 \
    --platform=ont \
    --model_path="/opt/models/ont" \
    --sample_name="test" --gvcf --include_all_ctgs \
    --output="./"
```

Thanks!
Steve

**Comment by aquaskyline** [comment]
Unfortunately, the answer is no. Clair3's models fit the very fine details of the input, thus even though CLR data might have an error rate that is high and around the level of ONT pre-Guppy 2 data, they are different in many other dimensions including the error profiles and patterns.

However, the reason why your command doesn't run should be different, Clair3 doesn't check the platform of the input data.

**Comment by SHuang-Broad** [comment]
Thanks!
That makes sense (though it would be good if there's a way to train a model on CLR data).

On the not-running issue, is there a debug flag that we can turn on for checking what happened?
Thanks!
Steve

**Comment by aquaskyline** [comment]
We indeed though about training a model for CLR data, but unfortunately we found insufficient CLR on the GIAB standard samples, it's unstandable since PacBio has discountinued the support of CLR data.

In terms of the running issue, Clair3 will output a list of parameters before it starts with the real works, so you might want to find clues from your running environment at first.

**Comment by SHuang-Broad** [comment]
That's enough to get us started. Thank you!
