### ISSUE TITLE
empty vcf output file when calling variants in a diploid genome

### ISSUE THREAD

**Issue by ogrecio** [HKU-BAL/Clair3#75]
Hi I installed clair3 using miniconda in my HPC facilities. 
Linux version: Linux version 3.10.0-862.14.4.el7.x86_64 (mockbuild@x86-040.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Sep 21 09:07:21 UTC 2018

I need to extract SNP variant from a cow diploid genome sequenced with a GridION. I have a reference genome (fasta) and the variants of interest in a vcf file.

I executed Clair3 as:
MODEL_NAME="r941_prom_hac_g360+g422"         # e.g. r941_prom_hac_g360+g422
run_clair3.sh --bam_fn=sample.bam --ref_fn=referenceGenome.fa --vcf_fn=reference-SNPs.vcf.gz --threads=6 --platform="ont" --model_path="${CONDA_PREFIX}/bin/models/${MODEL_NAME}" --output=outdir

I got an empty output vcf file, and a long log file that I attach below.

Could you please let me know what I am doing wrong? Thank you!

[run_clair3.log](https://github.com/HKU-BAL/Clair3/files/7831744/run_clair3.log)

**Comment by zhengzhenxian** [comment]
Hi,
   Seems the `tables` and `numpy` packages were not installed correctly:
```
import tables
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/clair3/lib/python3.6/site-packages/tables/__init__.py", line 24, in <module>
    from .utilsextension import (
  File "__init__.pxd", line 918, in init tables.utilsextension
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

   You might need to reinstall Clair3 in a new virtual conda environment or try [singularity](https://github.com/HKU-BAL/Clair3#option-2-singularity) installation in your HPC environment.  Thanks!

**Comment by aquaskyline** [comment]
It seems you've installed Clair3 in the base conda environment. Couldy you please try creating a new environment using `conda create`. Let us know if it works.

**Comment by ogrecio** [comment]
Hi, I followed the instructions and even installed the packages with pip. 
I created the environment again with the following instructions, but I'm still having the same error and empty vcf file.

conda create -n clair3 -c bioconda clair3 python=3.6.10 -y
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/clair3

  added / updated specs:
    - clair3
    - python=3.6.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    charset-normalizer-2.0.10  |     pyhd8ed1ab_0          34 KB  conda-forge
    libcurl-7.81.0             |       h2574ce0_0         338 KB  conda-forge
    requests-2.27.1            |     pyhd8ed1ab_0          53 KB  conda-forge
    tensorboard-plugin-wit-1.8.1|     pyhd8ed1ab_0         668 KB  conda-forge
    urllib3-1.26.8             |     pyhd8ed1ab_1         100 KB  conda-forge
    zipp-3.7.0                 |     pyhd8ed1ab_0          12 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.2 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  _tflow_select      pkgs/main/linux-64::_tflow_select-2.3.0-mkl
  absl-py            conda-forge/noarch::absl-py-1.0.0-pyhd8ed1ab_0
  astor              conda-forge/noarch::astor-0.8.1-pyh9f0ad1d_0
  astunparse         conda-forge/noarch::astunparse-1.6.3-pyhd8ed1ab_0
  biopython          conda-forge/linux-64::biopython-1.79-py36h8f6f2f9_0
  blinker            conda-forge/noarch::blinker-1.4-py_1
  blosc              conda-forge/linux-64::blosc-1.21.0-h9c3ff4c_0
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py36h8f6f2f9_1001
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  c-ares             conda-forge/linux-64::c-ares-1.18.1-h7f98852_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2021.10.8-ha878542_0
  cachetools         conda-forge/noarch::cachetools-2.1.0-py_0
  certifi            conda-forge/linux-64::certifi-2021.5.30-py36h5fab9bb_0
  cffi               conda-forge/linux-64::cffi-1.14.4-py36h211aa47_0
  charset-normalizer conda-forge/noarch::charset-normalizer-2.0.10-pyhd8ed1ab_0
  clair3             bioconda/noarch::clair3-0.1.9-hdfd78af_0
  click              conda-forge/linux-64::click-8.0.1-py36h5fab9bb_0
  cryptography       conda-forge/linux-64::cryptography-35.0.0-py36hb60f036_0
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  dataclasses        conda-forge/noarch::dataclasses-0.8-pyh787bdff_2
  expat              conda-forge/linux-64::expat-2.4.2-h9c3ff4c_0
  freetype           conda-forge/linux-64::freetype-2.10.4-h0708190_1
  gast               conda-forge/noarch::gast-0.3.3-py_0
  gdbm               conda-forge/linux-64::gdbm-1.18-h0a1914f_2
  google-auth        conda-forge/noarch::google-auth-1.2.1-py_0
  google-auth-oauth~ conda-forge/noarch::google-auth-oauthlib-0.4.1-py_2
  google-pasta       conda-forge/noarch::google-pasta-0.2.0-pyh8c360ce_0
  grpcio             conda-forge/linux-64::grpcio-1.38.1-py36h8e87921_0
  h5py               conda-forge/linux-64::h5py-2.10.0-nompi_py36h4510012_106
  hdf5               conda-forge/linux-64::hdf5-1.10.6-nompi_h6a2412b_1114
  htslib             bioconda/linux-64::htslib-1.10.2-hd3b49d5_1
  idna               conda-forge/noarch::idna-3.1-pyhd3deb0d_0
  importlib-metadata conda-forge/linux-64::importlib-metadata-4.8.1-py36h5fab9bb_0
  isa-l              conda-forge/linux-64::isa-l-2.30.0-ha770c72_4
  jpeg               conda-forge/linux-64::jpeg-9d-h36c2ea0_0
  keras-preprocessi~ conda-forge/noarch::keras-preprocessing-1.1.2-pyhd8ed1ab_0
  kiwisolver         conda-forge/linux-64::kiwisolver-1.3.1-py36h605e78d_1
  krb5               conda-forge/linux-64::krb5-1.19.2-hcc1bbae_3
  lcms2              conda-forge/linux-64::lcms2-2.11-hcbb858e_1
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  libblas            conda-forge/linux-64::libblas-3.9.0-12_linux64_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-12_linux64_openblas
  libcurl            conda-forge/linux-64::libcurl-7.81.0-h2574ce0_0
  libdeflate         conda-forge/linux-64::libdeflate-1.6-h516909a_0
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-h516909a_1
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-11.2.0-h1d223b6_11
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-11.2.0-h69a702a_11
  libgfortran5       conda-forge/linux-64::libgfortran5-11.2.0-h5c6108e_11
  libgomp            conda-forge/linux-64::libgomp-11.2.0-h1d223b6_11
  liblapack          conda-forge/linux-64::liblapack-3.9.0-12_linux64_openblas
  libnghttp2         conda-forge/linux-64::libnghttp2-1.43.0-h812cca2_1
  libopenblas        conda-forge/linux-64::libopenblas-0.3.18-pthreads_h8fe5266_0
  libpng             conda-forge/linux-64::libpng-1.6.37-h21135ba_2
  libprotobuf        conda-forge/linux-64::libprotobuf-3.18.0-h780b84a_1
  libssh2            conda-forge/linux-64::libssh2-1.10.0-ha56f1ee_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-11.2.0-he4da1e4_11
  libtiff            conda-forge/linux-64::libtiff-4.1.0-hc7e4089_6
  libwebp-base       conda-forge/linux-64::libwebp-base-1.1.0-h36c2ea0_3
  libzlib            conda-forge/linux-64::libzlib-1.2.11-h36c2ea0_1013
  lz4-c              conda-forge/linux-64::lz4-c-1.9.2-he1b5a44_3
  lzo                conda-forge/linux-64::lzo-2.10-h516909a_1000
  markdown           conda-forge/noarch::markdown-3.3.6-pyhd8ed1ab_0
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.3.4-py36hd391965_0
  mock               conda-forge/linux-64::mock-4.0.3-py36h5fab9bb_1
  ncurses            conda-forge/linux-64::ncurses-6.2-h58526e2_4
  networkx           conda-forge/noarch::networkx-2.6.3-pyhd8ed1ab_1
  numexpr            conda-forge/linux-64::numexpr-2.7.3-py36h0cdc3f0_0
  numpy              conda-forge/linux-64::numpy-1.19.5-py36hfc0c790_2
  oauthlib           conda-forge/noarch::oauthlib-3.1.1-pyhd8ed1ab_0
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openssl            conda-forge/linux-64::openssl-1.1.1l-h7f98852_0
  opt_einsum         conda-forge/noarch::opt_einsum-3.3.0-pyhd8ed1ab_1
  pandas             conda-forge/linux-64::pandas-1.1.5-py36h284efc9_0
  parallel           conda-forge/linux-64::parallel-20191122-0
  pbzip2             conda-forge/linux-64::pbzip2-1.1.13-0
  perl               conda-forge/linux-64::perl-5.32.1-1_h7f98852_perl5
  pigz               pkgs/main/linux-64::pigz-2.4-h84994c4_0
  pillow             conda-forge/linux-64::pillow-8.1.0-py36h4f9996e_1
  pip                conda-forge/noarch::pip-21.3.1-pyhd8ed1ab_0
  protobuf           conda-forge/linux-64::protobuf-3.18.0-py36hc4f0c31_0
  pyasn1             conda-forge/noarch::pyasn1-0.4.8-py_0
  pyasn1-modules     bioconda/linux-64::pyasn1-modules-0.0.5-py36_0
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pyfaidx            bioconda/noarch::pyfaidx-0.6.3.1-pyh5e36f6f_1
  pyjwt              conda-forge/noarch::pyjwt-2.3.0-pyhd8ed1ab_1
  pyopenssl          conda-forge/noarch::pyopenssl-21.0.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.0.6-pyhd8ed1ab_0
  pypy3.6            conda-forge/linux-64::pypy3.6-7.3.2-h45e8706_2
  pysam              bioconda/linux-64::pysam-0.16.0.1-py36h4c34d4e_1
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py36h5fab9bb_3
  pytables           conda-forge/linux-64::pytables-3.6.1-py36hb7ec5aa_3
  python             conda-forge/linux-64::python-3.6.10-h8356626_1011_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python-isal        conda-forge/linux-64::python-isal-0.11.1-py36h8f6f2f9_0
  python_abi         conda-forge/linux-64::python_abi-3.6-2_cp36m
  pytz               conda-forge/noarch::pytz-2021.3-pyhd8ed1ab_0
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  requests           conda-forge/noarch::requests-2.27.1-pyhd8ed1ab_0
  requests-oauthlib  conda-forge/noarch::requests-oauthlib-1.3.0-pyh9f0ad1d_0
  rsa                bioconda/linux-64::rsa-3.1.4-py36_0
  samtools           bioconda/linux-64::samtools-1.10-h2e538c0_3
  scipy              conda-forge/linux-64::scipy-1.5.3-py36h81d768a_1
  setuptools         conda-forge/linux-64::setuptools-58.0.4-py36h5fab9bb_2
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  sqlite             conda-forge/linux-64::sqlite-3.37.0-h9cd32fc_0
  tensorboard        conda-forge/noarch::tensorboard-2.3.0-py_0
  tensorboard-plugi~ conda-forge/noarch::tensorboard-plugin-wit-1.8.1-pyhd8ed1ab_0
  tensorflow         pkgs/main/linux-64::tensorflow-2.2.0-mkl_py36h5a57954_0
  tensorflow-base    pkgs/main/linux-64::tensorflow-base-2.2.0-mkl_py36hd506778_0
  tensorflow-estima~ conda-forge/linux-64::tensorflow-estimator-2.6.0-py36hc4f0c31_0
  termcolor          conda-forge/noarch::termcolor-1.1.0-py_2
  tk                 conda-forge/linux-64::tk-8.6.11-h27826a3_1
  tornado            conda-forge/linux-64::tornado-6.1-py36h8f6f2f9_1
  typing_extensions  conda-forge/noarch::typing_extensions-4.0.1-pyha770c72_0
  urllib3            conda-forge/noarch::urllib3-1.26.8-pyhd8ed1ab_1
  werkzeug           conda-forge/noarch::werkzeug-2.0.1-pyhd8ed1ab_0
  whatshap           bioconda/linux-64::whatshap-1.0-py36hf1ae8f4_1
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  wrapt              conda-forge/linux-64::wrapt-1.13.1-py36h8f6f2f9_0
  xopen              conda-forge/linux-64::xopen-1.2.0-py36h5fab9bb_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zipp               conda-forge/noarch::zipp-3.7.0-pyhd8ed1ab_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h36c2ea0_1013
  zstd               conda-forge/linux-64::zstd-1.4.4-h6597ccf_3



Downloading and Extracting Packages
zipp-3.7.0           | 12 KB     | ############################################################################################################ | 100% 
requests-2.27.1      | 53 KB     | ############################################################################################################ | 100% 
urllib3-1.26.8       | 100 KB    | ############################################################################################################ | 100% 
libcurl-7.81.0       | 338 KB    | ############################################################################################################ | 100% 
charset-normalizer-2 | 34 KB     | ############################################################################################################ | 100% 
tensorboard-plugin-w | 668 KB    | ############################################################################################################ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate clair3
#
# To deactivate an active environment, use
#
#     $ conda deactivate

**Comment by aquaskyline** [comment]
From the error message `ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject`, it seems to be a system compatibility problem. Using [Sigularity](https://github.com/HKU-BAL/Clair3#option-2-singularity) for installation might solve your problem.

**Comment by ogrecio** [comment]
Thank you for your answers!

I fixed the problem including in my script `export PYTHONNOUSERSITE=0` because my conda environment was pointing to my $HOME, and using the wrong packages.
