### ISSUE TITLE
incorrect SNP calling at low seq depth

### ISSUE THREAD

**Issue by ogrecio** [HKU-BAL/Clair3#76]
I need to make SNP variant calling in a sample with a low sequencing depth (<7x) with ONT. I am obtaining nearly 40% misscalled variants.
Is there any way to improve this performance? 
The [INFO] FULL ALIGN PROPORTION: 0.7 parameter can be tuned? Has this anything to do with the alignment proportion of the reads? Can I somehow be more strict?

Thank you in advance!

Here the info from clair3:
[INFO] CLAIR3 VERSION: v0.1-r9
[INFO] BAM FILE PATH: sample.fastq.bam
[INFO] REFERENCE FILE PATH: ref_genome.fa
[INFO] MODEL PATH: /mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/clair3/bin/models/r941_prom_hac_g360+g422
[INFO] OUTPUT FOLDER: Clair3.barcode10
[INFO] PLATFORM: ont
[INFO] THREADS: 12
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: variants.vcf.gz
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: /mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/clair3
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] USER DEFINED SNP THRESHOLD: 0.25
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: True
[INFO] ENABLE REMOVING INTERMEDIATE FILES: True
[INFO] ENABLE PHASING VCF OUTPUT: False
[INFO] ENABLE LONG INDEL CALLING: False

**Comment by zhengzhenxian** [comment]
Hi,

 We found you enabled  `no_phasing_for_fa`  option, the performance might be greatly affected if you disabled phasing when calling diploid species.  

The `FULL ALIGN PROPORTION: 0.7` can be tuned using `--var_pct_full` option, but we considered 0.7 rather an ideal parameter for Guppy3,4 data.

**Comment by ogrecio** [comment]
Hi,
thanks for your response. Actually I also tried disabling `no_phasing_for_fa` option but there was not too much change in my case. What do you reckon the problem may be? Even for variants with DP>3, the misscall ratio is very high.

**Comment by aquaskyline** [comment]
An average depth <7x is resonable to have around 40% miscalled variants eventhough we expect the SNP could still have a F1-score around 0.8. We suggest 1) use Guppy 5 for basecalling your data, and use Clair3's latest Guppy5 model, that gives a boost on the number of correct variants called, 2) depending on your application, you might want to trust some variants with QUAL below 2, but be cautious that most of the variants with QUAL below 2 are false positives.
