### ISSUE TITLE
Clair force calling using callVarBam calls more number of variants than included in a vcf file

### ISSUE THREAD

**Issue by teketelah** [HKU-BAL/Clair3#78]
Hello,
The vcf file I used for force calling had 57 million SNVs for whole genome variant calling. Force calling using callVarBam and vcf provided with --call_fn resulted in calling 322 million SNVs. Does force calling mean calling those variants in the vcf file plus additional variants or something is wrong? Normally force calling should only call variants at sites provided in the vcf file. I used the following script:

python clair.py callVarBam --chkpnt_fn "/clair/ont/model" --ref_fn "ref.fasta" --bam_fn "alignment.bam" --threshold "0.2" --minCoverage "4" --pypy "pypy3" --samtools "samtools" --delay "10" --threads "4" --sampleName "sample1" --vcf_fn "all_merged.vcf" --ctgName "$CONTIG_NAME" --call_fn "input.vcf"

Any help please?

**Comment by aquaskyline** [comment]
This is a question about Clair, please refer to the answer at https://github.com/HKU-BAL/Clair/issues/65
