### ISSUE TITLE
Clair3 BAM index bai file not found

### ISSUE THREAD

**Issue by Teklu67** [HKU-BAL/Clair3#80]
Hello, 
I was trying to run Clair3 but I got this error: [ERROR] BAM index bai file not found, please use 'samtools index $BAM' first. 
I tried to index the Bam file using Samtools but I get this: samtools index: failed to create index for "input.bam": Numerical result out of range try using a csi index. A csi index is already in the directory and that was what I used in the previous Clair version. The chromosome size is very large for a bai index which is not uncommon in plants. Is there a work around this in Clair3? 
Thank you so much.
Regards!

**Comment by aquaskyline** [comment]
We are proposing a fix, will turn back to you in two days.

**Comment by zhengzhenxian** [comment]
Hi,
We suggest you `mv bam.csi bam.bai` to skip the bai file suffix check now. We will add a csi index check in the next release, thanks!

**Comment by zhengzhenxian** [comment]
We have not exposed the  **--min_coverage** option for users, you might need to modify two lines(https://github.com/HKU-BAL/Clair3/blob/main/shared/param_p.py#L21 and https://github.com/HKU-BAL/Clair3/blob/main/shared/param_f.py#L18) to set the coverage. We will try to add this option in the next release.

**Comment by Teklu67** [comment]
Great, thank you so much.

**Comment by aquaskyline** [comment]
`.csi` and `--min_coverage` supported in v0.1-r11.
