### ISSUE TITLE
install runtime error 

### ISSUE THREAD

**Issue by liu2005678** [HKU-BAL/Clair3#81]
I installed with docker image with command "**docker pull hkubal/clair3**". and it seems success.
however, when i run with 
docker run -it   -v ${INPUT_DIR}:${INPUT_DIR}   -v ${OUTPUT_DIR}:${OUTPUT_DIR}   hkubal/clair3:latest   /opt/bin/run_clair3.sh   --bam_fn=${INPUT_DIR}/hp119_sorted.bam   --ref_fn=${INPUT_DIR}/UA802_23S.fa   --threads=${THREADS}     --platform="ont"   --model_path="${INPUT_DIR}/${MODEL_NAME}"  --output=${OUTPUT_DIR}

**it shows the following error**   

**[ERROR] Conda prefix not found, please activate clair3 conda environment first, model path: /evo/Antibiotic_Resistance/clair3/r941_prom_hac_g360+g422**

it confuse me, i didn't installed with bioconda.

I also tried with bioconda also, not able to install 

clair3 -> python=3.6.10The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0
Your installed version is: 2.27

**Comment by zhengzhenxian** [comment]
Hi, we used anaconda to install packages to build docker image. The error is that the model path `/evo/Antibiotic_Resistance/clair3/r941_prom_hac_g360+g422` is not found, could you try to use  `--model_path="/opt/models/r941_prom_hac_g360+g422"` to re-run the [command](https://github.com/HKU-BAL/Clair3#option-1--docker-pre-built-image) using docker. 

Pls let us know if it did not work for you, thanks!

**Comment by liu2005678** [comment]
It works, thank you very much!
