### ISSUE TITLE
Force calling in two different samples is not similar

### ISSUE THREAD

**Issue by Teklu67** [HKU-BAL/Clair3#82]
Hello,
I was calling SV using clair3 pipeline in two different samples. I used the following command for force calling only at sites provided in "input_merged.vcf" in both samples. 
/run_clair3.sh --bam_fn="input_sorted.bam" --ref_fn="reference.fasta" --threads="15" --platform="ont" --model_path="/clair/model/r941_prom_sup_g5014/" --remove_intermediate_dir --sample_name=name --vcf_fn="input_merged.vcf" --print_ref_calls --output="/output_dir".

However, the resulting vcf in each sample contained nearly similar number of sites but when comparing the sites they are not quite similar. Below is the result from comparing sites in each sample using vcftools:

Comparing sites in VCF files...
Found 7832718 sites common to both files.
Found 100856 sites only in main file.
Found 95537 sites only in second file.
Found 86024 non-matching overlapping sites.
After filtering, kept 8019598 out of a possible 8019598 Sites

Technically force calling should only call at sites provided in the vcf input and the two samples have similar number of calls right? This creates problem when merging the vcf for the two samples because I get a lot of ./. for the ones missing in the other sample. Any suggestion please...

**Comment by zhengzhenxian** [comment]
Hi, 
For genotyping mode, Clair3 only calls and reports the sites that exceed the minimum coverage(2) and minimum allele frequency(SNP:0.08, Indel:0.15). Those skipped low-confident sites might lead to the inconsistency of two samples. You might need to check the coverage and AF of the missing sites in each sample.

**Comment by Teklu67** [comment]
Ok, thanks so much for the reply.
