### ISSUE TITLE
minimum coverage call

### ISSUE THREAD

**Issue by rodrigopsav** [HKU-BAL/Clair3#83]
Hello,
Is there any flag to specify minimum coverage for variant calling?

Thanks

**Comment by zhengzhenxian** [comment]
Hi,

We have not exposed the `--min_coverage` option for users now, you might need to modify two lines(https://github.com/HKU-BAL/Clair3/blob/main/shared/param_p.py#L21 and https://github.com/HKU-BAL/Clair3/blob/main/shared/param_f.py#L18) to set the minimum coverage. We will add the `min_coverage` option in the next release.

**Comment by aquaskyline** [comment]
Thanks for asking, as we have collected multiple requests on this, we will expose `--min_coverage` in the next revision v0.1-r11.

**Comment by rodrigopsav** [comment]
Thanks for the answer!

**Comment by aquaskyline** [comment]
Added in v0.1-r11.
