### ISSUE TITLE
"No full-alignment output for file" stops merged file process

### ISSUE THREAD

**Issue by EdRyder** [HKU-BAL/Clair3#86]
Hi,

I'm doing some variant analysis on  PCR fragments(~10kb) and since switching from ONT fast to hac basecalling on some sample data I now get the following errors:

[INFO] 6/7 Call low-quality variants using full-alignment model
[INFO] Delay 4 seconds before starting variant calling ...
[mpileup] 1 samples in 1 input files
Calling variants ...
Total processed positions in xyz (chunk 1/1) : 0
[ERROR] No full-alignment output for file <path>/tmp/full_alignment_output/full_alignment_xyz.0_1.vcf
Total time elapsed: 0.00 s
[INFO] No vcf output for file <path>/tmp/full_alignment_output/full_alignment_xyz.0_1.vcf, remove empty file
...
[WARNING] No vcf file found with prefix:<path>/tmp/full_alignment_output/full_alignment, output empty vcf file
[WARNING] Copying pileup.vcf.gz to <path>/merge_output.vcf.gz
[INFO] Exit in full-alignment variant calling

The program then stops and I don't get the useful 'phased_merge_output.vcf.gz' output file I previously did using the fast basecalling. The log files 7_merge_vcf.log and  8_phase_vcf_output.log are also missing as the program exits at stage 6.

I'm presuming the issue is that switching to the hac model results in my data not having any low quality variant calls that needs the full alignment? Is there any way to switch/hack this so the empty file is ignored and the rest of the script carries on please? I could fill in a line of dummy data if that would help, but I'm unsure where that would go. 
If I use the --pileup_only switch it then doesn't do phasing  or final files either, sadly.

Thanks!
Ed

<path> added to replace full file path
xyz = custom chromosome name

**Comment by zhengzhenxian** [comment]
Hi, @EdRyder 

We consider no full-alignment output (without any candidates) is abnormal, so we exited in after full-alignment calling in advance. Could you kindly give the number of pileup calls (exclude the header)?

In your case, you might take `pileup.vcf.gz` as the final output, and then apply Whatshap `phase` on `pileup.vcf.gz` if phased output is required.
