### ISSUE TITLE
Should Clair3 be re-trained with new human T2T reference?

### ISSUE THREAD

**Issue by SHuang-Broad** [HKU-BAL/Clair3#95]
Hi,

Given the newly released human T2T reference (v2.0), should Clair3 be re-trained against that reference?
I'm unsure what the benefits this would bring, so am interested in your thoughts.

Thank you!
Steve

**Comment by aquaskyline** [comment]
Hi Steve, not sure. In Clair's paper, we concluded training on 38 over 37 had negligible improvement. But T2T-CHM13 could be another story with many more variants in repetitive sequences for training. Let's wait for GIAB to release a truth set with the new reference genome.

**Comment by SHuang-Broad** [comment]
Looking forward to it. Thanks!
