### ISSUE TITLE
python 3.6 is EOL

### ISSUE THREAD

**Issue by SamStudio8** [HKU-BAL/Clair3#96]
The default installation environment for Clair3 uses Python 3.6.10 (https://github.com/HKU-BAL/Clair3/blob/main/Dockerfile#L25). Python 3.6 has reached end of life and has not received security updates since December 2021. Unless there are specific reasons to keep using 3.6, could I suggest updating your build to use Python 3.7 as a minimum (which is supported until 2023) and seeing if the build breaks?

**Comment by aquaskyline** [comment]
Previously, for the sake of using Clair3 on Mac M1, we tried using Python 3.9 and TF 2.5 on Clair3 and got no problem. It is likely that Clair3 will be using newer Python and TF in the next version.

**Comment by aquaskyline** [comment]
Upgraded to Python 3.9 in v0.1-r12.
