### ISSUE TITLE
v0.1-r11 not outputting a phased bam file

### ISSUE THREAD

**Issue by danrdanny** [HKU-BAL/Clair3#97]
Hi, thanks for the updates to Clair3. I was excited to see the speedup and use of longphase.

I am running clair3 by passing a reference genome, aligned bam file, output dir, as well as a target bed file with the `--bed_fn` command as well as the longphase option `--longphase_for_phasing`.

I am having trouble figuring out how to get this version to output a phased bam file. I would expect to find the file in `<outputDir>/tmp/phase_output/phase_bam/` but that directory is empty at the end of my run. I do get a phased vcf at the end, as the file `phased_merge_output.vcf.gz` is correctly populated with phased SNVs. A phased bam was available in the previous version of Clair3--so did this go away with this new version?

**Comment by zhengzhenxian** [comment]
Hi,
In v0.1-r11,  we integrated reads haplotagging into full-alignment calling to avoid generating intermediate BAM files. The phased BAMs in `<outputDir>/tmp/phase_output/phase_bam/` are actually an intermediate phased BAM phased by heterozygous pileup SNP candidates. We would suggest you to use the final output(`phased_merge_output.vcf.gz`) and [WhatsHap haplotag](https://whatshap.readthedocs.io/en/latest/guide.html#whatshap-haplotag-tagging-reads-by-haplotype-for-visualization) submodule to get a more reliable phased BAM.

**Comment by danrdanny** [comment]
Got it--thank you!
