### ISSUE TITLE
1-bp off chromosome end event generated.

### ISSUE THREAD

**Issue by SHuang-Broad** [HKU-BAL/Clair3#99]
Hi, 

I'd like to report a strange variant generated in the gVCF.

```
chr1	248946423	.	N	<NON_REF>	0	.	END=248956422	GT:GQ:MIN_DP:PL	./.:1:0:0,0,0
```
Note that the position data is after the `END` annotation.

The command that generated this is 

```bash
platform="hifi"
/opt/bin/run_clair3.sh \
            --bam_fn=${bam} \
            --ref_fn=${ref_fasta} \
            --threads=${num_core} \
            --platform=${platform} \
            --model_path="/opt/models/${platform}" \
            --sample_name=$SM \
            --gvcf \
            "--include_all_ctgs" \
            --output="./"
```

with docker `hkubal/clair3:v0.1-r6`.
The bam was subset to chr1 beforehand.

Thanks,
Steve

**Comment by zhengzhenxian** [comment]
Hi, Steve,
We have not found similar end range problem in gvcf output before. I noticed that you are still using v0.1-r6, could you kindly try our latest version(v0.1-r11)? We have fixed several GVCF range issues in this release, not sure it could solve this end range. And pls kindly let us know if this bug still exists in our latest release, thanks!

Zhenxian
